/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.pa

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoUUID
import adventureworks.person.businessentity.BusinessentityId
import typo.runtime.PgTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers

/** View: pe.pa */
data class PaViewRow(
  /** Points to [adventureworks.person.password.PasswordRow.businessentityid] */
  val id: BusinessentityId,
  /** Points to [adventureworks.person.password.PasswordRow.businessentityid] */
  val businessentityid: BusinessentityId,
  /** Points to [adventureworks.person.password.PasswordRow.passwordhash] */
  val passwordhash: /* max 128 chars */ String,
  /** Points to [adventureworks.person.password.PasswordRow.passwordsalt] */
  val passwordsalt: /* max 10 chars */ String,
  /** Points to [adventureworks.person.password.PasswordRow.rowguid] */
  val rowguid: TypoUUID,
  /** Points to [adventureworks.person.password.PasswordRow.modifieddate] */
  val modifieddate: TypoLocalDateTime
) {
  companion object {
    val _rowParser: RowParser<PaViewRow> = RowParsers.of(BusinessentityId.pgType, BusinessentityId.pgType, PgTypes.text, PgTypes.text, TypoUUID.pgType, TypoLocalDateTime.pgType, { t0, t1, t2, t3, t4, t5 -> PaViewRow(t0!!, t1!!, t2!!, t3!!, t4!!, t5!!) }, { row -> arrayOf<Any?>(row.id, row.businessentityid, row.passwordhash, row.passwordsalt, row.rowguid, row.modifieddate) })
  }
}