/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.check_constraint_test

import dev.typr.dsl.FieldsBase
import dev.typr.dsl.Path
import dev.typr.dsl.SqlExpr.FieldLike
import dev.typr.dslsc.RelationStructure
import dev.typr.dslsc.SqlExpr
import dev.typr.dslsc.SqlExpr.Field
import dev.typr.dslsc.SqlExpr.IdField
import dev.typr.dslsc.SqlExpr.OptField
import dev.typr.dslsc.TupleExpr4
import dev.typr.foundations.RowCodec
import dev.typr.foundationssc.Db2Types

class CheckConstraintTestFields(val `_path`: java.util.List[Path]) extends TupleExpr4[CheckConstraintTestId, Int, String, BigDecimal] with RelationStructure[CheckConstraintTestFields, CheckConstraintTestRow]  with FieldsBase[CheckConstraintTestRow] {
  def id: IdField[CheckConstraintTestId, CheckConstraintTestRow] = {
    new IdField[CheckConstraintTestId, CheckConstraintTestRow](
      _path,
      "ID",
      _.id,
      None,
      None,
      (row, value) => row.copy(id = value),
      CheckConstraintTestId.db2Type.underlying
    )
  }

  def age: Field[Int, CheckConstraintTestRow] = {
    new Field[Int, CheckConstraintTestRow](
      _path,
      "AGE",
      _.age,
      None,
      None,
      (row, value) => row.copy(age = value),
      Db2Types.integer.underlying
    )
  }

  def status: Field[String, CheckConstraintTestRow] = {
    new Field[String, CheckConstraintTestRow](
      _path,
      "STATUS",
      _.status,
      None,
      None,
      (row, value) => row.copy(status = value),
      Db2Types.varchar.underlying
    )
  }

  def price: OptField[BigDecimal, CheckConstraintTestRow] = {
    new OptField[BigDecimal, CheckConstraintTestRow](
      _path,
      "PRICE",
      _.price,
      None,
      None,
      (row, value) => row.copy(price = value),
      Db2Types.decimal.underlying
    )
  }

  override def columns: java.util.List[FieldLike[?, CheckConstraintTestRow]] = java.util.List.of(this.id.underlying, this.age.underlying, this.status.underlying, this.price.underlying)

  override def rowCodec: RowCodec[CheckConstraintTestRow] = CheckConstraintTestRow.rowCodec.underlying

  override def withPaths(`_path`: java.util.List[Path]): RelationStructure[CheckConstraintTestFields, CheckConstraintTestRow] = new CheckConstraintTestFields(`_path`)

  override def `_1`: SqlExpr[CheckConstraintTestId] = id

  override def `_2`: SqlExpr[Int] = age

  override def `_3`: SqlExpr[String] = status

  override def `_4`: SqlExpr[BigDecimal] = price
}

object CheckConstraintTestFields {
  val structure: CheckConstraintTestFields = new CheckConstraintTestFields(java.util.Collections.emptyList())
}