/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.person;

import adventureworks.person.businessentity.BusinessentityFields;
import adventureworks.person.businessentity.BusinessentityId;
import adventureworks.person.businessentity.BusinessentityRow;
import adventureworks.public_.Name;
import adventureworks.public_.NameStyle;
import adventureworks.userdefined.FirstName;
import dev.typr.foundations.PgTypes;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.data.Xml;
import dev.typr.foundations.dsl.FieldsExpr;
import dev.typr.foundations.dsl.ForeignKey;
import dev.typr.foundations.dsl.Path;
import dev.typr.foundations.dsl.RelationStructure;
import dev.typr.foundations.dsl.SqlExpr.Field;
import dev.typr.foundations.dsl.SqlExpr.FieldLike;
import dev.typr.foundations.dsl.SqlExpr.IdField;
import dev.typr.foundations.dsl.SqlExpr.OptField;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface PersonFields extends FieldsExpr<PersonRow> {
  record Impl(List<Path> _path)
      implements PersonFields, RelationStructure<PersonFields, PersonRow> {
    @Override
    public IdField<BusinessentityId, PersonRow> businessentityid() {
      return new IdField<BusinessentityId, PersonRow>(
          _path,
          "businessentityid",
          PersonRow::businessentityid,
          Optional.empty(),
          Optional.of("int4"),
          (row, value) -> row.withBusinessentityid(value),
          BusinessentityId.pgType);
    }
    ;

    @Override
    public Field<String, PersonRow> persontype() {
      return new Field<String, PersonRow>(
          _path,
          "persontype",
          PersonRow::persontype,
          Optional.empty(),
          Optional.of("bpchar"),
          (row, value) -> row.withPersontype(value),
          PgTypes.bpchar);
    }
    ;

    @Override
    public Field<NameStyle, PersonRow> namestyle() {
      return new Field<NameStyle, PersonRow>(
          _path,
          "namestyle",
          PersonRow::namestyle,
          Optional.empty(),
          Optional.of("bool"),
          (row, value) -> row.withNamestyle(value),
          NameStyle.pgType);
    }
    ;

    @Override
    public OptField<String, PersonRow> title() {
      return new OptField<String, PersonRow>(
          _path,
          "title",
          PersonRow::title,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withTitle(value),
          PgTypes.text);
    }
    ;

    @Override
    public Field</* user-picked */ FirstName, PersonRow> firstname() {
      return new Field</* user-picked */ FirstName, PersonRow>(
          _path,
          "firstname",
          PersonRow::firstname,
          Optional.empty(),
          Optional.of("varchar"),
          (row, value) -> row.withFirstname(value),
          FirstName.pgType);
    }
    ;

    @Override
    public OptField<Name, PersonRow> middlename() {
      return new OptField<Name, PersonRow>(
          _path,
          "middlename",
          PersonRow::middlename,
          Optional.empty(),
          Optional.of("varchar"),
          (row, value) -> row.withMiddlename(value),
          Name.pgType);
    }
    ;

    @Override
    public Field<Name, PersonRow> lastname() {
      return new Field<Name, PersonRow>(
          _path,
          "lastname",
          PersonRow::lastname,
          Optional.empty(),
          Optional.of("varchar"),
          (row, value) -> row.withLastname(value),
          Name.pgType);
    }
    ;

    @Override
    public OptField<String, PersonRow> suffix() {
      return new OptField<String, PersonRow>(
          _path,
          "suffix",
          PersonRow::suffix,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withSuffix(value),
          PgTypes.text);
    }
    ;

    @Override
    public Field<Integer, PersonRow> emailpromotion() {
      return new Field<Integer, PersonRow>(
          _path,
          "emailpromotion",
          PersonRow::emailpromotion,
          Optional.empty(),
          Optional.of("int4"),
          (row, value) -> row.withEmailpromotion(value),
          PgTypes.int4);
    }
    ;

    @Override
    public OptField<Xml, PersonRow> additionalcontactinfo() {
      return new OptField<Xml, PersonRow>(
          _path,
          "additionalcontactinfo",
          PersonRow::additionalcontactinfo,
          Optional.empty(),
          Optional.of("xml"),
          (row, value) -> row.withAdditionalcontactinfo(value),
          PgTypes.xml);
    }
    ;

    @Override
    public OptField<Xml, PersonRow> demographics() {
      return new OptField<Xml, PersonRow>(
          _path,
          "demographics",
          PersonRow::demographics,
          Optional.empty(),
          Optional.of("xml"),
          (row, value) -> row.withDemographics(value),
          PgTypes.xml);
    }
    ;

    @Override
    public Field<UUID, PersonRow> rowguid() {
      return new Field<UUID, PersonRow>(
          _path,
          "rowguid",
          PersonRow::rowguid,
          Optional.empty(),
          Optional.of("uuid"),
          (row, value) -> row.withRowguid(value),
          PgTypes.uuid);
    }
    ;

    @Override
    public Field<LocalDateTime, PersonRow> modifieddate() {
      return new Field<LocalDateTime, PersonRow>(
          _path,
          "modifieddate",
          PersonRow::modifieddate,
          Optional.empty(),
          Optional.of("timestamp"),
          (row, value) -> row.withModifieddate(value),
          PgTypes.timestamp);
    }
    ;

    @Override
    public List<FieldLike<?, PersonRow>> columns() {
      return java.util.List.of(
          this.businessentityid(),
          this.persontype(),
          this.namestyle(),
          this.title(),
          this.firstname(),
          this.middlename(),
          this.lastname(),
          this.suffix(),
          this.emailpromotion(),
          this.additionalcontactinfo(),
          this.demographics(),
          this.rowguid(),
          this.modifieddate());
    }
    ;

    @Override
    public RelationStructure<PersonFields, PersonRow> withPaths(List<Path> _path) {
      return new Impl(_path);
    }
    ;
  }
  ;

  static Impl structure() {
    return new Impl(java.util.Collections.emptyList());
  }
  ;

  IdField<BusinessentityId, PersonRow> businessentityid();

  Field<String, PersonRow> persontype();

  Field<NameStyle, PersonRow> namestyle();

  OptField</* max 8 chars */ String, PersonRow> title();

  Field</* user-picked */ FirstName, PersonRow> firstname();

  OptField<Name, PersonRow> middlename();

  Field<Name, PersonRow> lastname();

  OptField</* max 10 chars */ String, PersonRow> suffix();

  Field<Integer, PersonRow> emailpromotion();

  OptField<Xml, PersonRow> additionalcontactinfo();

  OptField<Xml, PersonRow> demographics();

  Field<UUID, PersonRow> rowguid();

  Field<LocalDateTime, PersonRow> modifieddate();

  default ForeignKey<BusinessentityFields, BusinessentityRow> fkBusinessentity() {
    return ForeignKey.<BusinessentityFields, BusinessentityRow>of(
            "person.FK_Person_BusinessEntity_BusinessEntityID")
        .<BusinessentityId>withColumnPair(
            businessentityid(), BusinessentityFields::businessentityid);
  }
  ;

  @Override
  List<FieldLike<?, PersonRow>> columns();

  @Override
  default RowParser<PersonRow> rowParser() {
    return PersonRow._rowParser;
  }
  ;
}
