/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.bec

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoUUID
import adventureworks.person.businessentity.BusinessentityId
import adventureworks.person.contacttype.ContacttypeId
import typo.runtime.RowParser
import typo.runtime.RowParsers
import typo.runtime.RowParsers.Tuple6

/** View: pe.bec */
data class BecViewRow(
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.businessentityid] */
  val id: BusinessentityId,
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.businessentityid] */
  val businessentityid: BusinessentityId,
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.personid] */
  val personid: BusinessentityId,
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.contacttypeid] */
  val contacttypeid: ContacttypeId,
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.rowguid] */
  val rowguid: TypoUUID,
  /** Points to [adventureworks.person.businessentitycontact.BusinessentitycontactRow.modifieddate] */
  val modifieddate: TypoLocalDateTime
) {
  companion object {
    val _rowParser: RowParser<BecViewRow> = RowParsers.of(BusinessentityId.pgType, BusinessentityId.pgType, BusinessentityId.pgType, ContacttypeId.pgType, TypoUUID.pgType, TypoLocalDateTime.pgType, ::BecViewRow, { row -> Tuple6(row.id, row.businessentityid, row.personid, row.contacttypeid, row.rowguid, row.modifieddate) })
  }
}