/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public

import dev.typr.foundations.PgStruct
import dev.typr.foundations.PgType
import dev.typr.foundations.PgTypes

/** PostgreSQL composite type: public.person_name */
data class PersonName(
  val firstName: String?,
  val middleName: String?,
  val lastName: String?,
  val suffix: String?
) {
  companion object {
    val pgStruct: PgStruct<PersonName> =
      PgStruct.builder<PersonName>("public.person_name").nullableField("firstName", PgTypes.text, { v: PersonName -> v.firstName }).nullableField("middleName", PgTypes.text, { v: PersonName -> v.middleName }).nullableField("lastName", PgTypes.text, { v: PersonName -> v.lastName }).nullableField("suffix", PgTypes.text, { v: PersonName -> v.suffix }).build({ arr -> PersonName(arr[0] as? String, arr[1] as? String, arr[2] as? String, arr[3] as? String) })

    val pgType: PgType<PersonName> =
      pgStruct.asType()
  }
}