/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.pch

import adventureworks.production.product.ProductId
import java.time.LocalDateTime
import typo.runtime.PgTypes
import typo.scaladsl.RowParser
import typo.scaladsl.RowParsers
import typo.scaladsl.ScalaDbTypes

/** View: pr.pch */
case class PchViewRow(
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.productid]] */
  id: ProductId,
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.productid]] */
  productid: ProductId,
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.startdate]] */
  startdate: LocalDateTime,
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.enddate]] */
  enddate: LocalDateTime,
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.standardcost]] */
  standardcost: BigDecimal,
  /** Points to [[adventureworks.production.productcosthistory.ProductcosthistoryRow.modifieddate]] */
  modifieddate: LocalDateTime
)

object PchViewRow {
  val `_rowParser`: RowParser[PchViewRow] = RowParsers.of(ProductId.pgType, ProductId.pgType, PgTypes.timestamp, PgTypes.timestamp, ScalaDbTypes.PgTypes.numeric, PgTypes.timestamp)(PchViewRow.apply)(row => Array[Any](row.id, row.productid, row.startdate, row.enddate, row.standardcost, row.modifieddate))
}