/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.precision_types_null

import dev.typr.dslsc.DeleteBuilder
import dev.typr.dslsc.Dialect
import dev.typr.dslsc.SelectBuilder
import dev.typr.dslsc.UpdateBuilder
import dev.typr.foundationssc.Connection
import dev.typr.foundationssc.ConnectionRead
import dev.typr.foundationssc.Fragment
import scala.collection.mutable.ListBuffer
import testdb.precisetypes.Decimal10_2
import testdb.precisetypes.Decimal18_4
import testdb.precisetypes.Decimal5_2
import testdb.precisetypes.Int10
import testdb.precisetypes.Int18
import testdb.precisetypes.Int5
import testdb.precisetypes.String10
import testdb.precisetypes.String100
import testdb.precisetypes.String20
import testdb.precisetypes.String255
import testdb.precisetypes.String50
import dev.typr.foundationssc.Fragment.sql

class PrecisionTypesNullRepoImpl extends PrecisionTypesNullRepo {
  override def delete: DeleteBuilder[PrecisionTypesNullFields, PrecisionTypesNullRow] = DeleteBuilder.of(""""precision_types_null"""", PrecisionTypesNullFields.structure, Dialect.SQLITE)

  override def deleteById(id: PrecisionTypesNullId)(using c: Connection): Boolean = sql"""delete from "precision_types_null" where "id" = ${Fragment.encode(PrecisionTypesNullId.sqliteType, id)}""".update().run(using c) > 0

  override def deleteByIds(ids: List[PrecisionTypesNullId])(using c: Connection): Int = {
    val fragments: ListBuffer[Fragment] = ListBuffer()
    ids.foreach { id => fragments.addOne(Fragment.encode(PrecisionTypesNullId.sqliteType, id)): @scala.annotation.nowarn }
    return Fragment.concat(Fragment.of("""delete from "precision_types_null" where "id" in ("""), Fragment.comma(fragments), Fragment.of(")")).update().run(using c)
  }

  override def insert(unsaved: PrecisionTypesNullRow)(using c: Connection): PrecisionTypesNullRow = {
  sql"""insert into "precision_types_null"("id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0")
    values (${Fragment.encode(PrecisionTypesNullId.sqliteType, unsaved.id)}, ${Fragment.encode(String10.sqliteType.opt, unsaved.string10)}, ${Fragment.encode(String20.sqliteType.opt, unsaved.string20)}, ${Fragment.encode(String50.sqliteType.opt, unsaved.string50)}, ${Fragment.encode(String100.sqliteType.opt, unsaved.string100)}, ${Fragment.encode(String255.sqliteType.opt, unsaved.string255)}, ${Fragment.encode(Decimal5_2.sqliteType.opt, unsaved.decimal52)}, ${Fragment.encode(Decimal10_2.sqliteType.opt, unsaved.decimal102)}, ${Fragment.encode(Decimal18_4.sqliteType.opt, unsaved.decimal184)}, ${Fragment.encode(Int5.sqliteType.opt, unsaved.decimal50)}, ${Fragment.encode(Int10.sqliteType.opt, unsaved.decimal100)}, ${Fragment.encode(Int18.sqliteType.opt, unsaved.decimal180)})
    RETURNING "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0"
    """
    .updateReturning(PrecisionTypesNullRow.rowCodec.exactlyOne()).run(using c)
  }

  override def select: SelectBuilder[PrecisionTypesNullFields, PrecisionTypesNullRow] = SelectBuilder.of(""""precision_types_null"""", PrecisionTypesNullFields.structure, PrecisionTypesNullRow.rowCodec, Dialect.SQLITE)

  override def selectAll(using c: ConnectionRead): List[PrecisionTypesNullRow] = {
    sql"""select "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0"
    from "precision_types_null"
    """.query(PrecisionTypesNullRow.rowCodec.all()).run(using c)
  }

  override def selectById(id: PrecisionTypesNullId)(using c: ConnectionRead): Option[PrecisionTypesNullRow] = {
    sql"""select "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0"
    from "precision_types_null"
    where "id" = ${Fragment.encode(PrecisionTypesNullId.sqliteType, id)}""".query(PrecisionTypesNullRow.rowCodec.first()).run(using c)
  }

  override def selectByIds(ids: List[PrecisionTypesNullId])(using c: ConnectionRead): List[PrecisionTypesNullRow] = {
    val fragments: ListBuffer[Fragment] = ListBuffer()
    ids.foreach { id => fragments.addOne(Fragment.encode(PrecisionTypesNullId.sqliteType, id)): @scala.annotation.nowarn }
    return Fragment.concat(Fragment.of("""select "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0" from "precision_types_null" where "id" in ("""), Fragment.comma(fragments), Fragment.of(")")).query(PrecisionTypesNullRow.rowCodec.all()).run(using c)
  }

  override def selectByIdsTracked(ids: List[PrecisionTypesNullId])(using c: ConnectionRead): Map[PrecisionTypesNullId, PrecisionTypesNullRow] = {
    val ret: scala.collection.mutable.Map[PrecisionTypesNullId, PrecisionTypesNullRow] = scala.collection.mutable.Map.empty[PrecisionTypesNullId, PrecisionTypesNullRow]
    selectByIds(ids)(using c).foreach(row => ret.put(row.id, row): @scala.annotation.nowarn)
    return ret.toMap
  }

  override def update: UpdateBuilder[PrecisionTypesNullFields, PrecisionTypesNullRow] = UpdateBuilder.of(""""precision_types_null"""", PrecisionTypesNullFields.structure, PrecisionTypesNullRow.rowCodec, Dialect.SQLITE)

  override def update(row: PrecisionTypesNullRow)(using c: Connection): Boolean = {
    val id: PrecisionTypesNullId = row.id
    return sql"""update "precision_types_null"
    set "string10" = ${Fragment.encode(String10.sqliteType.opt, row.string10)},
    "string20" = ${Fragment.encode(String20.sqliteType.opt, row.string20)},
    "string50" = ${Fragment.encode(String50.sqliteType.opt, row.string50)},
    "string100" = ${Fragment.encode(String100.sqliteType.opt, row.string100)},
    "string255" = ${Fragment.encode(String255.sqliteType.opt, row.string255)},
    "decimal5_2" = ${Fragment.encode(Decimal5_2.sqliteType.opt, row.decimal52)},
    "decimal10_2" = ${Fragment.encode(Decimal10_2.sqliteType.opt, row.decimal102)},
    "decimal18_4" = ${Fragment.encode(Decimal18_4.sqliteType.opt, row.decimal184)},
    "decimal5_0" = ${Fragment.encode(Int5.sqliteType.opt, row.decimal50)},
    "decimal10_0" = ${Fragment.encode(Int10.sqliteType.opt, row.decimal100)},
    "decimal18_0" = ${Fragment.encode(Int18.sqliteType.opt, row.decimal180)}
    where "id" = ${Fragment.encode(PrecisionTypesNullId.sqliteType, id)}""".update().run(using c) > 0
  }

  override def upsert(unsaved: PrecisionTypesNullRow)(using c: Connection): PrecisionTypesNullRow = {
  sql"""INSERT INTO "precision_types_null"("id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0")
    VALUES (${Fragment.encode(PrecisionTypesNullId.sqliteType, unsaved.id)}, ${Fragment.encode(String10.sqliteType.opt, unsaved.string10)}, ${Fragment.encode(String20.sqliteType.opt, unsaved.string20)}, ${Fragment.encode(String50.sqliteType.opt, unsaved.string50)}, ${Fragment.encode(String100.sqliteType.opt, unsaved.string100)}, ${Fragment.encode(String255.sqliteType.opt, unsaved.string255)}, ${Fragment.encode(Decimal5_2.sqliteType.opt, unsaved.decimal52)}, ${Fragment.encode(Decimal10_2.sqliteType.opt, unsaved.decimal102)}, ${Fragment.encode(Decimal18_4.sqliteType.opt, unsaved.decimal184)}, ${Fragment.encode(Int5.sqliteType.opt, unsaved.decimal50)}, ${Fragment.encode(Int10.sqliteType.opt, unsaved.decimal100)}, ${Fragment.encode(Int18.sqliteType.opt, unsaved.decimal180)})
    ON CONFLICT ("id")
    DO UPDATE SET
      "string10" = EXCLUDED."string10",
    "string20" = EXCLUDED."string20",
    "string50" = EXCLUDED."string50",
    "string100" = EXCLUDED."string100",
    "string255" = EXCLUDED."string255",
    "decimal5_2" = EXCLUDED."decimal5_2",
    "decimal10_2" = EXCLUDED."decimal10_2",
    "decimal18_4" = EXCLUDED."decimal18_4",
    "decimal5_0" = EXCLUDED."decimal5_0",
    "decimal10_0" = EXCLUDED."decimal10_0",
    "decimal18_0" = EXCLUDED."decimal18_0"
    RETURNING "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0""""
    .updateReturning(PrecisionTypesNullRow.rowCodec.exactlyOne())
    .run(using c)
  }

  override def upsertBatch(unsaved: Iterator[PrecisionTypesNullRow])(using c: Connection): List[PrecisionTypesNullRow] = {
    sql"""INSERT INTO "precision_types_null"("id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0")
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT ("id")
    DO UPDATE SET
      "string10" = EXCLUDED."string10",
    "string20" = EXCLUDED."string20",
    "string50" = EXCLUDED."string50",
    "string100" = EXCLUDED."string100",
    "string255" = EXCLUDED."string255",
    "decimal5_2" = EXCLUDED."decimal5_2",
    "decimal10_2" = EXCLUDED."decimal10_2",
    "decimal18_4" = EXCLUDED."decimal18_4",
    "decimal5_0" = EXCLUDED."decimal5_0",
    "decimal10_0" = EXCLUDED."decimal10_0",
    "decimal18_0" = EXCLUDED."decimal18_0"
    RETURNING "id", "string10", "string20", "string50", "string100", "string255", "decimal5_2", "decimal10_2", "decimal18_4", "decimal5_0", "decimal10_0", "decimal18_0""""
      .updateReturningEach(PrecisionTypesNullRow.rowCodec, unsaved)
    .run(using c)
  }
}