/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.c;

import static typr.runtime.Fragment.interpolate;

import java.sql.Connection;
import java.util.List;
import typr.dsl.Dialect;
import typr.dsl.SelectBuilder;
import typr.runtime.Fragment;

public class CViewRepoImpl implements CViewRepo {
  @Override
  public SelectBuilder<CViewFields, CViewRow> select() {
    return SelectBuilder.of(
        "\"pr\".\"c\"", CViewFields.structure(), CViewRow._rowParser, Dialect.POSTGRESQL);
  }
  ;

  @Override
  public List<CViewRow> selectAll(Connection c) {
    return interpolate(
            Fragment.lit(
                "select \"id\", \"cultureid\", \"name\", \"modifieddate\"\nfrom \"pr\".\"c\"\n"))
        .query(CViewRow._rowParser.all())
        .runUnchecked(c);
  }
  ;
}
