/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders;

import com.fasterxml.jackson.annotation.JsonValue;
import dev.typr.foundations.Bijection;
import dev.typr.foundations.SqliteType;
import dev.typr.foundations.SqliteTypes;

/** Type for the primary key of table `orders` */
public record OrdersId(@JsonValue Long value) {
  public OrdersId withValue(Long value) {
    return new OrdersId(value);
  }

  @Override
  public java.lang.String toString() {
    return value.toString();
  }

  static public Bijection<OrdersId, Long> bijection =
    Bijection.of(OrdersId::value, OrdersId::new);

  static public SqliteType<OrdersId> sqliteType =
    SqliteTypes.integer.to(Bijection.of(OrdersId::new, OrdersId::value));
}