/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.order_items

import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Optional
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import testdb.orders.OrdersId
import testdb.products.ProductsId
import testdb.warehouses.WarehousesId
import typo.runtime.MariaText
import typo.runtime.MariaTypes

/** This class corresponds to a row in table `order_items` which has not been persisted yet */
case class OrderItemsRowUnsaved(
  /** 
   * Points to [[testdb.orders.OrdersRow.orderId]]
   */
  @JsonProperty("order_id") orderId: OrdersId,
  /** 
   * Points to [[testdb.products.ProductsRow.productId]]
   */
  @JsonProperty("product_id") productId: ProductsId,
  /**  */
  sku: String,
  /**  */
  @JsonProperty("product_name") productName: String,
  /**  */
  quantity: Integer,
  /**  */
  @JsonProperty("unit_price") unitPrice: java.math.BigDecimal,
  /**  */
  @JsonProperty("line_total") lineTotal: java.math.BigDecimal,
  /** Default: 0.0000

   */
  @JsonProperty("discount_amount") discountAmount: Defaulted[java.math.BigDecimal] = new UseDefault(),
  /** Default: 0.0000

   */
  @JsonProperty("tax_amount") taxAmount: Defaulted[java.math.BigDecimal] = new UseDefault(),
  /** Default: 'pending'

   */
  @JsonProperty("fulfillment_status") fulfillmentStatus: Defaulted[String] = new UseDefault(),
  /** Default: NULL
   * Points to [[testdb.warehouses.WarehousesRow.warehouseId]]
   */
  @JsonProperty("warehouse_id") warehouseId: Defaulted[Optional[WarehousesId]] = new UseDefault(),
  /** Default: NULL

   */
  notes: Defaulted[Optional[String]] = new UseDefault()
) {
  def toRow(
    discountAmountDefault: => java.math.BigDecimal,
    taxAmountDefault: => java.math.BigDecimal,
    fulfillmentStatusDefault: => String,
    warehouseIdDefault: => Optional[WarehousesId],
    notesDefault: => Optional[String],
    itemIdDefault: => OrderItemsId
  ): OrderItemsRow = {
    new OrderItemsRow(
      itemId = itemIdDefault,
      orderId = orderId,
      productId = productId,
      sku = sku,
      productName = productName,
      quantity = quantity,
      unitPrice = unitPrice,
      discountAmount = discountAmount.getOrElse(discountAmountDefault),
      taxAmount = taxAmount.getOrElse(taxAmountDefault),
      lineTotal = lineTotal,
      fulfillmentStatus = fulfillmentStatus.getOrElse(fulfillmentStatusDefault),
      warehouseId = warehouseId.getOrElse(warehouseIdDefault),
      notes = notes.getOrElse(notesDefault)
    )
  }
}

object OrderItemsRowUnsaved {
  given mariaText: MariaText[OrderItemsRowUnsaved] = MariaText.instance((row, sb) => { OrdersId.pgType.mariaText.unsafeEncode(row.orderId, sb); sb.append(MariaText.DELIMETER); ProductsId.pgType.mariaText.unsafeEncode(row.productId, sb); sb.append(MariaText.DELIMETER); MariaTypes.varchar.mariaText.unsafeEncode(row.sku, sb); sb.append(MariaText.DELIMETER); MariaTypes.varchar.mariaText.unsafeEncode(row.productName, sb); sb.append(MariaText.DELIMETER); MariaTypes.smallintUnsigned.mariaText.unsafeEncode(row.quantity, sb); sb.append(MariaText.DELIMETER); MariaTypes.decimal.mariaText.unsafeEncode(row.unitPrice, sb); sb.append(MariaText.DELIMETER); MariaTypes.decimal.mariaText.unsafeEncode(row.lineTotal, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.decimal.mariaText).unsafeEncode(row.discountAmount, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.decimal.mariaText).unsafeEncode(row.taxAmount, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.text.mariaText).unsafeEncode(row.fulfillmentStatus, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using WarehousesId.pgType.opt().mariaText).unsafeEncode(row.warehouseId, sb); sb.append(MariaText.DELIMETER); Defaulted.mariaText(using MariaTypes.tinytext.opt().mariaText).unsafeEncode(row.notes, sb) })
}