/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.employeepayhistory

import java.lang.RuntimeException
import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import java.util.function.Function
import java.util.stream.Collectors
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams

case class EmployeepayhistoryRepoMock(
  toRow: EmployeepayhistoryRowUnsaved => EmployeepayhistoryRow,
  map: HashMap[EmployeepayhistoryId, EmployeepayhistoryRow] = new HashMap[EmployeepayhistoryId, EmployeepayhistoryRow]()
) extends EmployeepayhistoryRepo {
  override def delete: DeleteBuilder[EmployeepayhistoryFields, EmployeepayhistoryRow] = {
    new DeleteBuilderMock(
      EmployeepayhistoryFields.structure,
      () => new ArrayList(map.values()),
      DeleteParams.empty(),
      row => row.compositeId,
      id => map.remove(id): @scala.annotation.nowarn
    )
  }

  override def deleteById(compositeId: EmployeepayhistoryId)(using c: Connection): java.lang.Boolean = Optional.ofNullable(map.remove(compositeId)).isPresent()

  override def deleteByIds(compositeIds: Array[EmployeepayhistoryId])(using c: Connection): Integer = {
    var count = 0
    compositeIds.foreach { id => if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1
    } }
    return count
  }

  override def insert(unsaved: EmployeepayhistoryRow)(using c: Connection): EmployeepayhistoryRow = {
    if (map.containsKey(unsaved.compositeId)) {
      throw new RuntimeException(s"id $unsaved.compositeId already exists")
    }
    map.put(unsaved.compositeId, unsaved): @scala.annotation.nowarn
    return unsaved
  }

  override def insert(unsaved: EmployeepayhistoryRowUnsaved)(using c: Connection): EmployeepayhistoryRow = insert(toRow(unsaved))(using c)

  override def insertStreaming(
    unsaved: java.util.Iterator[EmployeepayhistoryRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      count = count + 1L
    }
    return count
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override def insertUnsavedStreaming(
    unsaved: java.util.Iterator[EmployeepayhistoryRowUnsaved],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long = {
    var count = 0L
    while (unsaved.hasNext()) {
      val unsavedRow = unsaved.next()
      val row = toRow(unsavedRow)
      map.put(row.compositeId, row): @scala.annotation.nowarn
      count = count + 1L
    }
    return count
  }

  override def select: SelectBuilder[EmployeepayhistoryFields, EmployeepayhistoryRow] = new SelectBuilderMock(EmployeepayhistoryFields.structure, () => new ArrayList(map.values()), SelectParams.empty())

  override def selectAll(using c: Connection): java.util.List[EmployeepayhistoryRow] = new ArrayList(map.values())

  override def selectById(compositeId: EmployeepayhistoryId)(using c: Connection): Optional[EmployeepayhistoryRow] = Optional.ofNullable(map.get(compositeId))

  override def selectByIds(compositeIds: Array[EmployeepayhistoryId])(using c: Connection): java.util.List[EmployeepayhistoryRow] = {
    val result = new ArrayList[EmployeepayhistoryRow]()
    compositeIds.foreach { id => val opt = Optional.ofNullable(map.get(id)); if (opt.isPresent()) {
      result.add(opt.get()): @scala.annotation.nowarn
    } }
    return result
  }

  override def selectByIdsTracked(compositeIds: Array[EmployeepayhistoryId])(using c: Connection): java.util.Map[EmployeepayhistoryId, EmployeepayhistoryRow] = selectByIds(compositeIds)(using c).stream().collect(Collectors.toMap((row: EmployeepayhistoryRow) => row.compositeId, Function.identity()))

  override def update: UpdateBuilder[EmployeepayhistoryFields, EmployeepayhistoryRow] = {
    new UpdateBuilderMock(
      EmployeepayhistoryFields.structure,
      () => new ArrayList(map.values()),
      UpdateParams.empty(),
      row => row
    )
  }

  override def update(row: EmployeepayhistoryRow)(using c: Connection): java.lang.Boolean = {
    val shouldUpdate = Optional.ofNullable(map.get(row.compositeId)).filter(oldRow => (oldRow != row)).isPresent()
    if (shouldUpdate) {
      map.put(row.compositeId, row): @scala.annotation.nowarn
    }
    return shouldUpdate
  }

  override def upsert(unsaved: EmployeepayhistoryRow)(using c: Connection): EmployeepayhistoryRow = {
    map.put(unsaved.compositeId, unsaved): @scala.annotation.nowarn
    return unsaved
  }

  override def upsertBatch(unsaved: java.util.Iterator[EmployeepayhistoryRow])(using c: Connection): java.util.List[EmployeepayhistoryRow] = {
    val result = new ArrayList[EmployeepayhistoryRow]()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      result.add(row): @scala.annotation.nowarn
    }
    return result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override def upsertStreaming(
    unsaved: java.util.Iterator[EmployeepayhistoryRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer = {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map.put(row.compositeId, row): @scala.annotation.nowarn
      count = count + 1
    }
    return count
  }
}