enabled = true
version = "1.33.0"
style = "google"
skipSortingImports = false
skipRemovingUnusedImports = false
fixImportsOnly = false
skipReflowingLongStrings = false
skipJavadocFormatting = false
excludePaths = [
"**/generated-and-checked-in/**"
]
