/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.password;

import adventureworks.person.businessentity.BusinessentityId;
import adventureworks.person.person.PersonFields;
import adventureworks.person.person.PersonRow;
import dev.typr.foundations.PgTypes;
import dev.typr.foundations.RowParser;
import dev.typr.foundations.dsl.FieldsExpr;
import dev.typr.foundations.dsl.ForeignKey;
import dev.typr.foundations.dsl.Path;
import dev.typr.foundations.dsl.RelationStructure;
import dev.typr.foundations.dsl.SqlExpr.Field;
import dev.typr.foundations.dsl.SqlExpr.FieldLike;
import dev.typr.foundations.dsl.SqlExpr.IdField;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface PasswordFields extends FieldsExpr<PasswordRow> {
  record Impl(List<Path> _path)
      implements PasswordFields, RelationStructure<PasswordFields, PasswordRow> {
    @Override
    public IdField<BusinessentityId, PasswordRow> businessentityid() {
      return new IdField<BusinessentityId, PasswordRow>(
          _path,
          "businessentityid",
          PasswordRow::businessentityid,
          Optional.empty(),
          Optional.of("int4"),
          (row, value) -> row.withBusinessentityid(value),
          BusinessentityId.pgType);
    }
    ;

    @Override
    public Field<String, PasswordRow> passwordhash() {
      return new Field<String, PasswordRow>(
          _path,
          "passwordhash",
          PasswordRow::passwordhash,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withPasswordhash(value),
          PgTypes.text);
    }
    ;

    @Override
    public Field<String, PasswordRow> passwordsalt() {
      return new Field<String, PasswordRow>(
          _path,
          "passwordsalt",
          PasswordRow::passwordsalt,
          Optional.empty(),
          Optional.empty(),
          (row, value) -> row.withPasswordsalt(value),
          PgTypes.text);
    }
    ;

    @Override
    public Field<UUID, PasswordRow> rowguid() {
      return new Field<UUID, PasswordRow>(
          _path,
          "rowguid",
          PasswordRow::rowguid,
          Optional.empty(),
          Optional.of("uuid"),
          (row, value) -> row.withRowguid(value),
          PgTypes.uuid);
    }
    ;

    @Override
    public Field<LocalDateTime, PasswordRow> modifieddate() {
      return new Field<LocalDateTime, PasswordRow>(
          _path,
          "modifieddate",
          PasswordRow::modifieddate,
          Optional.empty(),
          Optional.of("timestamp"),
          (row, value) -> row.withModifieddate(value),
          PgTypes.timestamp);
    }
    ;

    @Override
    public List<FieldLike<?, PasswordRow>> columns() {
      return java.util.List.of(
          this.businessentityid(),
          this.passwordhash(),
          this.passwordsalt(),
          this.rowguid(),
          this.modifieddate());
    }
    ;

    @Override
    public RelationStructure<PasswordFields, PasswordRow> withPaths(List<Path> _path) {
      return new Impl(_path);
    }
    ;
  }
  ;

  static Impl structure() {
    return new Impl(java.util.Collections.emptyList());
  }
  ;

  IdField<BusinessentityId, PasswordRow> businessentityid();

  Field<String, PasswordRow> passwordhash();

  Field<String, PasswordRow> passwordsalt();

  Field<UUID, PasswordRow> rowguid();

  Field<LocalDateTime, PasswordRow> modifieddate();

  default ForeignKey<PersonFields, PersonRow> fkPerson() {
    return ForeignKey.<PersonFields, PersonRow>of("person.FK_Password_Person_BusinessEntityID")
        .<BusinessentityId>withColumnPair(businessentityid(), PersonFields::businessentityid);
  }
  ;

  @Override
  List<FieldLike<?, PasswordRow>> columns();

  @Override
  default RowParser<PasswordRow> rowParser() {
    return PasswordRow._rowParser;
  }
  ;
}
