/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package oracledb.contacts;

import dev.typr.dsl.DeleteBuilder;
import dev.typr.dsl.SelectBuilder;
import dev.typr.dsl.UpdateBuilder;
import dev.typr.foundations.Connection;
import dev.typr.foundations.ConnectionRead;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface ContactsRepo {
  DeleteBuilder<ContactsFields, ContactsRow> delete();

  Boolean deleteById(
    ContactsId contactId,
    Connection c
  );

  Integer deleteByIds(
    List<ContactsId> contactIds,
    Connection c
  );

  ContactsId insert(
    ContactsRow unsaved,
    Connection c
  );

  ContactsId insert(
    ContactsRowUnsaved unsaved,
    Connection c
  );

  SelectBuilder<ContactsFields, ContactsRow> select();

  List<ContactsRow> selectAll(ConnectionRead c);

  Optional<ContactsRow> selectById(
    ContactsId contactId,
    ConnectionRead c
  );

  List<ContactsRow> selectByIds(
    List<ContactsId> contactIds,
    ConnectionRead c
  );

  Map<ContactsId, ContactsRow> selectByIdsTracked(
    List<ContactsId> contactIds,
    ConnectionRead c
  );

  UpdateBuilder<ContactsFields, ContactsRow> update();

  Boolean update(
    ContactsRow row,
    Connection c
  );

  void upsert(
    ContactsRow unsaved,
    Connection c
  );

  void upsertBatch(
    Iterator<ContactsRow> unsaved,
    Connection c
  );
}