/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders

import dev.typr.foundations.kotlin.DeleteBuilder
import dev.typr.foundations.kotlin.SelectBuilder
import dev.typr.foundations.kotlin.UpdateBuilder
import java.sql.Connection
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map

interface OrdersRepo {
  abstract fun delete(): DeleteBuilder<OrdersFields, OrdersRow>

  abstract fun deleteById(
    orderId: OrdersId,
    c: Connection
  ): kotlin.Boolean

  abstract fun deleteByIds(
    orderIds: Array<OrdersId>,
    c: Connection
  ): Int

  abstract fun insert(
    unsaved: OrdersRow,
    c: Connection
  ): OrdersRow

  abstract fun insert(
    unsaved: OrdersRowUnsaved,
    c: Connection
  ): OrdersRow

  abstract fun select(): SelectBuilder<OrdersFields, OrdersRow>

  abstract fun selectAll(c: Connection): List<OrdersRow>

  abstract fun selectById(
    orderId: OrdersId,
    c: Connection
  ): OrdersRow?

  abstract fun selectByIds(
    orderIds: Array<OrdersId>,
    c: Connection
  ): List<OrdersRow>

  abstract fun selectByIdsTracked(
    orderIds: Array<OrdersId>,
    c: Connection
  ): Map<OrdersId, OrdersRow>

  abstract fun update(): UpdateBuilder<OrdersFields, OrdersRow>

  abstract fun update(
    row: OrdersRow,
    c: Connection
  ): kotlin.Boolean

  abstract fun upsert(
    unsaved: OrdersRow,
    c: Connection
  ): OrdersRow

  abstract fun upsertBatch(
    unsaved: Iterator<OrdersRow>,
    c: Connection
  ): List<OrdersRow>
}