/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.promotions

import java.lang.RuntimeException
import java.sql.Connection
import java.util.ArrayList
import java.util.Optional
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableIterator
import kotlin.collections.MutableMap
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams
import typo.runtime.internal.stringInterpolator.str

data class PromotionsRepoMock(
  val toRow: (PromotionsRowUnsaved) -> PromotionsRow,
  val map: MutableMap<PromotionsId, PromotionsRow> = mutableMapOf<PromotionsId, PromotionsRow>()
) : PromotionsRepo {
  override fun delete(): DeleteBuilder<PromotionsFields, PromotionsRow> = DeleteBuilderMock(PromotionsFields.structure, { map.values.toList() }, DeleteParams.empty(), { row -> row.promotionId }, { id -> map.remove(id) })

  override fun deleteById(
    promotionId: PromotionsId,
    c: Connection
  ): Boolean = Optional.ofNullable(map.remove(promotionId)).isPresent()

  override fun deleteByIds(
    promotionIds: Array<PromotionsId>,
    c: Connection
  ): Int {
    var count = 0
    for (id in promotionIds) {
      if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1
    }
    }
    return count
  }

  override fun insert(
    unsaved: PromotionsRow,
    c: Connection
  ): PromotionsRow {
    if (map.containsKey(unsaved.promotionId)) {
      throw RuntimeException(str("id $unsaved.promotionId already exists"))
    }
    map[unsaved.promotionId] = unsaved
    return unsaved
  }

  override fun insert(
    unsaved: PromotionsRowUnsaved,
    c: Connection
  ): PromotionsRow = insert(toRow(unsaved), c)

  override fun select(): SelectBuilder<PromotionsFields, PromotionsRow> = SelectBuilderMock(PromotionsFields.structure, { map.values.toList() }, SelectParams.empty())

  override fun selectAll(c: Connection): List<PromotionsRow> = map.values.toList()

  override fun selectById(
    promotionId: PromotionsId,
    c: Connection
  ): Optional<PromotionsRow> = Optional.ofNullable(map[promotionId])

  override fun selectByIds(
    promotionIds: Array<PromotionsId>,
    c: Connection
  ): List<PromotionsRow> {
    val result = ArrayList<PromotionsRow>()
    for (id in promotionIds) {
      val opt = Optional.ofNullable(map[id])
      if (opt.isPresent()) {
      result.add(opt.get())
    }
    }
    return result
  }

  override fun selectByIdsTracked(
    promotionIds: Array<PromotionsId>,
    c: Connection
  ): Map<PromotionsId, PromotionsRow> = selectByIds(promotionIds, c).associateBy({ row: PromotionsRow -> row.promotionId })

  override fun selectByUniqueCode(
    code: String,
    c: Connection
  ): Optional<PromotionsRow> = Optional.ofNullable(map.values.toList().find({ v -> (code == v.code) }))

  override fun update(): UpdateBuilder<PromotionsFields, PromotionsRow> = UpdateBuilderMock(PromotionsFields.structure, { map.values.toList() }, UpdateParams.empty(), { row -> row })

  override fun update(
    row: PromotionsRow,
    c: Connection
  ): Boolean {
    val shouldUpdate = Optional.ofNullable(map[row.promotionId]).filter({ oldRow -> (oldRow != row) }).isPresent()
    if (shouldUpdate) {
      map[row.promotionId] = row
    }
    return shouldUpdate
  }

  override fun upsert(
    unsaved: PromotionsRow,
    c: Connection
  ): PromotionsRow {
    map[unsaved.promotionId] = unsaved
    return unsaved
  }

  override fun upsertBatch(
    unsaved: MutableIterator<PromotionsRow>,
    c: Connection
  ): List<PromotionsRow> {
    val result = ArrayList<PromotionsRow>()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.promotionId] = row
      result.add(row)
    }
    return result
  }
}