/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.customer

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoUUID
import adventureworks.person.businessentity.BusinessentityId
import adventureworks.person.person.PersonFields
import adventureworks.person.person.PersonRow
import adventureworks.sales.salesterritory.SalesterritoryFields
import adventureworks.sales.salesterritory.SalesterritoryId
import adventureworks.sales.salesterritory.SalesterritoryRow
import adventureworks.sales.store.StoreFields
import adventureworks.sales.store.StoreRow
import java.util.Optional
import kotlin.collections.List
import typo.dsl.FieldsExpr
import typo.dsl.ForeignKey
import typo.dsl.Path
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.FieldLike
import typo.dsl.SqlExpr.IdField
import typo.dsl.SqlExpr.OptField
import typo.dsl.Structure.Relation
import typo.runtime.RowParser

interface CustomerFields : FieldsExpr<CustomerRow> {
  override fun columns(): List<FieldLike<*, CustomerRow>>

  fun customerid(): IdField<CustomerId, CustomerRow>

  fun fkPersonPerson(): ForeignKey<PersonFields, PersonRow> = ForeignKey.of<PersonFields, PersonRow>("sales.FK_Customer_Person_PersonID").withColumnPair(personid(), PersonFields::businessentityid)

  fun fkSalesterritory(): ForeignKey<SalesterritoryFields, SalesterritoryRow> = ForeignKey.of<SalesterritoryFields, SalesterritoryRow>("sales.FK_Customer_SalesTerritory_TerritoryID").withColumnPair(territoryid(), SalesterritoryFields::territoryid)

  fun fkStore(): ForeignKey<StoreFields, StoreRow> = ForeignKey.of<StoreFields, StoreRow>("sales.FK_Customer_Store_StoreID").withColumnPair(storeid(), StoreFields::businessentityid)

  fun modifieddate(): Field<TypoLocalDateTime, CustomerRow>

  fun personid(): OptField<BusinessentityId, CustomerRow>

  override fun rowParser(): RowParser<CustomerRow> = CustomerRow._rowParser

  fun rowguid(): Field<TypoUUID, CustomerRow>

  fun storeid(): OptField<BusinessentityId, CustomerRow>

  fun territoryid(): OptField<SalesterritoryId, CustomerRow>

  companion object {
    data class Impl(val _path: List<Path>) : CustomerFields, Relation<CustomerFields, CustomerRow> {
      override fun customerid(): IdField<CustomerId, CustomerRow> = IdField<CustomerId, CustomerRow>(_path, "customerid", CustomerRow::customerid, Optional.empty(), Optional.of("int4"), { row, value -> row.copy(customerid = value) }, CustomerId.pgType)

      override fun personid(): OptField<BusinessentityId, CustomerRow> = OptField<BusinessentityId, CustomerRow>(_path, "personid", CustomerRow::personid, Optional.empty(), Optional.of("int4"), { row, value -> row.copy(personid = value) }, BusinessentityId.pgType)

      override fun storeid(): OptField<BusinessentityId, CustomerRow> = OptField<BusinessentityId, CustomerRow>(_path, "storeid", CustomerRow::storeid, Optional.empty(), Optional.of("int4"), { row, value -> row.copy(storeid = value) }, BusinessentityId.pgType)

      override fun territoryid(): OptField<SalesterritoryId, CustomerRow> = OptField<SalesterritoryId, CustomerRow>(_path, "territoryid", CustomerRow::territoryid, Optional.empty(), Optional.of("int4"), { row, value -> row.copy(territoryid = value) }, SalesterritoryId.pgType)

      override fun rowguid(): Field<TypoUUID, CustomerRow> = Field<TypoUUID, CustomerRow>(_path, "rowguid", CustomerRow::rowguid, Optional.empty(), Optional.of("uuid"), { row, value -> row.copy(rowguid = value) }, TypoUUID.pgType)

      override fun modifieddate(): Field<TypoLocalDateTime, CustomerRow> = Field<TypoLocalDateTime, CustomerRow>(_path, "modifieddate", CustomerRow::modifieddate, Optional.of("text"), Optional.of("timestamp"), { row, value -> row.copy(modifieddate = value) }, TypoLocalDateTime.pgType)

      override fun columns(): List<FieldLike<*, CustomerRow>> = listOf(this.customerid(), this.personid(), this.storeid(), this.territoryid(), this.rowguid(), this.modifieddate())

      override fun copy(_path: List<Path>): Relation<CustomerFields, CustomerRow> = Impl(_path)
    }

    fun structure(): Impl = Impl(listOf())
  }
}