/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders_with_customer_details

import dev.typr.foundationssc.ConnectionRead
import java.time.LocalDateTime

trait OrdersWithCustomerDetailsSqlRepo {
  def apply(
    minAmount: Option[BigDecimal],
    startDate: Option[LocalDateTime]
  )(using c: ConnectionRead): List[OrdersWithCustomerDetailsSqlRow]
}