/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.businessentityaddress;

import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.customtypes.TypoUUID;
import adventureworks.person.address.AddressId;
import adventureworks.person.addresstype.AddresstypeId;
import adventureworks.person.businessentity.BusinessentityId;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.internal.arrayMap;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public class BusinessentityaddressRepoImpl implements BusinessentityaddressRepo {
  public DeleteBuilder<BusinessentityaddressFields, BusinessentityaddressRow> delete() {
    return DeleteBuilder.of("person.businessentityaddress", BusinessentityaddressFields.structure());
  };

  public Boolean deleteById(
    BusinessentityaddressId compositeId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "person"."businessentityaddress" where "businessentityid" = 
      """),
      BusinessentityId.pgType.encode(compositeId.businessentityid()),
      typo.runtime.Fragment.lit("""
       AND "addressid" = 
      """),
      AddressId.pgType.encode(compositeId.addressid()),
      typo.runtime.Fragment.lit("""
       AND "addresstypeid" = 
      """),
      AddresstypeId.pgType.encode(compositeId.addresstypeid()),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  public Integer deleteByIds(
    BusinessentityaddressId[] compositeIds,
    Connection c
  ) {
    BusinessentityId[] businessentityid = arrayMap.map(compositeIds, BusinessentityaddressId::businessentityid, BusinessentityId.class);;
      AddressId[] addressid = arrayMap.map(compositeIds, BusinessentityaddressId::addressid, AddressId.class);;
      AddresstypeId[] addresstypeid = arrayMap.map(compositeIds, BusinessentityaddressId::addresstypeid, AddresstypeId.class);;
    return interpolate(
             typo.runtime.Fragment.lit("""
                delete
                from "person"."businessentityaddress"
                where ("businessentityid", "addressid", "addresstypeid")
                in (select unnest("""),
             BusinessentityId.pgTypeArray.encode(businessentityid),
             typo.runtime.Fragment.lit("::int4[]), unnest("),
             AddressId.pgTypeArray.encode(addressid),
             typo.runtime.Fragment.lit("::int4[]), unnest("),
             AddresstypeId.pgTypeArray.encode(addresstypeid),
             typo.runtime.Fragment.lit("""
             ::int4[]))

             """)
           ).update().runUnchecked(c);
  };

  public BusinessentityaddressRow insert(
    BusinessentityaddressRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate")
         values ("""),
      BusinessentityId.pgType.encode(unsaved.businessentityid()),
      typo.runtime.Fragment.lit("::int4, "),
      AddressId.pgType.encode(unsaved.addressid()),
      typo.runtime.Fragment.lit("::int4, "),
      AddresstypeId.pgType.encode(unsaved.addresstypeid()),
      typo.runtime.Fragment.lit("::int4, "),
      TypoUUID.pgType.encode(unsaved.rowguid()),
      typo.runtime.Fragment.lit("::uuid, "),
      TypoLocalDateTime.pgType.encode(unsaved.modifieddate()),
      typo.runtime.Fragment.lit("""
         ::timestamp)
         returning "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
      """)
    )
      .updateReturning(BusinessentityaddressRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public BusinessentityaddressRow insert(
    BusinessentityaddressRowUnsaved unsaved,
    Connection c
  ) {
    List<Literal> columns = new ArrayList<>();;
      List<Fragment> values = new ArrayList<>();;
      columns.add(Fragment.lit("\"businessentityid\""));
      values.add(interpolate(
        BusinessentityId.pgType.encode(unsaved.businessentityid()),
        typo.runtime.Fragment.lit("::int4")
      ));
      columns.add(Fragment.lit("\"addressid\""));
      values.add(interpolate(
        AddressId.pgType.encode(unsaved.addressid()),
        typo.runtime.Fragment.lit("::int4")
      ));
      columns.add(Fragment.lit("\"addresstypeid\""));
      values.add(interpolate(
        AddresstypeId.pgType.encode(unsaved.addresstypeid()),
        typo.runtime.Fragment.lit("::int4")
      ));
      unsaved.rowguid().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"rowguid\""));
          values.add(interpolate(
            TypoUUID.pgType.encode(value),
            typo.runtime.Fragment.lit("::uuid")
          ));
        }
      );;
      unsaved.modifieddate().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"modifieddate\""));
          values.add(interpolate(
            TypoLocalDateTime.pgType.encode(value),
            typo.runtime.Fragment.lit("::timestamp")
          ));
        }
      );;
      Fragment q = interpolate(
        typo.runtime.Fragment.lit("""
        insert into "person"."businessentityaddress"(
        """),
        Fragment.comma(columns),
        typo.runtime.Fragment.lit("""
           )
           values ("""),
        Fragment.comma(values),
        typo.runtime.Fragment.lit("""
           )
           returning "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
        """)
      );;
    return q.updateReturning(BusinessentityaddressRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public Long insertStreaming(
    Iterator<BusinessentityaddressRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate") FROM STDIN
    """), batchSize, unsaved, c, BusinessentityaddressRow.pgText);
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<BusinessentityaddressRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')
    """), batchSize, unsaved, c, BusinessentityaddressRowUnsaved.pgText);
  };

  public SelectBuilder<BusinessentityaddressFields, BusinessentityaddressRow> select() {
    return SelectBuilder.of("person.businessentityaddress", BusinessentityaddressFields.structure(), BusinessentityaddressRow._rowParser);
  };

  public List<BusinessentityaddressRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
       from "person"."businessentityaddress"
    """)).as(BusinessentityaddressRow._rowParser.all()).runUnchecked(c);
  };

  public Optional<BusinessentityaddressRow> selectById(
    BusinessentityaddressId compositeId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
         from "person"."businessentityaddress"
         where "businessentityid" = """),
      BusinessentityId.pgType.encode(compositeId.businessentityid()),
      typo.runtime.Fragment.lit("""
       AND "addressid" = 
      """),
      AddressId.pgType.encode(compositeId.addressid()),
      typo.runtime.Fragment.lit("""
       AND "addresstypeid" = 
      """),
      AddresstypeId.pgType.encode(compositeId.addresstypeid()),
      typo.runtime.Fragment.lit("")
    ).as(BusinessentityaddressRow._rowParser.first()).runUnchecked(c);
  };

  public List<BusinessentityaddressRow> selectByIds(
    BusinessentityaddressId[] compositeIds,
    Connection c
  ) {
    BusinessentityId[] businessentityid = arrayMap.map(compositeIds, BusinessentityaddressId::businessentityid, BusinessentityId.class);;
      AddressId[] addressid = arrayMap.map(compositeIds, BusinessentityaddressId::addressid, AddressId.class);;
      AddresstypeId[] addresstypeid = arrayMap.map(compositeIds, BusinessentityaddressId::addresstypeid, AddresstypeId.class);;
    return interpolate(
             typo.runtime.Fragment.lit("""
                select "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
                from "person"."businessentityaddress"
                where ("businessentityid", "addressid", "addresstypeid")
                in (select unnest("""),
             BusinessentityId.pgTypeArray.encode(businessentityid),
             typo.runtime.Fragment.lit("::int4[]), unnest("),
             AddressId.pgTypeArray.encode(addressid),
             typo.runtime.Fragment.lit("::int4[]), unnest("),
             AddresstypeId.pgTypeArray.encode(addresstypeid),
             typo.runtime.Fragment.lit("""
             ::int4[]))

             """)
           ).as(BusinessentityaddressRow._rowParser.all()).runUnchecked(c);
  };

  public Map<BusinessentityaddressId, BusinessentityaddressRow> selectByIdsTracked(
    BusinessentityaddressId[] compositeIds,
    Connection c
  ) {
    Map<BusinessentityaddressId, BusinessentityaddressRow> ret = new HashMap<>();;
      selectByIds(compositeIds, c).forEach(row -> ret.put(row.compositeId(), row));
    return ret;
  };

  public UpdateBuilder<BusinessentityaddressFields, BusinessentityaddressRow> update() {
    return UpdateBuilder.of("person.businessentityaddress", BusinessentityaddressFields.structure(), BusinessentityaddressRow._rowParser.all());
  };

  public Boolean update(
    BusinessentityaddressRow row,
    Connection c
  ) {
    BusinessentityaddressId compositeId = row.compositeId();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "person"."businessentityaddress"
                set "rowguid" = """),
             TypoUUID.pgType.encode(row.rowguid()),
             typo.runtime.Fragment.lit("""
                ::uuid,
                "modifieddate" = """),
             TypoLocalDateTime.pgType.encode(row.modifieddate()),
             typo.runtime.Fragment.lit("""
                ::timestamp
                where "businessentityid" = """),
             BusinessentityId.pgType.encode(compositeId.businessentityid()),
             typo.runtime.Fragment.lit("""
              AND "addressid" = 
             """),
             AddressId.pgType.encode(compositeId.addressid()),
             typo.runtime.Fragment.lit("""
              AND "addresstypeid" = 
             """),
             AddresstypeId.pgType.encode(compositeId.addresstypeid()),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };

  public BusinessentityaddressRow upsert(
    BusinessentityaddressRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate")
         values ("""),
      BusinessentityId.pgType.encode(unsaved.businessentityid()),
      typo.runtime.Fragment.lit("::int4, "),
      AddressId.pgType.encode(unsaved.addressid()),
      typo.runtime.Fragment.lit("::int4, "),
      AddresstypeId.pgType.encode(unsaved.addresstypeid()),
      typo.runtime.Fragment.lit("::int4, "),
      TypoUUID.pgType.encode(unsaved.rowguid()),
      typo.runtime.Fragment.lit("::uuid, "),
      TypoLocalDateTime.pgType.encode(unsaved.modifieddate()),
      typo.runtime.Fragment.lit("""
         ::timestamp)
         on conflict ("businessentityid", "addressid", "addresstypeid")
         do update set
           "rowguid" = EXCLUDED."rowguid",
         "modifieddate" = EXCLUDED."modifieddate"
         returning "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
      """)
    )
      .updateReturning(BusinessentityaddressRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  public List<BusinessentityaddressRow> upsertBatch(
    Iterator<BusinessentityaddressRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate")
                values (?::int4, ?::int4, ?::int4, ?::uuid, ?::timestamp)
                on conflict ("businessentityid", "addressid", "addresstypeid")
                do update set
                  "rowguid" = EXCLUDED."rowguid",
                "modifieddate" = EXCLUDED."modifieddate"
                returning "businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate"::text
             """))
      .updateManyReturning(BusinessentityaddressRow._rowParser, unsaved)
      .runUnchecked(c);
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<BusinessentityaddressRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table businessentityaddress_TEMP (like "person"."businessentityaddress") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy businessentityaddress_TEMP("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate") from stdin
      """), batchSize, unsaved, c, BusinessentityaddressRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "person"."businessentityaddress"("businessentityid", "addressid", "addresstypeid", "rowguid", "modifieddate")
              select * from businessentityaddress_TEMP
              on conflict ("businessentityid", "addressid", "addresstypeid")
              do update set
                "rowguid" = EXCLUDED."rowguid",
              "modifieddate" = EXCLUDED."modifieddate"
              ;
              drop table businessentityaddress_TEMP;""")).update().runUnchecked(c);
  };
}