/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.users

import dev.typr.dslkt.DeleteBuilder
import dev.typr.dslkt.DeleteBuilderMock
import dev.typr.dslkt.DeleteParams
import dev.typr.dslkt.SelectBuilder
import dev.typr.dslkt.SelectBuilderMock
import dev.typr.dslkt.SelectParams
import dev.typr.dslkt.UpdateBuilder
import dev.typr.dslkt.UpdateBuilderMock
import dev.typr.dslkt.UpdateParams
import dev.typr.foundations.data.Unknown
import dev.typr.foundationskt.Connection
import dev.typr.foundationskt.ConnectionRead
import java.lang.RuntimeException
import java.util.ArrayList
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableMap

data class UsersRepoMock(
  val toRow: (UsersRowUnsaved) -> UsersRow,
  val map: MutableMap<UsersId, UsersRow> = mutableMapOf<UsersId, UsersRow>()
) : UsersRepo {
  override fun delete(): DeleteBuilder<UsersFields, UsersRow> = DeleteBuilderMock(UsersFields.structure, { map.values.toList() }, DeleteParams.empty(), { row -> row.userId }, { id -> map.remove(id) })

  override fun deleteById(
    userId: UsersId,
    c: Connection
  ): kotlin.Boolean = map.remove(userId) != null

  override fun deleteByIds(
    userIds: List<UsersId>,
    c: Connection
  ): Int {
    var count = 0
    for (id in userIds) {
      if (map.remove(id) != null) {
      count = count + 1
    }
    }
    return count
  }

  override fun insert(
    unsaved: UsersRow,
    c: Connection
  ): UsersRow {
    if (map.containsKey(unsaved.userId)) {
      throw RuntimeException("id " + unsaved.userId + " already exists")
    }
    map[unsaved.userId] = unsaved
    return unsaved
  }

  override fun insert(
    unsaved: UsersRowUnsaved,
    c: Connection
  ): UsersRow = insert(toRow(unsaved), c)

  override fun insertStreaming(
    unsaved: Iterator<UsersRow>,
    batchSize: Int,
    c: Connection
  ): kotlin.Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.userId] = row
      count = count + 1L
    }
    return count
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override fun insertUnsavedStreaming(
    unsaved: Iterator<UsersRowUnsaved>,
    batchSize: Int,
    c: Connection
  ): kotlin.Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val unsavedRow = unsaved.next()
      val row = toRow(unsavedRow)
      map[row.userId] = row
      count = count + 1L
    }
    return count
  }

  override fun select(): SelectBuilder<UsersFields, UsersRow> = SelectBuilderMock(UsersFields.structure, { map.values.toList() }, SelectParams.empty())

  override fun selectAll(c: ConnectionRead): List<UsersRow> = map.values.toList()

  override fun selectById(
    userId: UsersId,
    c: ConnectionRead
  ): UsersRow? = map[userId]

  override fun selectByIds(
    userIds: List<UsersId>,
    c: ConnectionRead
  ): List<UsersRow> {
    val result = ArrayList<UsersRow>()
    for (id in userIds) {
      val opt = map[id]
      if (opt != null) {
      result.add(opt)
    }
    }
    return result
  }

  override fun selectByIdsTracked(
    userIds: List<UsersId>,
    c: ConnectionRead
  ): Map<UsersId, UsersRow> = selectByIds(userIds, c).associateBy({ row: UsersRow -> row.userId })

  override fun selectByUniqueEmail(
    email: Unknown,
    c: ConnectionRead
  ): UsersRow? = map.values.toList().find({ v -> (email == v.email) })

  override fun update(): UpdateBuilder<UsersFields, UsersRow> = UpdateBuilderMock(UsersFields.structure, { map.values.toList() }, UpdateParams.empty(), { row -> row })

  override fun update(
    row: UsersRow,
    c: Connection
  ): kotlin.Boolean {
    val shouldUpdate = map[row.userId]?.takeIf({ oldRow -> (oldRow != row) }) != null
    if (shouldUpdate) {
      map[row.userId] = row
    }
    return shouldUpdate
  }

  override fun upsert(
    unsaved: UsersRow,
    c: Connection
  ): UsersRow {
    map[unsaved.userId] = unsaved
    return unsaved
  }

  override fun upsertBatch(
    unsaved: Iterator<UsersRow>,
    c: Connection
  ): List<UsersRow> {
    val result = ArrayList<UsersRow>()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.userId] = row
      result.add(row)
    }
    return result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override fun upsertStreaming(
    unsaved: Iterator<UsersRow>,
    batchSize: Int,
    c: Connection
  ): Int {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.userId] = row
      count = count + 1
    }
    return count
  }
}