/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.sr;

import java.sql.Connection;
import java.util.List;
import typo.dsl.Dialect;
import typo.dsl.SelectBuilder;
import static typo.runtime.Fragment.interpolate;

public class SrViewRepoImpl implements SrViewRepo {
  @Override
  public SelectBuilder<SrViewFields, SrViewRow> select() {
    return SelectBuilder.of("\"sa\".\"sr\"", SrViewFields.structure(), SrViewRow._rowParser, Dialect.POSTGRESQL);
  };

  @Override
  public List<SrViewRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "salesreasonid", "name", "reasontype", "modifieddate"::text
       from "sa"."sr"
    """)).query(SrViewRow._rowParser.all()).runUnchecked(c);
  };
}