/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.employee

import adventureworks.person.businessentity.BusinessentityId
import java.lang.RuntimeException
import java.sql.Connection
import java.util.ArrayList
import java.util.Optional
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableIterator
import kotlin.collections.MutableMap
import typo.dsl.DeleteBuilder
import typo.dsl.DeleteBuilder.DeleteBuilderMock
import typo.dsl.DeleteParams
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderMock
import typo.dsl.SelectParams
import typo.dsl.UpdateBuilder
import typo.dsl.UpdateBuilder.UpdateBuilderMock
import typo.dsl.UpdateParams
import typo.runtime.internal.stringInterpolator.str

data class EmployeeRepoMock(
  val toRow: (EmployeeRowUnsaved) -> EmployeeRow,
  val map: MutableMap<BusinessentityId, EmployeeRow> = mutableMapOf<BusinessentityId, EmployeeRow>()
) : EmployeeRepo {
  override fun delete(): DeleteBuilder<EmployeeFields, EmployeeRow> = DeleteBuilderMock(EmployeeFields.structure, { map.values.toList() }, DeleteParams.empty(), { row -> row.businessentityid }, { id -> map.remove(id) })

  override fun deleteById(
    businessentityid: BusinessentityId,
    c: Connection
  ): Boolean = Optional.ofNullable(map.remove(businessentityid)).isPresent()

  override fun deleteByIds(
    businessentityids: Array<BusinessentityId>,
    c: Connection
  ): Int {
    var count = 0
    for (id in businessentityids) {
      if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1
    }
    }
    return count
  }

  override fun insert(
    unsaved: EmployeeRow,
    c: Connection
  ): EmployeeRow {
    if (map.containsKey(unsaved.businessentityid)) {
      throw RuntimeException(str("id $unsaved.businessentityid already exists"))
    }
    map[unsaved.businessentityid] = unsaved
    return unsaved
  }

  override fun insert(
    unsaved: EmployeeRowUnsaved,
    c: Connection
  ): EmployeeRow = insert(toRow(unsaved), c)

  override fun insertStreaming(
    unsaved: MutableIterator<EmployeeRow>,
    batchSize: Int,
    c: Connection
  ): Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.businessentityid] = row
      count = count + 1L
    }
    return count
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override fun insertUnsavedStreaming(
    unsaved: MutableIterator<EmployeeRowUnsaved>,
    batchSize: Int,
    c: Connection
  ): Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val unsavedRow = unsaved.next()
      val row = toRow(unsavedRow)
      map[row.businessentityid] = row
      count = count + 1L
    }
    return count
  }

  override fun select(): SelectBuilder<EmployeeFields, EmployeeRow> = SelectBuilderMock(EmployeeFields.structure, { map.values.toList() }, SelectParams.empty())

  override fun selectAll(c: Connection): List<EmployeeRow> = map.values.toList()

  override fun selectById(
    businessentityid: BusinessentityId,
    c: Connection
  ): Optional<EmployeeRow> = Optional.ofNullable(map[businessentityid])

  override fun selectByIds(
    businessentityids: Array<BusinessentityId>,
    c: Connection
  ): List<EmployeeRow> {
    val result = ArrayList<EmployeeRow>()
    for (id in businessentityids) {
      val opt = Optional.ofNullable(map[id])
      if (opt.isPresent()) {
      result.add(opt.get())
    }
    }
    return result
  }

  override fun selectByIdsTracked(
    businessentityids: Array<BusinessentityId>,
    c: Connection
  ): Map<BusinessentityId, EmployeeRow> = selectByIds(businessentityids, c).associateBy({ row: EmployeeRow -> row.businessentityid })

  override fun update(): UpdateBuilder<EmployeeFields, EmployeeRow> = UpdateBuilderMock(EmployeeFields.structure, { map.values.toList() }, UpdateParams.empty(), { row -> row })

  override fun update(
    row: EmployeeRow,
    c: Connection
  ): Boolean {
    val shouldUpdate = Optional.ofNullable(map[row.businessentityid]).filter({ oldRow -> (oldRow != row) }).isPresent()
    if (shouldUpdate) {
      map[row.businessentityid] = row
    }
    return shouldUpdate
  }

  override fun upsert(
    unsaved: EmployeeRow,
    c: Connection
  ): EmployeeRow {
    map[unsaved.businessentityid] = unsaved
    return unsaved
  }

  override fun upsertBatch(
    unsaved: MutableIterator<EmployeeRow>,
    c: Connection
  ): List<EmployeeRow> {
    val result = ArrayList<EmployeeRow>()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.businessentityid] = row
      result.add(row)
    }
    return result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override fun upsertStreaming(
    unsaved: MutableIterator<EmployeeRow>,
    batchSize: Int,
    c: Connection
  ): Int {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.businessentityid] = row
      count = count + 1
    }
    return count
  }
}