/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.so

import adventureworks.sales.specialoffer.SpecialofferId
import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.UUID
import kotlin.collections.List
import typr.dsl.FieldsExpr
import typr.dsl.Path
import typr.dsl.SqlExpr.FieldLike
import typr.kotlindsl.KotlinDbTypes
import typr.kotlindsl.RelationStructure
import typr.kotlindsl.SqlExpr.Field
import typr.runtime.PgTypes
import typr.runtime.RowParser

interface SoViewFields : FieldsExpr<SoViewRow> {
  abstract fun category(): Field<String, SoViewRow>

  abstract override fun columns(): List<FieldLike<*, SoViewRow>>

  abstract fun description(): Field<String, SoViewRow>

  abstract fun discountpct(): Field<BigDecimal, SoViewRow>

  abstract fun enddate(): Field<LocalDateTime, SoViewRow>

  abstract fun id(): Field<SpecialofferId, SoViewRow>

  abstract fun maxqty(): Field<Int, SoViewRow>

  abstract fun minqty(): Field<Int, SoViewRow>

  abstract fun modifieddate(): Field<LocalDateTime, SoViewRow>

  override fun rowParser(): RowParser<SoViewRow> = SoViewRow._rowParser.underlying

  abstract fun rowguid(): Field<UUID, SoViewRow>

  abstract fun specialofferid(): Field<SpecialofferId, SoViewRow>

  abstract fun startdate(): Field<LocalDateTime, SoViewRow>

  abstract fun type(): Field<String, SoViewRow>

  companion object {
    data class Impl(val _path: List<Path>) : SoViewFields, RelationStructure<SoViewFields, SoViewRow> {
      override fun id(): Field<SpecialofferId, SoViewRow> = Field<SpecialofferId, SoViewRow>(_path, "id", SoViewRow::id, null, null, { row, value -> row.copy(id = value) }, SpecialofferId.pgType)

      override fun specialofferid(): Field<SpecialofferId, SoViewRow> = Field<SpecialofferId, SoViewRow>(_path, "specialofferid", SoViewRow::specialofferid, null, null, { row, value -> row.copy(specialofferid = value) }, SpecialofferId.pgType)

      override fun description(): Field<String, SoViewRow> = Field<String, SoViewRow>(_path, "description", SoViewRow::description, null, null, { row, value -> row.copy(description = value) }, PgTypes.text)

      override fun discountpct(): Field<BigDecimal, SoViewRow> = Field<BigDecimal, SoViewRow>(_path, "discountpct", SoViewRow::discountpct, null, null, { row, value -> row.copy(discountpct = value) }, PgTypes.numeric)

      override fun type(): Field<String, SoViewRow> = Field<String, SoViewRow>(_path, "type", SoViewRow::type, null, null, { row, value -> row.copy(type = value) }, PgTypes.text)

      override fun category(): Field<String, SoViewRow> = Field<String, SoViewRow>(_path, "category", SoViewRow::category, null, null, { row, value -> row.copy(category = value) }, PgTypes.text)

      override fun startdate(): Field<LocalDateTime, SoViewRow> = Field<LocalDateTime, SoViewRow>(_path, "startdate", SoViewRow::startdate, null, null, { row, value -> row.copy(startdate = value) }, PgTypes.timestamp)

      override fun enddate(): Field<LocalDateTime, SoViewRow> = Field<LocalDateTime, SoViewRow>(_path, "enddate", SoViewRow::enddate, null, null, { row, value -> row.copy(enddate = value) }, PgTypes.timestamp)

      override fun minqty(): Field<Int, SoViewRow> = Field<Int, SoViewRow>(_path, "minqty", SoViewRow::minqty, null, null, { row, value -> row.copy(minqty = value) }, KotlinDbTypes.PgTypes.int4)

      override fun maxqty(): Field<Int, SoViewRow> = Field<Int, SoViewRow>(_path, "maxqty", SoViewRow::maxqty, null, null, { row, value -> row.copy(maxqty = value) }, KotlinDbTypes.PgTypes.int4)

      override fun rowguid(): Field<UUID, SoViewRow> = Field<UUID, SoViewRow>(_path, "rowguid", SoViewRow::rowguid, null, null, { row, value -> row.copy(rowguid = value) }, PgTypes.uuid)

      override fun modifieddate(): Field<LocalDateTime, SoViewRow> = Field<LocalDateTime, SoViewRow>(_path, "modifieddate", SoViewRow::modifieddate, null, null, { row, value -> row.copy(modifieddate = value) }, PgTypes.timestamp)

      override fun _path(): List<Path> = _path

      override fun columns(): List<FieldLike<*, SoViewRow>> = listOf(this.id().underlying, this.specialofferid().underlying, this.description().underlying, this.discountpct().underlying, this.type().underlying, this.category().underlying, this.startdate().underlying, this.enddate().underlying, this.minqty().underlying, this.maxqty().underlying, this.rowguid().underlying, this.modifieddate().underlying)

      override fun withPaths(_path: List<Path>): RelationStructure<SoViewFields, SoViewRow> = Impl(_path)
    }

    val structure: Impl = Impl(emptyList<typr.dsl.Path>())
  }
}