-- Get row from all_scalar_types table
-- Tests: all SQL Server scalar types, NULL handling, complex type mapping
SELECT
    id,
    col_tinyint,
    col_smallint,
    col_int,
    col_bigint,
    col_decimal,
    col_numeric,
    col_money,
    col_smallmoney,
    col_real,
    col_float,
    col_bit,
    col_char,
    col_varchar,
    col_varchar_max,
    col_text,
    col_nchar,
    col_nvarchar,
    col_nvarchar_max,
    col_ntext,
    col_binary,
    col_varbinary,
    col_varbinary_max,
    col_image,
    col_date,
    col_time,
    col_datetime,
    col_smalldatetime,
    col_datetime2,
    col_datetimeoffset,
    col_uniqueidentifier,
    col_xml,
    col_json,
    col_hierarchyid,
    col_geography,
    col_geometry,
    col_not_null
FROM all_scalar_types
WHERE id = :id:Int!
