/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.product_prices;

import java.lang.RuntimeException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import typo.dsl.DeleteBuilder;
import typo.dsl.DeleteBuilder.DeleteBuilderMock;
import typo.dsl.DeleteParams;
import typo.dsl.SelectBuilder;
import typo.dsl.SelectBuilderMock;
import typo.dsl.SelectParams;
import typo.dsl.UpdateBuilder;
import typo.dsl.UpdateBuilder.UpdateBuilderMock;
import typo.dsl.UpdateParams;
import static typo.runtime.internal.stringInterpolator.str;

public record ProductPricesRepoMock(
  java.util.function.Function<ProductPricesRowUnsaved, ProductPricesRow> toRow,
  HashMap<ProductPricesId, ProductPricesRow> map
) implements ProductPricesRepo {
  public ProductPricesRepoMock(java.util.function.Function<ProductPricesRowUnsaved, ProductPricesRow> toRow) {
    this(toRow, new HashMap<ProductPricesId, ProductPricesRow>());
  };

  public ProductPricesRepoMock withToRow(java.util.function.Function<ProductPricesRowUnsaved, ProductPricesRow> toRow) {
    return new ProductPricesRepoMock(toRow, map);
  };

  public ProductPricesRepoMock withMap(HashMap<ProductPricesId, ProductPricesRow> map) {
    return new ProductPricesRepoMock(toRow, map);
  };

  @Override
  public DeleteBuilder<ProductPricesFields, ProductPricesRow> delete() {
    return new DeleteBuilderMock<>(ProductPricesFields.structure(), () -> new ArrayList<>(map.values()), DeleteParams.empty(), row -> row.priceId(), id -> map.remove(id));
  };

  @Override
  public Boolean deleteById(
    ProductPricesId priceId,
    Connection c
  ) {
    return Optional.ofNullable(map.remove(priceId)).isPresent();
  };

  @Override
  public Integer deleteByIds(
    ProductPricesId[] priceIds,
    Connection c
  ) {
    var count = 0;
    for (var id : priceIds) {
      if (Optional.ofNullable(map.remove(id)).isPresent()) {
      count = count + 1;;
    };
    };
    return count;
  };

  @Override
  public ProductPricesRow insert(
    ProductPricesRow unsaved,
    Connection c
  ) {
    if (map.containsKey(unsaved.priceId())) {
      throw new RuntimeException(str("id $unsaved.priceId() already exists"));
    };
    map.put(unsaved.priceId(), unsaved);
    return unsaved;
  };

  @Override
  public ProductPricesRow insert(
    ProductPricesRowUnsaved unsaved,
    Connection c
  ) {
    return insert(toRow.apply(unsaved), c);
  };

  @Override
  public SelectBuilder<ProductPricesFields, ProductPricesRow> select() {
    return new SelectBuilderMock<>(ProductPricesFields.structure(), () -> new ArrayList<>(map.values()), SelectParams.empty());
  };

  @Override
  public List<ProductPricesRow> selectAll(Connection c) {
    return new ArrayList<>(map.values());
  };

  @Override
  public Optional<ProductPricesRow> selectById(
    ProductPricesId priceId,
    Connection c
  ) {
    return Optional.ofNullable(map.get(priceId));
  };

  @Override
  public List<ProductPricesRow> selectByIds(
    ProductPricesId[] priceIds,
    Connection c
  ) {
    var result = new ArrayList<ProductPricesRow>();
    for (var id : priceIds) {
      var opt = Optional.ofNullable(map.get(id));
      if (opt.isPresent()) {
      result.add(opt.get());
    };
    };
    return result;
  };

  @Override
  public Map<ProductPricesId, ProductPricesRow> selectByIdsTracked(
    ProductPricesId[] priceIds,
    Connection c
  ) {
    return selectByIds(priceIds, c).stream().collect(Collectors.toMap((ProductPricesRow row) -> row.priceId(), Function.identity()));
  };

  @Override
  public UpdateBuilder<ProductPricesFields, ProductPricesRow> update() {
    return new UpdateBuilderMock<>(ProductPricesFields.structure(), () -> new ArrayList<>(map.values()), UpdateParams.empty(), row -> row);
  };

  @Override
  public Boolean update(
    ProductPricesRow row,
    Connection c
  ) {
    var shouldUpdate = Optional.ofNullable(map.get(row.priceId())).filter(oldRow -> !oldRow.equals(row)).isPresent();
    if (shouldUpdate) {
      map.put(row.priceId(), row);;
    };
    return shouldUpdate;
  };

  @Override
  public ProductPricesRow upsert(
    ProductPricesRow unsaved,
    Connection c
  ) {
    map.put(unsaved.priceId(), unsaved);
    return unsaved;
  };

  @Override
  public List<ProductPricesRow> upsertBatch(
    Iterator<ProductPricesRow> unsaved,
    Connection c
  ) {
    var result = new ArrayList<ProductPricesRow>();
    while (unsaved.hasNext()) {
      var row = unsaved.next();
      map.put(row.priceId(), row);
      result.add(row);
    };
    return result;
  };
}