/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package oracledb.precision_types

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.foundations.OracleType
import dev.typr.foundations.OracleTypes
import dev.typr.foundations.RowParser
import dev.typr.foundations.RowParsers
import dev.typr.foundations.dsl.Bijection

/** Type for the primary key of table `PRECISION_TYPES` */
case class PrecisionTypesId(@JsonValue value: java.math.BigDecimal) extends scala.AnyVal

object PrecisionTypesId {
  given `_rowParser`: RowParser[PrecisionTypesId] = RowParsers.of(OracleTypes.number.bimap(PrecisionTypesId.apply, _.value), x => x, id => Array[Any](id))

  given bijection: Bijection[PrecisionTypesId, java.math.BigDecimal] = Bijection.apply[PrecisionTypesId, java.math.BigDecimal](_.value)(PrecisionTypesId.apply)

  given oracleType: OracleType[PrecisionTypesId] = OracleTypes.number.bimap(PrecisionTypesId.apply, _.value)
}