/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.shoppingcartitem;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.production.product.ProductId;
import typo.runtime.PgText;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;

/** Table: sales.shoppingcartitem
  * Contains online customer orders until the order is submitted or cancelled.
  * Primary key: shoppingcartitemid
  */
public record ShoppingcartitemRow(
  /** Primary key for ShoppingCartItem records.
    * Default: nextval('sales.shoppingcartitem_shoppingcartitemid_seq'::regclass)
    */
  ShoppingcartitemId shoppingcartitemid,
  /** Shopping cart identification number. */
  /* max 50 chars */ String shoppingcartid,
  /** Product quantity ordered.
    * Default: 1
    * Constraint CK_ShoppingCartItem_Quantity affecting columns quantity: ((quantity >= 1))
    */
  Integer quantity,
  /** Product ordered. Foreign key to Product.ProductID.
    * Points to {@link adventureworks.production.product.ProductRow#productid()}
    */
  ProductId productid,
  /** Date the time the record was created.
    * Default: now()
    */
  TypoLocalDateTime datecreated,
  /** Default: now() */
  TypoLocalDateTime modifieddate
) {
  /** Primary key for ShoppingCartItem records.
    * Default: nextval('sales.shoppingcartitem_shoppingcartitemid_seq'::regclass)
    */
  public ShoppingcartitemRow withShoppingcartitemid(ShoppingcartitemId shoppingcartitemid) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  /** Shopping cart identification number. */
  public ShoppingcartitemRow withShoppingcartid(/* max 50 chars */ String shoppingcartid) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  /** Product quantity ordered.
    * Default: 1
    * Constraint CK_ShoppingCartItem_Quantity affecting columns quantity: ((quantity >= 1))
    */
  public ShoppingcartitemRow withQuantity(Integer quantity) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  /** Product ordered. Foreign key to Product.ProductID.
    * Points to {@link adventureworks.production.product.ProductRow#productid()}
    */
  public ShoppingcartitemRow withProductid(ProductId productid) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  /** Date the time the record was created.
    * Default: now()
    */
  public ShoppingcartitemRow withDatecreated(TypoLocalDateTime datecreated) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  /** Default: now() */
  public ShoppingcartitemRow withModifieddate(TypoLocalDateTime modifieddate) {
    return new ShoppingcartitemRow(shoppingcartitemid, shoppingcartid, quantity, productid, datecreated, modifieddate);
  };

  static RowParser<ShoppingcartitemRow> _rowParser = RowParsers.of(ShoppingcartitemId.pgType, PgTypes.text, PgTypes.int4, ProductId.pgType, TypoLocalDateTime.pgType, TypoLocalDateTime.pgType, ShoppingcartitemRow::new, row -> new Object[]{row.shoppingcartitemid(), row.shoppingcartid(), row.quantity(), row.productid(), row.datecreated(), row.modifieddate()});;

  static public PgText<ShoppingcartitemRow> pgText =
    PgText.from(_rowParser);

  public ShoppingcartitemId id() {
    return shoppingcartitemid;
  };

  public ShoppingcartitemRowUnsaved toUnsavedRow(
    Defaulted<ShoppingcartitemId> shoppingcartitemid,
    Defaulted<Integer> quantity,
    Defaulted<TypoLocalDateTime> datecreated,
    Defaulted<TypoLocalDateTime> modifieddate
  ) {
    return new ShoppingcartitemRowUnsaved(shoppingcartid, productid, shoppingcartitemid, quantity, datecreated, modifieddate);
  };
}