/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.brands

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.foundations.MariaType
import dev.typr.foundations.MariaTypes
import dev.typr.foundations.data.Uint2
import dev.typr.foundations.scala.Bijection

/** Type for the primary key of table `brands` */
case class BrandsId(@JsonValue value: Uint2) extends scala.AnyVal

object BrandsId {
  given bijection: Bijection[BrandsId, Uint2] = Bijection.apply[BrandsId, Uint2](_.value)(BrandsId.apply)

  given mariaType: MariaType[BrandsId] = MariaTypes.smallintUnsigned.bimap(BrandsId.apply, _.value)
}