package typr

import typr.jvm.Type.Qualified

object TypesJava {
  // PostgreSQL-specific runtime types
  object runtime {
    val AclItem = Qualified("dev.typr.foundations.data.AclItem")
    val AnyArray = Qualified("dev.typr.foundations.data.AnyArray")
    val Arr = Qualified("dev.typr.foundations.data.Arr")
    val Inet = Qualified("dev.typr.foundations.data.Inet")
    val Int2Vector = Qualified("dev.typr.foundations.data.Int2Vector")
    val Json = Qualified("dev.typr.foundations.data.Json")
    val Jsonb = Qualified("dev.typr.foundations.data.Jsonb")
    val Money = Qualified("dev.typr.foundations.data.Money")
    val OidVector = Qualified("dev.typr.foundations.data.OidVector")
    val OracleIntervalDS = Qualified("dev.typr.foundations.data.OracleIntervalDS")
    val OracleIntervalYM = Qualified("dev.typr.foundations.data.OracleIntervalYM")
    val PgNodeTree = Qualified("dev.typr.foundations.data.PgNodeTree")
    val Record = Qualified("dev.typr.foundations.data.Record")
    val Regclass = Qualified("dev.typr.foundations.data.Regclass")
    val Regconfig = Qualified("dev.typr.foundations.data.Regconfig")
    val Regdictionary = Qualified("dev.typr.foundations.data.Regdictionary")
    val Regnamespace = Qualified("dev.typr.foundations.data.Regnamespace")
    val Regoper = Qualified("dev.typr.foundations.data.Regoper")
    val Regoperator = Qualified("dev.typr.foundations.data.Regoperator")
    val Regproc = Qualified("dev.typr.foundations.data.Regproc")
    val Regprocedure = Qualified("dev.typr.foundations.data.Regprocedure")
    val Regrole = Qualified("dev.typr.foundations.data.Regrole")
    val Regtype = Qualified("dev.typr.foundations.data.Regtype")
    val Vector = Qualified("dev.typr.foundations.data.Vector")
    val Unknown = Qualified("dev.typr.foundations.data.Unknown")
    val Xid = Qualified("dev.typr.foundations.data.Xid")
    val Xml = Qualified("dev.typr.foundations.data.Xml")
  }

  // MariaDB-specific runtime types
  object maria {
    val Inet4 = Qualified("dev.typr.foundations.data.maria.Inet4")
    val Inet6 = Qualified("dev.typr.foundations.data.maria.Inet6")
    val MariaSet = Qualified("dev.typr.foundations.data.maria.MariaSet")
    val Geometry = Qualified("org.mariadb.jdbc.type.Geometry")
    val Point = Qualified("org.mariadb.jdbc.type.Point")
    val LineString = Qualified("org.mariadb.jdbc.type.LineString")
    val Polygon = Qualified("org.mariadb.jdbc.type.Polygon")
    val MultiPoint = Qualified("org.mariadb.jdbc.type.MultiPoint")
    val MultiLineString = Qualified("org.mariadb.jdbc.type.MultiLineString")
    val MultiPolygon = Qualified("org.mariadb.jdbc.type.MultiPolygon")
    val GeometryCollection = Qualified("org.mariadb.jdbc.type.GeometryCollection")
  }
  val Arrays = Qualified("java.util.Arrays")
  val ArrayList = Qualified("java.util.ArrayList")
  val BiFunction = Qualified("java.util.function.BiFunction")
  val BiConsumer = Qualified("java.util.function.BiConsumer")
  val BigDecimal = Qualified("java.math.BigDecimal")
  val BigInteger = Qualified("java.math.BigInteger")
  val Boolean = Qualified("java.lang.Boolean")
  val Byte = Qualified("java.lang.Byte")
  val BytePrimitive = jvm.Type.Primitive("byte") // Java primitive byte
  val FloatPrimitive = jvm.Type.Primitive("float") // Java primitive float
  val ByteArrays = Qualified("dev.typr.foundations.internal.ByteArrays")
  val Character = Qualified("java.lang.Character")
  val ChronoField = jvm.Type.Qualified("java.time.temporal.ChronoField")
  val ChronoUnit = jvm.Type.Qualified("java.time.temporal.ChronoUnit")
  val Collectors = Qualified("java.util.stream.Collectors")
  val Connection = Qualified("java.sql.Connection")
  val Consumer = Qualified("java.util.function.Consumer")
  val DateTimeFormatter = jvm.Type.Qualified("java.time.format.DateTimeFormatter")
  val DateTimeFormatterBuilder = jvm.Type.Qualified("java.time.format.DateTimeFormatterBuilder")
  val DateTimeParseException = Qualified("java.time.format.DateTimeParseException")
  val Double = Qualified("java.lang.Double")
  val Duration = Qualified("java.time.Duration")
  val Float = Qualified("java.lang.Float")
  val Function = Qualified("java.util.function.Function")
  val Instant = Qualified("java.time.Instant")
  val Integer = Qualified("java.lang.Integer")
  val Iterator = Qualified("java.util.Iterator")
  val HashMap = Qualified("java.util.HashMap")
  val List = Qualified("java.util.List")
  val LocalDate = Qualified("java.time.LocalDate")
  val LocalDateTime = Qualified("java.time.LocalDateTime")
  val LocalTime = Qualified("java.time.LocalTime")
  val Long = Qualified("java.lang.Long")
  val Map = Qualified("java.util.Map")
  val OffsetDateTime = Qualified("java.time.OffsetDateTime")
  val OffsetTime = Qualified("java.time.OffsetTime")
  val Optional = Qualified("java.util.Optional")
  val PGInterval = Qualified("org.postgresql.util.PGInterval")
  val PGbox = Qualified("org.postgresql.geometric.PGbox")
  val PGcircle = Qualified("org.postgresql.geometric.PGcircle")
  val PGline = Qualified("org.postgresql.geometric.PGline")
  val PGlseg = Qualified("org.postgresql.geometric.PGlseg")
  val PGmoney = Qualified("org.postgresql.util.PGmoney")
  val PGobject = Qualified("org.postgresql.util.PGobject")
  val PGpath = Qualified("org.postgresql.geometric.PGpath")
  val PGpoint = Qualified("org.postgresql.geometric.PGpoint")
  val PGpolygon = Qualified("org.postgresql.geometric.PGpolygon")
  val PgArray = Qualified("org.postgresql.jdbc.PgArray")
  val PgSQLXML = Qualified("org.postgresql.jdbc.PgSQLXML")
  val PreparedStatement = Qualified("java.sql.PreparedStatement")
  val Random = Qualified("java.util.Random")
  val RandomHelper = Qualified("dev.typr.foundations.internal.RandomHelper")
  val TypoPGObjectHelper = Qualified("dev.typr.foundations.internal.TypoPGObjectHelper")
  val ResultSet = jvm.Type.Qualified("java.sql.ResultSet")
  val Runnable = jvm.Type.Qualified("java.lang.Runnable")
  val RuntimeException = Qualified("java.lang.RuntimeException")
  val Object = Qualified("java.lang.Object")
  val Override = Qualified("java.lang.Override")
  val Short = Qualified("java.lang.Short")
  val SqlTypes = Qualified("java.sql.Types")
  val Stream = Qualified("java.util.stream.Stream")
  val String = Qualified("java.lang.String")
  val StringBuilder = Qualified("scala.collection.mutable.StringBuilder")
  val Supplier = Qualified("java.util.function.Supplier")
  val Throwable = jvm.Type.Qualified("java.lang.Throwable")
  val UUID = Qualified("java.util.UUID")
  val Void = Qualified("java.lang.Void")
  val Year = Qualified("java.time.Year")
  val ZoneOffset = Qualified("java.time.ZoneOffset")
}
