/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.flaff

import dev.typr.foundations.dsl.DeleteBuilder
import dev.typr.foundations.dsl.SelectBuilder
import dev.typr.foundations.dsl.UpdateBuilder
import java.sql.Connection
import java.util.Optional

trait FlaffRepo {
  def delete: DeleteBuilder[FlaffFields, FlaffRow]

  def deleteById(compositeId: FlaffId)(using c: Connection): java.lang.Boolean

  def deleteByIds(compositeIds: Array[FlaffId])(using c: Connection): Integer

  def insert(unsaved: FlaffRow)(using c: Connection): FlaffRow

  def insertStreaming(
    unsaved: java.util.Iterator[FlaffRow],
    batchSize: Integer = 10000
  )(using c: Connection): java.lang.Long

  def select: SelectBuilder[FlaffFields, FlaffRow]

  def selectAll(using c: Connection): java.util.List[FlaffRow]

  def selectById(compositeId: FlaffId)(using c: Connection): Optional[FlaffRow]

  def selectByIds(compositeIds: Array[FlaffId])(using c: Connection): java.util.List[FlaffRow]

  def selectByIdsTracked(compositeIds: Array[FlaffId])(using c: Connection): java.util.Map[FlaffId, FlaffRow]

  def update: UpdateBuilder[FlaffFields, FlaffRow]

  def update(row: FlaffRow)(using c: Connection): java.lang.Boolean

  def upsert(unsaved: FlaffRow)(using c: Connection): FlaffRow

  def upsertBatch(unsaved: java.util.Iterator[FlaffRow])(using c: Connection): java.util.List[FlaffRow]

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: java.util.Iterator[FlaffRow],
    batchSize: Integer = 10000
  )(using c: Connection): Integer
}