/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.unitmeasure

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.dslsc.Bijection
import dev.typr.foundationssc.PgType
import dev.typr.foundationssc.PgTypes

/** Type for the primary key of table `production.unitmeasure` */
case class UnitmeasureId(@JsonValue value: String) extends scala.AnyVal

object UnitmeasureId {
  given bijection: Bijection[UnitmeasureId, String] = Bijection.of[UnitmeasureId, String](_.value, UnitmeasureId.apply)

  given pgType: PgType[UnitmeasureId] = PgTypes.bpchar.to(Bijection.of(UnitmeasureId.apply, _.value))

  given pgTypeArray: PgType[List[UnitmeasureId]] = pgType.array
}