/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customer_addresses

import java.sql.Connection
import java.util.ArrayList
import java.util.Optional
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableIterator
import kotlin.collections.MutableMap
import testdb.customers.CustomersId
import typo.dsl.DeleteBuilder
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.MariaTypes
import typo.runtime.Fragment.interpolate

class CustomerAddressesRepoImpl() : CustomerAddressesRepo {
  override fun delete(): DeleteBuilder<CustomerAddressesFields, CustomerAddressesRow> = DeleteBuilder.of("`customer_addresses`", CustomerAddressesFields.structure, Dialect.MARIADB)

  override fun deleteById(
    addressId: CustomerAddressesId,
    c: Connection
  ): Boolean = interpolate(
    typo.runtime.Fragment.lit("delete from `customer_addresses` where `address_id` = "),
    CustomerAddressesId.pgType.encode(addressId),
    typo.runtime.Fragment.lit("")
  ).update().runUnchecked(c) > 0

  override fun deleteByIds(
    addressIds: Array<CustomerAddressesId>,
    c: Connection
  ): Int {
    val fragments: ArrayList<Fragment> = ArrayList<Fragment>()
    for (id in addressIds) { fragments.add(CustomerAddressesId.pgType.encode(id)) }
    return Fragment.interpolate(Fragment.lit("delete from `customer_addresses` where `address_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).update().runUnchecked(c)
  }

  override fun insert(
    unsaved: CustomerAddressesRow,
    c: Connection
  ): CustomerAddressesRow = interpolate(
    typo.runtime.Fragment.lit("""
      insert into `customer_addresses`(`customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`)
      values (""".trimMargin()),
    CustomersId.pgType.encode(unsaved.customerId),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.addressType),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.bool.encode(unsaved.isDefault),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.recipientName),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.streetLine1),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.streetLine2),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.city),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.stateProvince),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.postalCode),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.countryCode),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.point.opt().encode(unsaved.location),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.deliveryNotes),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.datetime.encode(unsaved.createdAt),
    typo.runtime.Fragment.lit("""
      )
      returning `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`
    """.trimMargin())
  )
    .updateReturning(CustomerAddressesRow._rowParser.exactlyOne()).runUnchecked(c)

  override fun insert(
    unsaved: CustomerAddressesRowUnsaved,
    c: Connection
  ): CustomerAddressesRow {
    val columns: ArrayList<Literal> = ArrayList<Literal>()
    val values: ArrayList<Fragment> = ArrayList<Fragment>()
    columns.add(Fragment.lit("`customer_id`"))
    values.add(interpolate(
      CustomersId.pgType.encode(unsaved.customerId),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`address_type`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.addressType),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`recipient_name`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.recipientName),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`street_line1`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.streetLine1),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`city`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.city),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`postal_code`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.postalCode),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    columns.add(Fragment.lit("`country_code`"))
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.countryCode),
      typo.runtime.Fragment.lit("""
      """.trimMargin())
    ))
    unsaved.isDefault.visit(
      {  },
      { value -> columns.add(Fragment.lit("`is_default`"))
      values.add(interpolate(
        MariaTypes.bool.encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    unsaved.streetLine2.visit(
      {  },
      { value -> columns.add(Fragment.lit("`street_line2`"))
      values.add(interpolate(
        MariaTypes.text.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    unsaved.stateProvince.visit(
      {  },
      { value -> columns.add(Fragment.lit("`state_province`"))
      values.add(interpolate(
        MariaTypes.text.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    unsaved.location.visit(
      {  },
      { value -> columns.add(Fragment.lit("`location`"))
      values.add(interpolate(
        MariaTypes.point.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    unsaved.deliveryNotes.visit(
      {  },
      { value -> columns.add(Fragment.lit("`delivery_notes`"))
      values.add(interpolate(
        MariaTypes.text.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    unsaved.createdAt.visit(
      {  },
      { value -> columns.add(Fragment.lit("`created_at`"))
      values.add(interpolate(
        MariaTypes.datetime.encode(value),
        typo.runtime.Fragment.lit("""
        """.trimMargin())
      )) }
    );
    val q: Fragment = interpolate(
      typo.runtime.Fragment.lit("insert into `customer_addresses`("),
      Fragment.comma(columns),
      typo.runtime.Fragment.lit("""
        )
        values (""".trimMargin()),
      Fragment.comma(values),
      typo.runtime.Fragment.lit("""
        )
        returning `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`
      """.trimMargin())
    )
    return q.updateReturning(CustomerAddressesRow._rowParser.exactlyOne()).runUnchecked(c)
  }

  override fun select(): SelectBuilder<CustomerAddressesFields, CustomerAddressesRow> = SelectBuilder.of("`customer_addresses`", CustomerAddressesFields.structure, CustomerAddressesRow._rowParser, Dialect.MARIADB)

  override fun selectAll(c: Connection): List<CustomerAddressesRow> = interpolate(typo.runtime.Fragment.lit("""
    select `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`
    from `customer_addresses`
  """.trimMargin())).query(CustomerAddressesRow._rowParser.all()).runUnchecked(c)

  override fun selectById(
    addressId: CustomerAddressesId,
    c: Connection
  ): Optional<CustomerAddressesRow> = interpolate(
    typo.runtime.Fragment.lit("""
      select `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`
      from `customer_addresses`
      where `address_id` = """.trimMargin()),
    CustomerAddressesId.pgType.encode(addressId),
    typo.runtime.Fragment.lit("")
  ).query(CustomerAddressesRow._rowParser.first()).runUnchecked(c)

  override fun selectByIds(
    addressIds: Array<CustomerAddressesId>,
    c: Connection
  ): List<CustomerAddressesRow> {
    val fragments: ArrayList<Fragment> = ArrayList<Fragment>()
    for (id in addressIds) { fragments.add(CustomerAddressesId.pgType.encode(id)) }
    return Fragment.interpolate(Fragment.lit("select `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at` from `customer_addresses` where `address_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).query(CustomerAddressesRow._rowParser.all()).runUnchecked(c)
  }

  override fun selectByIdsTracked(
    addressIds: Array<CustomerAddressesId>,
    c: Connection
  ): Map<CustomerAddressesId, CustomerAddressesRow> {
    val ret: MutableMap<CustomerAddressesId, CustomerAddressesRow> = mutableMapOf<CustomerAddressesId, CustomerAddressesRow>()
    selectByIds(addressIds, c).forEach({ row -> ret.put(row.addressId, row) })
    return ret
  }

  override fun update(): UpdateBuilder<CustomerAddressesFields, CustomerAddressesRow> = UpdateBuilder.of("`customer_addresses`", CustomerAddressesFields.structure, CustomerAddressesRow._rowParser.all(), Dialect.MARIADB)

  override fun update(
    row: CustomerAddressesRow,
    c: Connection
  ): Boolean {
    val addressId: CustomerAddressesId = row.addressId
    return interpolate(
      typo.runtime.Fragment.lit("""
        update `customer_addresses`
        set `customer_id` = """.trimMargin()),
      CustomersId.pgType.encode(row.customerId),
      typo.runtime.Fragment.lit("""
        ,
        `address_type` = """.trimMargin()),
      MariaTypes.text.encode(row.addressType),
      typo.runtime.Fragment.lit("""
        ,
        `is_default` = """.trimMargin()),
      MariaTypes.bool.encode(row.isDefault),
      typo.runtime.Fragment.lit("""
        ,
        `recipient_name` = """.trimMargin()),
      MariaTypes.text.encode(row.recipientName),
      typo.runtime.Fragment.lit("""
        ,
        `street_line1` = """.trimMargin()),
      MariaTypes.text.encode(row.streetLine1),
      typo.runtime.Fragment.lit("""
        ,
        `street_line2` = """.trimMargin()),
      MariaTypes.text.opt().encode(row.streetLine2),
      typo.runtime.Fragment.lit("""
        ,
        `city` = """.trimMargin()),
      MariaTypes.text.encode(row.city),
      typo.runtime.Fragment.lit("""
        ,
        `state_province` = """.trimMargin()),
      MariaTypes.text.opt().encode(row.stateProvince),
      typo.runtime.Fragment.lit("""
        ,
        `postal_code` = """.trimMargin()),
      MariaTypes.text.encode(row.postalCode),
      typo.runtime.Fragment.lit("""
        ,
        `country_code` = """.trimMargin()),
      MariaTypes.text.encode(row.countryCode),
      typo.runtime.Fragment.lit("""
        ,
        `location` = """.trimMargin()),
      MariaTypes.point.opt().encode(row.location),
      typo.runtime.Fragment.lit("""
        ,
        `delivery_notes` = """.trimMargin()),
      MariaTypes.text.opt().encode(row.deliveryNotes),
      typo.runtime.Fragment.lit("""
        ,
        `created_at` = """.trimMargin()),
      MariaTypes.datetime.encode(row.createdAt),
      typo.runtime.Fragment.lit("""
  
        where `address_id` = """.trimMargin()),
      CustomerAddressesId.pgType.encode(addressId),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0
  }

  override fun upsert(
    unsaved: CustomerAddressesRow,
    c: Connection
  ): CustomerAddressesRow = interpolate(
    typo.runtime.Fragment.lit("""
      INSERT INTO `customer_addresses`(`customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`)
      VALUES (""".trimMargin()),
    CustomersId.pgType.encode(unsaved.customerId),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.addressType),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.bool.encode(unsaved.isDefault),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.recipientName),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.streetLine1),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.streetLine2),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.city),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.stateProvince),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.postalCode),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.encode(unsaved.countryCode),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.point.opt().encode(unsaved.location),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.text.opt().encode(unsaved.deliveryNotes),
    typo.runtime.Fragment.lit(", "),
    MariaTypes.datetime.encode(unsaved.createdAt),
    typo.runtime.Fragment.lit("""
      )
      ON DUPLICATE KEY UPDATE `customer_id` = VALUES(`customer_id`),
      `address_type` = VALUES(`address_type`),
      `is_default` = VALUES(`is_default`),
      `recipient_name` = VALUES(`recipient_name`),
      `street_line1` = VALUES(`street_line1`),
      `street_line2` = VALUES(`street_line2`),
      `city` = VALUES(`city`),
      `state_province` = VALUES(`state_province`),
      `postal_code` = VALUES(`postal_code`),
      `country_code` = VALUES(`country_code`),
      `location` = VALUES(`location`),
      `delivery_notes` = VALUES(`delivery_notes`),
      `created_at` = VALUES(`created_at`)
      RETURNING `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`""".trimMargin())
  )
    .updateReturning(CustomerAddressesRow._rowParser.exactlyOne())
    .runUnchecked(c)

  override fun upsertBatch(
    unsaved: MutableIterator<CustomerAddressesRow>,
    c: Connection
  ): List<CustomerAddressesRow> = interpolate(typo.runtime.Fragment.lit("""
                                    INSERT INTO `customer_addresses`(`address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`)
                                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                                    ON DUPLICATE KEY UPDATE `customer_id` = VALUES(`customer_id`),
                                    `address_type` = VALUES(`address_type`),
                                    `is_default` = VALUES(`is_default`),
                                    `recipient_name` = VALUES(`recipient_name`),
                                    `street_line1` = VALUES(`street_line1`),
                                    `street_line2` = VALUES(`street_line2`),
                                    `city` = VALUES(`city`),
                                    `state_province` = VALUES(`state_province`),
                                    `postal_code` = VALUES(`postal_code`),
                                    `country_code` = VALUES(`country_code`),
                                    `location` = VALUES(`location`),
                                    `delivery_notes` = VALUES(`delivery_notes`),
                                    `created_at` = VALUES(`created_at`)
                                    RETURNING `address_id`, `customer_id`, `address_type`, `is_default`, `recipient_name`, `street_line1`, `street_line2`, `city`, `state_province`, `postal_code`, `country_code`, `location`, `delivery_notes`, `created_at`""".trimMargin()))
    .updateReturningEach(CustomerAddressesRow._rowParser, unsaved)
    .runUnchecked(c)
}