openapi: 3.0.3
info:
  title: Showcase API
  description: |
    A pedagogical API demonstrating how TypeDefinitions matches fields across:
    - Database columns (e.g., first_name, email, hired_at)
    - API fields (e.g., firstName, email, hiredAt)

    This creates shared semantic wrapper types that ensure type safety
    across heterogeneous systems.

    Key TypeDefinitions matches in this API:
    - firstName, lastName -> Name columns in databases
    - email -> Email columns
    - isActive -> Boolean status columns
    - salary -> Monetary amounts
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: Employees
    description: Employee management
  - name: Customers
    description: Customer management
  - name: Products
    description: Product catalog

paths:
  /employees:
    get:
      tags: [Employees]
      operationId: listEmployees
      summary: List all employees
      parameters:
        - name: isActive
          in: query
          description: Filter by active status
          schema:
            type: boolean
        - name: departmentId
          in: query
          description: Filter by department
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      tags: [Employees]
      operationId: createEmployee
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'

  /employees/{id}:
    get:
      tags: [Employees]
      operationId: getEmployee
      summary: Get employee by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Employee details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Employee not found

  /customers:
    get:
      tags: [Customers]
      operationId: listCustomers
      summary: List all customers
      parameters:
        - name: isActive
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

  /products:
    get:
      tags: [Products]
      operationId: listProducts
      summary: List all products
      parameters:
        - name: isActive
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Employee:
      type: object
      description: |
        Employee record demonstrating TypeDefinitions matching:
        - firstName/lastName match database first_name/last_name columns
        - email matches database email column
        - isActive matches database active/is_active columns
        - salary matches database salary column (decimal amount)
      required:
        - id
        - firstName
        - lastName
        - email
        - salary
        - isActive
        - hiredAt
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          description: First name (matches TypeDefinitions 'FirstName')
          maxLength: 100
        lastName:
          type: string
          description: Last name (matches TypeDefinitions 'LastName')
          maxLength: 100
        email:
          type: string
          format: email
          description: Email address (matches TypeDefinitions 'Email')
        salary:
          type: number
          format: double
          description: Annual salary (matches TypeDefinitions 'Salary')
        isActive:
          type: boolean
          description: Active status (matches TypeDefinitions 'IsActive')
        hiredAt:
          type: string
          format: date-time
          description: Hire date

    EmployeeCreate:
      type: object
      required:
        - firstName
        - lastName
        - email
        - salary
        - departmentId
      properties:
        firstName:
          type: string
          description: First name (matches TypeDefinitions 'FirstName')
          maxLength: 100
        lastName:
          type: string
          description: Last name (matches TypeDefinitions 'LastName')
          maxLength: 100
        email:
          type: string
          format: email
          description: Email address (matches TypeDefinitions 'Email')
        salary:
          type: number
          format: double
          description: Annual salary (matches TypeDefinitions 'Salary')
        departmentId:
          type: integer
          format: int64
          description: Department ID

    Customer:
      type: object
      description: |
        Customer record with fields matching TypeDefinitions
      required:
        - id
        - firstName
        - lastName
        - email
        - isActive
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          description: First name (matches TypeDefinitions 'FirstName')
        lastName:
          type: string
          description: Last name (matches TypeDefinitions 'LastName')
        email:
          type: string
          format: email
          description: Email (matches TypeDefinitions 'Email')
        isActive:
          type: boolean
          description: Active status (matches TypeDefinitions 'IsActive')
        createdAt:
          type: string
          format: date-time

    Product:
      type: object
      required:
        - id
        - name
        - price
        - isActive
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        stockQuantity:
          type: integer
          format: int32
        isActive:
          type: boolean
          description: Whether product is active (matches TypeDefinitions 'IsActive')
