package testdb

import org.junit.Assert._
import org.junit.Test
import testdb.customer_order_summary._
import testdb.customer_stats._
import testdb.distinct_type_test._

import scala.util.Random

/** Tests for DB2-specific features: distinct types, check constraints, identity columns, and materialized views.
  */
class DatabaseFeaturesTest {
  private val testInsert = TestInsert(Random(1794356978))
  private val distinctTypeRepo = DistinctTypeTestRepoImpl()
  private val summaryViewRepo = CustomerOrderSummaryViewRepoImpl()
  private val statsMVRepo = CustomerStatsMVRepoImpl()

  // ==================== Distinct Type Tests ====================

  @Test
  def testEmailAddressDistinctType(): Unit = withConnection {
    val email = EmailAddress("test@example.com")
    val row = testInsert.DistinctTypeTest(email)

    assertNotNull(row)
    assertEquals(email, row.email)
    assertEquals("test@example.com", row.email.value)
  }

  @Test
  def testEmailAddressUpdate(): Unit = withConnection {
    val email = EmailAddress("original@example.com")
    val row = testInsert.DistinctTypeTest(email)

    val newEmail = EmailAddress("updated@example.com")
    val updated = row.copy(email = newEmail)
    val _ = distinctTypeRepo.update(updated)

    val found = distinctTypeRepo.selectById(row.id).get
    assertEquals(newEmail, found.email)
  }

  @Test
  def testEmailAddressDSLQuery(): Unit = withConnection {
    val email1 = EmailAddress("user1@company.com")
    val email2 = EmailAddress("user2@company.com")
    val _ = testInsert.DistinctTypeTest(email1)
    val _ = testInsert.DistinctTypeTest(email2)

    val results = distinctTypeRepo.select
      .where(_.email.isEqual(email1))
      .toList

    assertEquals(1, results.size)
    assertEquals(email1, results.head.email)
  }

  @Test
  def testMoneyAmountDistinctType(): Unit = withConnection {
    val email = EmailAddress("money@test.com")
    val money = MoneyAmount(BigDecimal("999.99"))
    val row = testInsert.DistinctTypeTest(email, balance = Some(money))

    assertTrue(row.balance.isDefined)
    assertEquals(money, row.balance.get)
    assertEquals(0, BigDecimal("999.99").compareTo(row.balance.get.value))
  }

  // ==================== Check Constraint Tests ====================

  @Test
  def testCheckConstraintValidAge(): Unit = withConnection {
    val row = testInsert.CheckConstraintTest(25, "active")

    assertNotNull(row)
    assertEquals(25, row.age.intValue())
    assertEquals("active", row.status)
  }

  @Test
  def testCheckConstraintMinAge(): Unit = withConnection {
    val row = testInsert.CheckConstraintTest(18, "active")
    assertEquals(18, row.age.intValue())
  }

  @Test
  def testCheckConstraintMaxAge(): Unit = withConnection {
    val row = testInsert.CheckConstraintTest(120, "inactive")
    assertEquals(120, row.age.intValue())
  }

  @Test
  def testCheckConstraintStatusValues(): Unit = withConnection {
    val active = testInsert.CheckConstraintTest(30, "active")
    val inactive = testInsert.CheckConstraintTest(30, "inactive")
    val pending = testInsert.CheckConstraintTest(30, "pending")

    assertEquals("active", active.status)
    assertEquals("inactive", inactive.status)
    assertEquals("pending", pending.status)
  }

  // ==================== Identity Column Tests ====================

  @Test
  def testIdentityAlwaysAutoGenerated(): Unit = withConnection {
    val row1 = testInsert.Db2testIdentityAlways()
    val row2 = testInsert.Db2testIdentityAlways()
    val row3 = testInsert.Db2testIdentityAlways()

    assertNotNull(row1.id)
    assertNotNull(row2.id)
    assertNotNull(row3.id)

    assertNotEquals(row1.id, row2.id)
    assertNotEquals(row2.id, row3.id)
  }

  @Test
  def testIdentityDefaultAutoGenerated(): Unit = withConnection {
    val row1 = testInsert.Db2testIdentityDefault()
    val row2 = testInsert.Db2testIdentityDefault()

    assertNotNull(row1.id)
    assertNotNull(row2.id)
    assertNotEquals(row1.id, row2.id)
  }

  @Test
  def testIdentityParamsTest(): Unit = withConnection {
    val row = testInsert.IdentityParamsTest()

    assertNotNull(row)
    assertNotNull(row.id)
  }

  // ==================== Nullability Tests ====================

  @Test
  def testRequiredColumnNotNull(): Unit = withConnection {
    val row = testInsert.NullabilityTest()

    assertNotNull(row.requiredCol)
  }

  @Test
  def testOptionalColumnCanBeNull(): Unit = withConnection {
    val row = testInsert.NullabilityTest(optionalCol = None)

    assertTrue(row.optionalCol.isEmpty)
  }

  @Test
  def testOptionalColumnWithValue(): Unit = withConnection {
    val row = testInsert.NullabilityTest(optionalCol = Some("has value"))

    assertEquals(Some("has value"), row.optionalCol)
  }

  // ==================== View Tests ====================

  @Test
  def testCustomerOrderSummaryView(): Unit = withConnection {
    val customer = testInsert.Customers()
    val _ = testInsert.Orders(customer.customerId, totalAmount = Some(BigDecimal("100.00")))
    val _ = testInsert.Orders(customer.customerId, totalAmount = Some(BigDecimal("200.00")))

    val viewResults = summaryViewRepo.select.toList

    assertTrue(viewResults.nonEmpty)
  }

  @Test
  def testCustomerStatsMaterializedView(): Unit = withConnection {
    val results = statsMVRepo.select.toList

    assertNotNull(results)
  }
}
