/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.flaff

import adventureworks.public.ShortText
import doobie.util.Read
import doobie.util.meta.Meta
import io.circe.Decoder
import io.circe.Encoder

/** Type for the composite primary key of table `public.flaff` */
case class FlaffId(
  code: ShortText,
  anotherCode: String,
  someNumber: Int,
  specifier: ShortText
)

object FlaffId {
  implicit lazy val decoder: Decoder[FlaffId] = Decoder.forProduct4[FlaffId, ShortText, String, Int, ShortText]("code", "another_code", "some_number", "specifier")(FlaffId.apply)(ShortText.decoder, Decoder.decodeString, Decoder.decodeInt, ShortText.decoder)

  implicit lazy val encoder: Encoder[FlaffId] = Encoder.forProduct4[FlaffId, ShortText, String, Int, ShortText]("code", "another_code", "some_number", "specifier")(x => (x.code, x.anotherCode, x.someNumber, x.specifier))(ShortText.encoder, Encoder.encodeString, Encoder.encodeInt, ShortText.encoder)

  implicit lazy val read: Read[FlaffId] = {
    new Read.CompositeOfInstances(Array(
      new Read.Single(ShortText.get).asInstanceOf[Read[Any]],
        new Read.Single(Meta.StringMeta.get).asInstanceOf[Read[Any]],
        new Read.Single(Meta.IntMeta.get).asInstanceOf[Read[Any]],
        new Read.Single(ShortText.get).asInstanceOf[Read[Any]]
    ))(scala.reflect.ClassTag.Any).map { arr =>
      FlaffId(
        code = arr(0).asInstanceOf[ShortText],
            anotherCode = arr(1).asInstanceOf[String],
            someNumber = arr(2).asInstanceOf[Int],
            specifier = arr(3).asInstanceOf[ShortText]
      )
    }
  }
}