/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.l;

import java.sql.Connection;
import java.util.List;
import typo.dsl.Dialect;
import typo.dsl.SelectBuilder;
import static typo.runtime.Fragment.interpolate;

public class LViewRepoImpl implements LViewRepo {
  @Override
  public SelectBuilder<LViewFields, LViewRow> select() {
    return SelectBuilder.of("\"pr\".\"l\"", LViewFields.structure(), LViewRow._rowParser, Dialect.POSTGRESQL);
  };

  @Override
  public List<LViewRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "id", "locationid", "name", "costrate", "availability", "modifieddate"::text
       from "pr"."l"
    """)).query(LViewRow._rowParser.all()).runUnchecked(c);
  };
}