/**
 * File automatically generated by `typo` for its own test suite.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN
 */
package testdb.hardcoded.compositepk.person;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import typo.dsl.DeleteBuilder;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.PgTypes;
import typo.runtime.streamingInsert;
import static typo.runtime.Fragment.interpolate;
import static typo.runtime.internal.stringInterpolator.str;

public class PersonRepoImpl implements PersonRepo {
  public DeleteBuilder<PersonFields, PersonRow> delete() {
    return DeleteBuilder.of("compositepk.person", PersonFields.structure());
  };

  public Boolean deleteById(
    PersonId compositeId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
      delete from "compositepk"."person" where "one" = 
      """),
      PgTypes.int8.encode(compositeId.one()),
      typo.runtime.Fragment.lit("""
       AND "two" = 
      """),
      PgTypes.text.opt().encode(compositeId.two()),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  public PersonRow insert(
    PersonRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "compositepk"."person"("one", "two", "name")
         values ("""),
      PgTypes.int8.encode(unsaved.one()),
      typo.runtime.Fragment.lit("::int8, "),
      PgTypes.text.opt().encode(unsaved.two()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.text.opt().encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         returning "one", "two", "name"
      """)
    )
      .updateReturning(PersonRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public PersonRow insert(
    PersonRowUnsaved unsaved,
    Connection c
  ) {
    List<Literal> columns = new ArrayList<>();;
      List<Fragment> values = new ArrayList<>();;
      columns.add(Fragment.lit("\"name\""));
      values.add(interpolate(
        PgTypes.text.opt().encode(unsaved.name()),
        typo.runtime.Fragment.lit("""
        """)
      ));
      unsaved.one().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"one\""));
          values.add(interpolate(
            PgTypes.int8.encode(value),
            typo.runtime.Fragment.lit("::int8")
          ));
        }
      );;
      unsaved.two().visit(
        () -> {},
        value -> {
          columns.add(Fragment.lit("\"two\""));
          values.add(interpolate(
            PgTypes.text.opt().encode(value),
            typo.runtime.Fragment.lit("""
            """)
          ));
        }
      );;
      Fragment q = interpolate(
        typo.runtime.Fragment.lit("""
        insert into "compositepk"."person"(
        """),
        Fragment.comma(columns),
        typo.runtime.Fragment.lit("""
           )
           values ("""),
        Fragment.comma(values),
        typo.runtime.Fragment.lit("""
           )
           returning "one", "two", "name"
        """)
      );;
    return q.updateReturning(PersonRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  public Long insertStreaming(
    Iterator<PersonRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "compositepk"."person"("one", "two", "name") FROM STDIN
    """), batchSize, unsaved, c, PersonRow.pgText);
  };

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  public Long insertUnsavedStreaming(
    Iterator<PersonRowUnsaved> unsaved,
    Integer batchSize,
    Connection c
  ) {
    return streamingInsert.insertUnchecked(str("""
    COPY "compositepk"."person"("name", "one", "two") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')
    """), batchSize, unsaved, c, PersonRowUnsaved.pgText);
  };

  public SelectBuilder<PersonFields, PersonRow> select() {
    return SelectBuilder.of("compositepk.person", PersonFields.structure(), PersonRow._rowParser);
  };

  public List<PersonRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select "one", "two", "name"
       from "compositepk"."person"
    """)).as(PersonRow._rowParser.all()).runUnchecked(c);
  };

  public Optional<PersonRow> selectById(
    PersonId compositeId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select "one", "two", "name"
         from "compositepk"."person"
         where "one" = """),
      PgTypes.int8.encode(compositeId.one()),
      typo.runtime.Fragment.lit("""
       AND "two" = 
      """),
      PgTypes.text.opt().encode(compositeId.two()),
      typo.runtime.Fragment.lit("")
    ).as(PersonRow._rowParser.first()).runUnchecked(c);
  };

  public UpdateBuilder<PersonFields, PersonRow> update() {
    return UpdateBuilder.of("compositepk.person", PersonFields.structure(), PersonRow._rowParser.all());
  };

  public Boolean update(
    PersonRow row,
    Connection c
  ) {
    PersonId compositeId = row.compositeId();;
    return interpolate(
             typo.runtime.Fragment.lit("""
                update "compositepk"."person"
                set "name" = """),
             PgTypes.text.opt().encode(row.name()),
             typo.runtime.Fragment.lit("""
   
                where "one" = """),
             PgTypes.int8.encode(compositeId.one()),
             typo.runtime.Fragment.lit("""
              AND "two" = 
             """),
             PgTypes.text.opt().encode(compositeId.two()),
             typo.runtime.Fragment.lit("")
           ).update().runUnchecked(c) > 0;
  };

  public PersonRow upsert(
    PersonRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into "compositepk"."person"("one", "two", "name")
         values ("""),
      PgTypes.int8.encode(unsaved.one()),
      typo.runtime.Fragment.lit("::int8, "),
      PgTypes.text.opt().encode(unsaved.two()),
      typo.runtime.Fragment.lit(", "),
      PgTypes.text.opt().encode(unsaved.name()),
      typo.runtime.Fragment.lit("""
         )
         on conflict ("one", "two")
         do update set
           "name" = EXCLUDED."name"
         returning "one", "two", "name"
      """)
    )
      .updateReturning(PersonRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  public List<PersonRow> upsertBatch(
    Iterator<PersonRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                insert into "compositepk"."person"("one", "two", "name")
                values (?::int8, ?, ?)
                on conflict ("one", "two")
                do update set
                  "name" = EXCLUDED."name"
                returning "one", "two", "name"
             """))
      .updateManyReturning(PersonRow._rowParser, unsaved)
      .runUnchecked(c);
  };

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  public Integer upsertStreaming(
    Iterator<PersonRow> unsaved,
    Integer batchSize,
    Connection c
  ) {
    interpolate(typo.runtime.Fragment.lit("""
      create temporary table person_TEMP (like "compositepk"."person") on commit drop
      """)).update().runUnchecked(c);
      streamingInsert.insertUnchecked(str("""
      copy person_TEMP("one", "two", "name") from stdin
      """), batchSize, unsaved, c, PersonRow.pgText);
    return interpolate(typo.runtime.Fragment.lit("""
              insert into "compositepk"."person"("one", "two", "name")
              select * from person_TEMP
              on conflict ("one", "two")
              do update set
                "name" = EXCLUDED."name"
              ;
              drop table person_TEMP;""")).update().runUnchecked(c);
  };
}