/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.orders

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime
import java.util.Optional
import testdb.customer_addresses.CustomerAddressesId
import testdb.customers.CustomersId
import testdb.customtypes.Defaulted
import testdb.promotions.PromotionsId
import typo.data.maria.Inet6
import typo.runtime.MariaText
import typo.runtime.MariaTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers

/** Table: orders
 * Primary key: order_id
 */
case class OrdersRow(
  /** 
   * AUTO_INCREMENT
   */
  @JsonProperty("order_id") orderId: OrdersId,
  /**  */
  @JsonProperty("order_number") orderNumber: String,
  /** 
   * Points to [[testdb.customers.CustomersRow.customerId]]
   */
  @JsonProperty("customer_id") customerId: CustomersId,
  /** 
   * Default: 'pending'
   */
  @JsonProperty("order_status") orderStatus: String,
  /** 
   * Default: 'pending'
   */
  @JsonProperty("payment_status") paymentStatus: String,
  /** 
   * Default: NULL
   * Points to [[testdb.customer_addresses.CustomerAddressesRow.addressId]]
   */
  @JsonProperty("shipping_address_id") shippingAddressId: Optional[CustomerAddressesId],
  /** 
   * Default: NULL
   * Points to [[testdb.customer_addresses.CustomerAddressesRow.addressId]]
   */
  @JsonProperty("billing_address_id") billingAddressId: Optional[CustomerAddressesId],
  /**  */
  subtotal: java.math.BigDecimal,
  /** 
   * Default: 0.0000
   */
  @JsonProperty("shipping_cost") shippingCost: java.math.BigDecimal,
  /** 
   * Default: 0.0000
   */
  @JsonProperty("tax_amount") taxAmount: java.math.BigDecimal,
  /** 
   * Default: 0.0000
   */
  @JsonProperty("discount_amount") discountAmount: java.math.BigDecimal,
  /**  */
  @JsonProperty("total_amount") totalAmount: java.math.BigDecimal,
  /** 
   * Default: 'USD'
   */
  @JsonProperty("currency_code") currencyCode: String,
  /** 
   * Default: NULL
   * Points to [[testdb.promotions.PromotionsRow.promotionId]]
   */
  @JsonProperty("promotion_id") promotionId: Optional[PromotionsId],
  /** 
   * Default: NULL
   */
  notes: Optional[String],
  /** 
   * Default: NULL
   */
  @JsonProperty("internal_notes") internalNotes: Optional[String],
  /** 
   * Default: NULL
   */
  @JsonProperty("ip_address") ipAddress: Optional[Inet6],
  /** 
   * Default: NULL
   */
  @JsonProperty("user_agent") userAgent: Optional[String],
  /** 
   * Default: current_timestamp(6)
   */
  @JsonProperty("ordered_at") orderedAt: LocalDateTime,
  /** 
   * Default: NULL
   */
  @JsonProperty("confirmed_at") confirmedAt: Optional[LocalDateTime],
  /** 
   * Default: NULL
   */
  @JsonProperty("shipped_at") shippedAt: Optional[LocalDateTime],
  /** 
   * Default: NULL
   */
  @JsonProperty("delivered_at") deliveredAt: Optional[LocalDateTime]
) {
  def id: OrdersId = orderId

  def toUnsavedRow(
    orderStatus: Defaulted[String] = Defaulted.Provided(this.orderStatus),
    paymentStatus: Defaulted[String] = Defaulted.Provided(this.paymentStatus),
    shippingAddressId: Defaulted[Optional[CustomerAddressesId]] = Defaulted.Provided(this.shippingAddressId),
    billingAddressId: Defaulted[Optional[CustomerAddressesId]] = Defaulted.Provided(this.billingAddressId),
    shippingCost: Defaulted[java.math.BigDecimal] = Defaulted.Provided(this.shippingCost),
    taxAmount: Defaulted[java.math.BigDecimal] = Defaulted.Provided(this.taxAmount),
    discountAmount: Defaulted[java.math.BigDecimal] = Defaulted.Provided(this.discountAmount),
    currencyCode: Defaulted[String] = Defaulted.Provided(this.currencyCode),
    promotionId: Defaulted[Optional[PromotionsId]] = Defaulted.Provided(this.promotionId),
    notes: Defaulted[Optional[String]] = Defaulted.Provided(this.notes),
    internalNotes: Defaulted[Optional[String]] = Defaulted.Provided(this.internalNotes),
    ipAddress: Defaulted[Optional[Inet6]] = Defaulted.Provided(this.ipAddress),
    userAgent: Defaulted[Optional[String]] = Defaulted.Provided(this.userAgent),
    orderedAt: Defaulted[LocalDateTime] = Defaulted.Provided(this.orderedAt),
    confirmedAt: Defaulted[Optional[LocalDateTime]] = Defaulted.Provided(this.confirmedAt),
    shippedAt: Defaulted[Optional[LocalDateTime]] = Defaulted.Provided(this.shippedAt),
    deliveredAt: Defaulted[Optional[LocalDateTime]] = Defaulted.Provided(this.deliveredAt)
  ): OrdersRowUnsaved = {
    new OrdersRowUnsaved(
      orderNumber,
      customerId,
      subtotal,
      totalAmount,
      orderStatus,
      paymentStatus,
      shippingAddressId,
      billingAddressId,
      shippingCost,
      taxAmount,
      discountAmount,
      currencyCode,
      promotionId,
      notes,
      internalNotes,
      ipAddress,
      userAgent,
      orderedAt,
      confirmedAt,
      shippedAt,
      deliveredAt
    )
  }
}

object OrdersRow {
  val `_rowParser`: RowParser[OrdersRow] = RowParsers.of(OrdersId.pgType, MariaTypes.varchar, CustomersId.pgType, MariaTypes.text, MariaTypes.text, CustomerAddressesId.pgType.opt(), CustomerAddressesId.pgType.opt(), MariaTypes.decimal, MariaTypes.decimal, MariaTypes.decimal, MariaTypes.decimal, MariaTypes.decimal, MariaTypes.char_, PromotionsId.pgType.opt(), MariaTypes.text.opt(), MariaTypes.mediumtext.opt(), MariaTypes.inet6.opt(), MariaTypes.varchar.opt(), MariaTypes.datetime, MariaTypes.datetime.opt(), MariaTypes.datetime.opt(), MariaTypes.datetime.opt(), OrdersRow.apply, row => Array(row.orderId, row.orderNumber, row.customerId, row.orderStatus, row.paymentStatus, row.shippingAddressId, row.billingAddressId, row.subtotal, row.shippingCost, row.taxAmount, row.discountAmount, row.totalAmount, row.currencyCode, row.promotionId, row.notes, row.internalNotes, row.ipAddress, row.userAgent, row.orderedAt, row.confirmedAt, row.shippedAt, row.deliveredAt))

  given mariaText: MariaText[OrdersRow] = MariaText.from(`_rowParser`)
}