package adventureworks

import adventureworks.DbNow
import adventureworks.customtypes.*
import adventureworks.public.Mydomain
import adventureworks.public.Myenum
import adventureworks.public.pgtest.PgtestRow
import adventureworks.public.pgtestnull.PgtestnullRow
import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetTime
import java.util.UUID
import org.postgresql.geometric.PGbox
import org.postgresql.geometric.PGcircle
import org.postgresql.geometric.PGline
import org.postgresql.geometric.PGlseg
import org.postgresql.geometric.PGpath
import org.postgresql.geometric.PGpoint
import org.postgresql.geometric.PGpolygon
import org.postgresql.util.PGInterval
import typo.data.Inet
import typo.data.Int2Vector
import typo.data.Json
import typo.data.Jsonb
import typo.data.Money
import typo.data.Vector
import typo.data.Xml

object ArrayTestData {
    val pgTestRow = PgtestRow(
        bool = true,
        box = PGbox(3.0, 4.0, 1.0, 2.0),
        bpchar = "abc",
        bytea = byteArrayOf(1, 2, 3),
        char = "a",
        circle = PGcircle(PGpoint(1.0, 2.0), 3.0),
        date = LocalDate.now(),
        float4 = 1.0f,
        float8 = 2.45,
        hstore = mapOf("a" to "1", "b" to "2"),
        inet = Inet("::10.2.3.4"),
        int2 = 1.toShort(),
        int2vector = Int2Vector("1 2 3"),
        int4 = 4,
        int8 = Int.MAX_VALUE.toLong() + 1,
        interval = PGInterval(1, 2, 3, 4, 5, 6.5),
        json = Json("""{"a": 1}"""),
        jsonb = Jsonb("""{"a": 2}"""),
        line = PGline(3.0, 4.5, 5.5),
        lseg = PGlseg(PGpoint(6.5, 4.3), PGpoint(1.5, 2.3)),
        money = Money("22.50"),
        mydomain = Mydomain("a"),
        myenum = Myenum.c,
        name = "foo",
        numeric = BigDecimal("3.14159"),
        path = PGpath(arrayOf(PGpoint(6.5, 4.3), PGpoint(8.5, 4.3)), true),
        point = PGpoint(6.5, 4.3),
        polygon = PGpolygon(arrayOf(PGpoint(6.5, 4.3), PGpoint(10.5, 4.3), PGpoint(-6.5, 4.3))),
        text = "flaff",
        time = DbNow.localDateTime().toLocalTime(),
        timestamp = DbNow.localDateTime(),
        timestampz = DbNow.instant(),
        timez = DbNow.offsetDateTime().toOffsetTime(),
        uuid = UUID.randomUUID(),
        varchar = "asd asd ",
        vector = Vector(floatArrayOf(1.0f, 2.2f, 3.3f)),
        xml = Xml("<xml/>"),
        boxes = arrayOf(PGbox(3.0, 4.0, 1.0, 2.0)),
        bpchares = arrayOf("abc"),
        chares = arrayOf("a"),
        circlees = arrayOf(PGcircle(PGpoint(1.0, 2.0), 3.0)),
        datees = arrayOf(LocalDate.now()),
        float4es = arrayOf(1.0f),
        float8es = arrayOf(2.45),
        inetes = arrayOf(Inet("::10.2.3.4")),
        int2es = arrayOf(1.toShort()),
        int2vectores = arrayOf(Int2Vector("1 2 3")),
        int4es = arrayOf(4),
        int8es = arrayOf(Int.MAX_VALUE.toLong() + 1),
        intervales = arrayOf(PGInterval(1, 2, 3, 4, 5, 6.5)),
        jsones = arrayOf(Json("""{"a": 1}""")),
        jsonbes = arrayOf(Jsonb("""{"a": 2}""")),
        linees = arrayOf(PGline(3.0, 4.5, 5.5)),
        lseges = arrayOf(PGlseg(PGpoint(6.5, 4.3), PGpoint(1.5, 2.3))),
        moneyes = arrayOf(Money("22.50")),
        myenumes = arrayOf(Myenum.c),
        mydomaines = arrayOf(Mydomain("a")),
        namees = arrayOf("foo"),
        numerices = arrayOf(BigDecimal("3.14159")),
        pathes = arrayOf(PGpath(arrayOf(PGpoint(6.5, 4.3), PGpoint(8.5, 4.3)), true)),
        pointes = arrayOf(PGpoint(6.5, 4.3)),
        polygones = arrayOf(PGpolygon(arrayOf(PGpoint(6.5, 4.3), PGpoint(10.5, 4.3), PGpoint(-6.5, 4.3)))),
        textes = arrayOf("flaff"),
        timees = arrayOf(DbNow.localDateTime().toLocalTime()),
        timestampes = arrayOf(DbNow.localDateTime()),
        timestampzes = arrayOf(DbNow.instant()),
        timezes = arrayOf(DbNow.offsetDateTime().toOffsetTime()),
        uuides = arrayOf(UUID.randomUUID()),
        varchares = arrayOf("asd asd "),
        xmles = arrayOf(Xml("<xml/>"))
    )

    val pgtestnullRow = PgtestnullRow(
        bool = null,
        box = null,
        bpchar = null,
        bytea = null,
        char = null,
        circle = null,
        date = null,
        float4 = null,
        float8 = null,
        hstore = null,
        inet = null,
        int2 = null,
        int2vector = null,
        int4 = null,
        int8 = null,
        interval = null,
        json = null,
        jsonb = null,
        line = null,
        lseg = null,
        money = null,
        mydomain = null,
        myenum = null,
        name = null,
        numeric = null,
        path = null,
        point = null,
        polygon = null,
        text = null,
        time = null,
        timestamp = null,
        timestampz = null,
        timez = null,
        uuid = null,
        varchar = null,
        vector = null,
        xml = null,
        boxes = null,
        bpchares = null,
        chares = null,
        circlees = null,
        datees = null,
        float4es = null,
        float8es = null,
        inetes = null,
        int2es = null,
        int2vectores = null,
        int4es = null,
        int8es = null,
        intervales = null,
        jsones = null,
        jsonbes = null,
        linees = null,
        lseges = null,
        moneyes = null,
        mydomaines = null,
        myenumes = null,
        namees = null,
        numerices = null,
        pathes = null,
        pointes = null,
        polygones = null,
        textes = null,
        timees = null,
        timestampes = null,
        timestampzes = null,
        timezes = null,
        uuides = null,
        varchares = null,
        xmles = null
    )

    val pgtestnullRowWithValues = PgtestnullRow(
        bool = true,
        box = PGbox(3.0, 4.0, 1.0, 2.0),
        bpchar = "abc",
        bytea = byteArrayOf(1, 2, 3),
        char = "a",
        circle = PGcircle(PGpoint(1.0, 2.0), 3.0),
        date = LocalDate.now(),
        float4 = 1.0f,
        float8 = 2.45,
        hstore = mapOf("a" to "1", "b" to "2"),
        inet = Inet("::10.2.3.4"),
        int2 = 1.toShort(),
        int2vector = Int2Vector("1 2 3"),
        int4 = 4,
        int8 = Int.MAX_VALUE.toLong() + 1,
        interval = PGInterval(1, 2, 3, 4, 5, 6.5),
        json = Json("""{"a": 1}"""),
        jsonb = Jsonb("""{"a": 2}"""),
        line = PGline(3.0, 4.5, 5.5),
        lseg = PGlseg(PGpoint(6.5, 4.3), PGpoint(1.5, 2.3)),
        money = Money("22.50"),
        mydomain = Mydomain("a"),
        myenum = Myenum.c,
        name = "foo",
        numeric = BigDecimal("3.14159"),
        path = PGpath(arrayOf(PGpoint(6.5, 4.3), PGpoint(8.5, 4.3)), true),
        point = PGpoint(6.5, 4.3),
        polygon = PGpolygon(arrayOf(PGpoint(6.5, 4.3), PGpoint(10.5, 4.3), PGpoint(-6.5, 4.3))),
        text = "flaff",
        time = DbNow.localDateTime().toLocalTime(),
        timestamp = DbNow.localDateTime(),
        timestampz = DbNow.instant(),
        timez = DbNow.offsetDateTime().toOffsetTime(),
        uuid = UUID.randomUUID(),
        varchar = "asd asd ",
        vector = Vector(floatArrayOf(1.0f, 2.2f, 3.3f)),
        xml = Xml("<xml/>"),
        boxes = arrayOf(PGbox(3.0, 4.0, 1.0, 2.0)),
        bpchares = arrayOf("abc"),
        chares = arrayOf("a"),
        circlees = arrayOf(PGcircle(PGpoint(1.0, 2.0), 3.0)),
        datees = arrayOf(LocalDate.now()),
        float4es = arrayOf(1.0f),
        float8es = arrayOf(2.45),
        inetes = arrayOf(Inet("::10.2.3.4")),
        int2es = arrayOf(1.toShort()),
        int2vectores = arrayOf(Int2Vector("1 2 3")),
        int4es = arrayOf(4),
        int8es = arrayOf(Int.MAX_VALUE.toLong() + 1),
        intervales = arrayOf(PGInterval(1, 2, 3, 4, 5, 6.5)),
        jsones = arrayOf(Json("""{"a": 1}""")),
        jsonbes = arrayOf(Jsonb("""{"a": 2}""")),
        linees = arrayOf(PGline(3.0, 4.5, 5.5)),
        lseges = arrayOf(PGlseg(PGpoint(6.5, 4.3), PGpoint(1.5, 2.3))),
        moneyes = arrayOf(Money("22.50")),
        mydomaines = arrayOf(Mydomain("a")),
        myenumes = arrayOf(Myenum.c),
        namees = arrayOf("foo"),
        numerices = arrayOf(BigDecimal("3.14159")),
        pathes = arrayOf(PGpath(arrayOf(PGpoint(6.5, 4.3), PGpoint(8.5, 4.3)), true)),
        pointes = arrayOf(PGpoint(6.5, 4.3)),
        polygones = arrayOf(PGpolygon(arrayOf(PGpoint(6.5, 4.3), PGpoint(10.5, 4.3), PGpoint(-6.5, 4.3)))),
        textes = arrayOf("flaff"),
        timees = arrayOf(DbNow.localDateTime().toLocalTime()),
        timestampes = arrayOf(DbNow.localDateTime()),
        timestampzes = arrayOf(DbNow.instant()),
        timezes = arrayOf(DbNow.offsetDateTime().toOffsetTime()),
        uuides = arrayOf(UUID.randomUUID()),
        varchares = arrayOf("asd asd "),
        xmles = arrayOf(Xml("<xml/>"))
    )
}
