/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.find_customers_by_email

import java.sql.Connection

trait FindCustomersByEmailSqlRepo {
  def apply(emailPattern: String)(using c: Connection): List[FindCustomersByEmailSqlRow]
}