/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.title

import dev.typr.foundationskt.Bijection
import dev.typr.foundationskt.PgType
import dev.typr.foundationskt.PgTypes
import kotlin.collections.List

sealed interface TitleId {
    val value: kotlin.String

    data class Unknown(override val value: kotlin.String) : TitleId

    enum class Known(override val value: kotlin.String) : TitleId {
        dr("dr"),
        mr("mr"),
        ms("ms"),
        phd("phd");

        companion object {
            val ByName: kotlin.collections.Map<kotlin.String, Known> = entries.associateBy { it.value }
        }
    }

    companion object {
        fun apply(str: kotlin.String): TitleId =
            Known.ByName[str] ?: Unknown(str)
        val pgTypeArray: PgType<List<TitleId>> =
          PgTypes.text.array()
            .to(Bijection.of({ xs -> xs.map(TitleId::apply) }, { xs -> xs.map(TitleId::value) }))
        val pgType: PgType<TitleId> =
          PgTypes.text.to(Bijection.of(TitleId::apply, TitleId::value))
    }
}