/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.stateprovince

import com.fasterxml.jackson.annotation.JsonValue
import dev.typr.foundations.PgType
import dev.typr.foundations.PgTypes
import dev.typr.foundations.internal.arrayMap
import dev.typr.foundations.kotlin.Bijection
import dev.typr.foundations.kotlin.KotlinDbTypes

/** Type for the primary key of table `person.stateprovince` */
data class StateprovinceId(@field:JsonValue val value: Int) {
  override fun toString(): kotlin.String {
    return value.toString()
  }

  companion object {
    val bijection: Bijection<StateprovinceId, Int> =
      Bijection.of(StateprovinceId::value, ::StateprovinceId)

    val dbType: PgType<StateprovinceId> =
      KotlinDbTypes.PgTypes.int4.bimap(::StateprovinceId, StateprovinceId::value)

    val dbTypeArray: PgType<Array<StateprovinceId>> =
      PgTypes.int4Array.bimap({ xs -> arrayMap.map(xs, ::StateprovinceId, StateprovinceId::class.java) }, { xs -> arrayMap.map(xs, StateprovinceId::value, Int::class.javaObjectType) })
  }
}