/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.stateprovince

import adventureworks.person.countryregion.CountryregionFields
import adventureworks.person.countryregion.CountryregionId
import adventureworks.person.countryregion.CountryregionRow
import adventureworks.public.Flag
import adventureworks.public.Name
import adventureworks.sales.salesterritory.SalesterritoryFields
import adventureworks.sales.salesterritory.SalesterritoryId
import adventureworks.sales.salesterritory.SalesterritoryRow
import dev.typr.foundations.PgTypes
import dev.typr.foundations.RowParser
import dev.typr.foundations.dsl.FieldsBase
import dev.typr.foundations.dsl.Path
import dev.typr.foundations.dsl.SqlExpr.FieldLike
import dev.typr.foundations.kotlin.ForeignKey
import dev.typr.foundations.kotlin.RelationStructure
import dev.typr.foundations.kotlin.SqlExpr
import dev.typr.foundations.kotlin.SqlExpr.Field
import dev.typr.foundations.kotlin.SqlExpr.IdField
import dev.typr.foundations.kotlin.TupleExpr8
import java.time.LocalDateTime
import java.util.UUID
import kotlin.collections.List

data class StateprovinceFields(val _path: List<Path>) : TupleExpr8<StateprovinceId, String, CountryregionId, Flag, Name, SalesterritoryId, UUID, LocalDateTime>, RelationStructure<StateprovinceFields, StateprovinceRow>, FieldsBase<StateprovinceRow> {
  override fun _1(): SqlExpr<StateprovinceId> = stateprovinceid()

  override fun _2(): SqlExpr<String> = stateprovincecode()

  override fun _3(): SqlExpr<CountryregionId> = countryregioncode()

  override fun _4(): SqlExpr<Flag> = isonlystateprovinceflag()

  override fun _5(): SqlExpr<Name> = name()

  override fun _6(): SqlExpr<SalesterritoryId> = territoryid()

  override fun _7(): SqlExpr<UUID> = rowguid()

  override fun _8(): SqlExpr<LocalDateTime> = modifieddate()

  override fun _path(): List<Path> = _path

  override fun columns(): List<FieldLike<*, StateprovinceRow>> = listOf(this.stateprovinceid().underlying, this.stateprovincecode().underlying, this.countryregioncode().underlying, this.isonlystateprovinceflag().underlying, this.name().underlying, this.territoryid().underlying, this.rowguid().underlying, this.modifieddate().underlying)

  fun countryregioncode(): Field<CountryregionId, StateprovinceRow> = Field<CountryregionId, StateprovinceRow>(_path, "countryregioncode", StateprovinceRow::countryregioncode, null, null, { row, value -> row.copy(countryregioncode = value) }, CountryregionId.pgType)

  fun fkCountryregion(): ForeignKey<CountryregionFields, CountryregionRow> = ForeignKey.of<CountryregionFields, CountryregionRow>("person.FK_StateProvince_CountryRegion_CountryRegionCode").withColumnPair<CountryregionId>(countryregioncode(), CountryregionFields::countryregioncode)

  fun fkSalesSalesterritory(): ForeignKey<SalesterritoryFields, SalesterritoryRow> = ForeignKey.of<SalesterritoryFields, SalesterritoryRow>("person.FK_StateProvince_SalesTerritory_TerritoryID").withColumnPair<SalesterritoryId>(territoryid(), SalesterritoryFields::territoryid)

  fun isonlystateprovinceflag(): Field<Flag, StateprovinceRow> = Field<Flag, StateprovinceRow>(_path, "isonlystateprovinceflag", StateprovinceRow::isonlystateprovinceflag, null, "bool", { row, value -> row.copy(isonlystateprovinceflag = value) }, Flag.pgType)

  fun modifieddate(): Field<LocalDateTime, StateprovinceRow> = Field<LocalDateTime, StateprovinceRow>(_path, "modifieddate", StateprovinceRow::modifieddate, null, "timestamp", { row, value -> row.copy(modifieddate = value) }, PgTypes.timestamp)

  fun name(): Field<Name, StateprovinceRow> = Field<Name, StateprovinceRow>(_path, "name", StateprovinceRow::name, null, "varchar", { row, value -> row.copy(name = value) }, Name.pgType)

  override fun rowParser(): RowParser<StateprovinceRow> = StateprovinceRow._rowParser.underlying

  fun rowguid(): Field<UUID, StateprovinceRow> = Field<UUID, StateprovinceRow>(_path, "rowguid", StateprovinceRow::rowguid, null, "uuid", { row, value -> row.copy(rowguid = value) }, PgTypes.uuid)

  fun stateprovincecode(): Field<String, StateprovinceRow> = Field<String, StateprovinceRow>(_path, "stateprovincecode", StateprovinceRow::stateprovincecode, null, "bpchar", { row, value -> row.copy(stateprovincecode = value) }, PgTypes.bpchar)

  fun stateprovinceid(): IdField<StateprovinceId, StateprovinceRow> = IdField<StateprovinceId, StateprovinceRow>(_path, "stateprovinceid", StateprovinceRow::stateprovinceid, null, "int4", { row, value -> row.copy(stateprovinceid = value) }, StateprovinceId.pgType)

  fun territoryid(): Field<SalesterritoryId, StateprovinceRow> = Field<SalesterritoryId, StateprovinceRow>(_path, "territoryid", StateprovinceRow::territoryid, null, "int4", { row, value -> row.copy(territoryid = value) }, SalesterritoryId.pgType)

  override fun withPaths(_path: List<Path>): RelationStructure<StateprovinceFields, StateprovinceRow> = StateprovinceFields(_path)

  companion object {
    val structure: StateprovinceFields = StateprovinceFields(emptyList<Path>())
  }
}