/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.inventory

import dev.typr.dslkt.DeleteBuilder
import dev.typr.dslkt.SelectBuilder
import dev.typr.dslkt.UpdateBuilder
import dev.typr.foundationskt.Connection
import dev.typr.foundationskt.ConnectionRead
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map
import testdb.products.ProductsId
import testdb.warehouses.WarehousesId

interface InventoryRepo {
  abstract fun delete(): DeleteBuilder<InventoryFields, InventoryRow>

  abstract fun deleteById(
    inventoryId: InventoryId,
    c: Connection
  ): kotlin.Boolean

  abstract fun deleteByIds(
    inventoryIds: List<InventoryId>,
    c: Connection
  ): Int

  abstract fun insert(
    unsaved: InventoryRow,
    c: Connection
  ): InventoryRow

  abstract fun insert(
    unsaved: InventoryRowUnsaved,
    c: Connection
  ): InventoryRow

  abstract fun select(): SelectBuilder<InventoryFields, InventoryRow>

  abstract fun selectAll(c: ConnectionRead): List<InventoryRow>

  abstract fun selectById(
    inventoryId: InventoryId,
    c: ConnectionRead
  ): InventoryRow?

  abstract fun selectByIds(
    inventoryIds: List<InventoryId>,
    c: ConnectionRead
  ): List<InventoryRow>

  abstract fun selectByIdsTracked(
    inventoryIds: List<InventoryId>,
    c: ConnectionRead
  ): Map<InventoryId, InventoryRow>

  abstract fun selectByUniqueProductIdAndWarehouseId(
    productId: ProductsId,
    warehouseId: WarehousesId,
    c: ConnectionRead
  ): InventoryRow?

  abstract fun update(): UpdateBuilder<InventoryFields, InventoryRow>

  abstract fun update(
    row: InventoryRow,
    c: Connection
  ): kotlin.Boolean

  abstract fun upsert(
    unsaved: InventoryRow,
    c: Connection
  ): InventoryRow

  abstract fun upsertBatch(
    unsaved: Iterator<InventoryRow>,
    c: Connection
  ): List<InventoryRow>
}