/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.product_images;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import testdb.products.ProductsId;
import typo.dsl.DeleteBuilder;
import typo.dsl.Dialect;
import typo.dsl.SelectBuilder;
import typo.dsl.UpdateBuilder;
import typo.runtime.Fragment;
import typo.runtime.Fragment.Literal;
import typo.runtime.MariaTypes;
import static typo.runtime.Fragment.interpolate;

public class ProductImagesRepoImpl implements ProductImagesRepo {
  @Override
  public DeleteBuilder<ProductImagesFields, ProductImagesRow> delete() {
    return DeleteBuilder.of("`product_images`", ProductImagesFields.structure(), Dialect.MARIADB);
  };

  @Override
  public Boolean deleteById(
    ProductImagesId imageId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("delete from `product_images` where `image_id` = "),
      ProductImagesId.pgType.encode(imageId),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  @Override
  public Integer deleteByIds(
    ProductImagesId[] imageIds,
    Connection c
  ) {
    ArrayList<Fragment> fragments = new ArrayList<Fragment>();
    for (var id : imageIds) { fragments.add(ProductImagesId.pgType.encode(id)); };
    return Fragment.interpolate(Fragment.lit("delete from `product_images` where `image_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).update().runUnchecked(c);
  };

  @Override
  public ProductImagesRow insert(
    ProductImagesRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         insert into `product_images`(`product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`)
         values ("""),
      ProductsId.pgType.encode(unsaved.productId()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.encode(unsaved.imageUrl()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.opt().encode(unsaved.thumbnailUrl()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.opt().encode(unsaved.altText()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.smallint.encode(unsaved.sortOrder()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.bool.encode(unsaved.isPrimary()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.blob.opt().encode(unsaved.imageData()),
      typo.runtime.Fragment.lit("""
         )
         returning `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`
      """)
    )
      .updateReturning(ProductImagesRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  @Override
  public ProductImagesRow insert(
    ProductImagesRowUnsaved unsaved,
    Connection c
  ) {
    ArrayList<Literal> columns = new ArrayList<Literal>();;
    ArrayList<Fragment> values = new ArrayList<Fragment>();;
    columns.add(Fragment.lit("`product_id`"));
    values.add(interpolate(
      ProductsId.pgType.encode(unsaved.productId()),
      typo.runtime.Fragment.lit("""
      """)
    ));
    columns.add(Fragment.lit("`image_url`"));
    values.add(interpolate(
      MariaTypes.text.encode(unsaved.imageUrl()),
      typo.runtime.Fragment.lit("""
      """)
    ));
    unsaved.thumbnailUrl().visit(
      () -> {
  
      },
      value -> {
        columns.add(Fragment.lit("`thumbnail_url`"));
        values.add(interpolate(
        MariaTypes.text.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """)
      ));
      }
    );;
    unsaved.altText().visit(
      () -> {
  
      },
      value -> {
        columns.add(Fragment.lit("`alt_text`"));
        values.add(interpolate(
        MariaTypes.text.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """)
      ));
      }
    );;
    unsaved.sortOrder().visit(
      () -> {
  
      },
      value -> {
        columns.add(Fragment.lit("`sort_order`"));
        values.add(interpolate(
        MariaTypes.smallint.encode(value),
        typo.runtime.Fragment.lit("""
        """)
      ));
      }
    );;
    unsaved.isPrimary().visit(
      () -> {
  
      },
      value -> {
        columns.add(Fragment.lit("`is_primary`"));
        values.add(interpolate(
        MariaTypes.bool.encode(value),
        typo.runtime.Fragment.lit("""
        """)
      ));
      }
    );;
    unsaved.imageData().visit(
      () -> {
  
      },
      value -> {
        columns.add(Fragment.lit("`image_data`"));
        values.add(interpolate(
        MariaTypes.blob.opt().encode(value),
        typo.runtime.Fragment.lit("""
        """)
      ));
      }
    );;
    Fragment q = interpolate(
      typo.runtime.Fragment.lit("insert into `product_images`("),
      Fragment.comma(columns),
      typo.runtime.Fragment.lit("""
         )
         values ("""),
      Fragment.comma(values),
      typo.runtime.Fragment.lit("""
         )
         returning `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`
      """)
    );;
    return q.updateReturning(ProductImagesRow._rowParser.exactlyOne()).runUnchecked(c);
  };

  @Override
  public SelectBuilder<ProductImagesFields, ProductImagesRow> select() {
    return SelectBuilder.of("`product_images`", ProductImagesFields.structure(), ProductImagesRow._rowParser, Dialect.MARIADB);
  };

  @Override
  public List<ProductImagesRow> selectAll(Connection c) {
    return interpolate(typo.runtime.Fragment.lit("""
       select `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`
       from `product_images`
    """)).query(ProductImagesRow._rowParser.all()).runUnchecked(c);
  };

  @Override
  public Optional<ProductImagesRow> selectById(
    ProductImagesId imageId,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         select `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`
         from `product_images`
         where `image_id` = """),
      ProductImagesId.pgType.encode(imageId),
      typo.runtime.Fragment.lit("")
    ).query(ProductImagesRow._rowParser.first()).runUnchecked(c);
  };

  @Override
  public List<ProductImagesRow> selectByIds(
    ProductImagesId[] imageIds,
    Connection c
  ) {
    ArrayList<Fragment> fragments = new ArrayList<Fragment>();
    for (var id : imageIds) { fragments.add(ProductImagesId.pgType.encode(id)); };
    return Fragment.interpolate(Fragment.lit("select `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data` from `product_images` where `image_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).query(ProductImagesRow._rowParser.all()).runUnchecked(c);
  };

  @Override
  public Map<ProductImagesId, ProductImagesRow> selectByIdsTracked(
    ProductImagesId[] imageIds,
    Connection c
  ) {
    HashMap<ProductImagesId, ProductImagesRow> ret = new HashMap<ProductImagesId, ProductImagesRow>();
    selectByIds(imageIds, c).forEach(row -> ret.put(row.imageId(), row));
    return ret;
  };

  @Override
  public UpdateBuilder<ProductImagesFields, ProductImagesRow> update() {
    return UpdateBuilder.of("`product_images`", ProductImagesFields.structure(), ProductImagesRow._rowParser.all(), Dialect.MARIADB);
  };

  @Override
  public Boolean update(
    ProductImagesRow row,
    Connection c
  ) {
    ProductImagesId imageId = row.imageId();;
    return interpolate(
      typo.runtime.Fragment.lit("""
         update `product_images`
         set `product_id` = """),
      ProductsId.pgType.encode(row.productId()),
      typo.runtime.Fragment.lit("""
         ,
         `image_url` = """),
      MariaTypes.text.encode(row.imageUrl()),
      typo.runtime.Fragment.lit("""
         ,
         `thumbnail_url` = """),
      MariaTypes.text.opt().encode(row.thumbnailUrl()),
      typo.runtime.Fragment.lit("""
         ,
         `alt_text` = """),
      MariaTypes.text.opt().encode(row.altText()),
      typo.runtime.Fragment.lit("""
         ,
         `sort_order` = """),
      MariaTypes.smallint.encode(row.sortOrder()),
      typo.runtime.Fragment.lit("""
         ,
         `is_primary` = """),
      MariaTypes.bool.encode(row.isPrimary()),
      typo.runtime.Fragment.lit("""
         ,
         `image_data` = """),
      MariaTypes.blob.opt().encode(row.imageData()),
      typo.runtime.Fragment.lit("""
   
         where `image_id` = """),
      ProductImagesId.pgType.encode(imageId),
      typo.runtime.Fragment.lit("")
    ).update().runUnchecked(c) > 0;
  };

  @Override
  public ProductImagesRow upsert(
    ProductImagesRow unsaved,
    Connection c
  ) {
    return interpolate(
      typo.runtime.Fragment.lit("""
         INSERT INTO `product_images`(`product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`)
         VALUES ("""),
      ProductsId.pgType.encode(unsaved.productId()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.encode(unsaved.imageUrl()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.opt().encode(unsaved.thumbnailUrl()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.text.opt().encode(unsaved.altText()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.smallint.encode(unsaved.sortOrder()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.bool.encode(unsaved.isPrimary()),
      typo.runtime.Fragment.lit(", "),
      MariaTypes.blob.opt().encode(unsaved.imageData()),
      typo.runtime.Fragment.lit("""
         )
         ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`),
         `image_url` = VALUES(`image_url`),
         `thumbnail_url` = VALUES(`thumbnail_url`),
         `alt_text` = VALUES(`alt_text`),
         `sort_order` = VALUES(`sort_order`),
         `is_primary` = VALUES(`is_primary`),
         `image_data` = VALUES(`image_data`)
         RETURNING `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`""")
    )
      .updateReturning(ProductImagesRow._rowParser.exactlyOne())
      .runUnchecked(c);
  };

  @Override
  public List<ProductImagesRow> upsertBatch(
    Iterator<ProductImagesRow> unsaved,
    Connection c
  ) {
    return interpolate(typo.runtime.Fragment.lit("""
                INSERT INTO `product_images`(`image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`),
                `image_url` = VALUES(`image_url`),
                `thumbnail_url` = VALUES(`thumbnail_url`),
                `alt_text` = VALUES(`alt_text`),
                `sort_order` = VALUES(`sort_order`),
                `is_primary` = VALUES(`is_primary`),
                `image_data` = VALUES(`image_data`)
                RETURNING `image_id`, `product_id`, `image_url`, `thumbnail_url`, `alt_text`, `sort_order`, `is_primary`, `image_data`"""))
      .updateReturningEach(ProductImagesRow._rowParser, unsaved)
      .runUnchecked(c);
  };
}