/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.update_person_returning

import adventureworks.customtypes.TypoLocalDateTime
import java.sql.Connection
import java.util.Optional
import kotlin.collections.List

interface UpdatePersonReturningSqlRepo {
  fun apply(
    suffix: /* nullability unknown */ Optional<String>,
    cutoff: /* nullability unknown */ Optional<TypoLocalDateTime>,
    c: Connection
  ): List<UpdatePersonReturningSqlRow>
}