/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.crc

import adventureworks.person.countryregion.CountryregionId
import adventureworks.sales.currency.CurrencyId
import java.time.LocalDateTime
import typr.kotlindsl.RowParser
import typr.kotlindsl.RowParsers
import typr.runtime.PgTypes

/** View: sa.crc */
data class CrcViewRow(
  /** Points to [adventureworks.sales.countryregioncurrency.CountryregioncurrencyRow.countryregioncode] */
  val countryregioncode: CountryregionId,
  /** Points to [adventureworks.sales.countryregioncurrency.CountryregioncurrencyRow.currencycode] */
  val currencycode: CurrencyId,
  /** Points to [adventureworks.sales.countryregioncurrency.CountryregioncurrencyRow.modifieddate] */
  val modifieddate: LocalDateTime
) {
  companion object {
    val _rowParser: RowParser<CrcViewRow> = RowParsers.of(CountryregionId.pgType, CurrencyId.pgType, PgTypes.timestamp, { t0, t1, t2 -> CrcViewRow(t0, t1, t2) }, { row -> arrayOf<Any?>(row.countryregioncode, row.currencycode, row.modifieddate) })
  }
}