/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.productproductphoto;

import java.sql.Connection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import typr.dsl.DeleteBuilder;
import typr.dsl.SelectBuilder;
import typr.dsl.UpdateBuilder;

public interface ProductproductphotoRepo {
  DeleteBuilder<ProductproductphotoFields, ProductproductphotoRow> delete();

  Boolean deleteById(ProductproductphotoId compositeId, Connection c);

  Integer deleteByIds(ProductproductphotoId[] compositeIds, Connection c);

  ProductproductphotoRow insert(ProductproductphotoRow unsaved, Connection c);

  ProductproductphotoRow insert(ProductproductphotoRowUnsaved unsaved, Connection c);

  Long insertStreaming(Iterator<ProductproductphotoRow> unsaved, Integer batchSize, Connection c);

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  Long insertUnsavedStreaming(
      Iterator<ProductproductphotoRowUnsaved> unsaved, Integer batchSize, Connection c);

  SelectBuilder<ProductproductphotoFields, ProductproductphotoRow> select();

  List<ProductproductphotoRow> selectAll(Connection c);

  Optional<ProductproductphotoRow> selectById(ProductproductphotoId compositeId, Connection c);

  List<ProductproductphotoRow> selectByIds(ProductproductphotoId[] compositeIds, Connection c);

  Map<ProductproductphotoId, ProductproductphotoRow> selectByIdsTracked(
      ProductproductphotoId[] compositeIds, Connection c);

  UpdateBuilder<ProductproductphotoFields, ProductproductphotoRow> update();

  Boolean update(ProductproductphotoRow row, Connection c);

  ProductproductphotoRow upsert(ProductproductphotoRow unsaved, Connection c);

  List<ProductproductphotoRow> upsertBatch(Iterator<ProductproductphotoRow> unsaved, Connection c);

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  Integer upsertStreaming(
      Iterator<ProductproductphotoRow> unsaved, Integer batchSize, Connection c);
}
