/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.vstorewithdemographics;

import adventureworks.person.businessentity.BusinessentityId;
import adventureworks.public_.Name;
import com.fasterxml.jackson.annotation.JsonProperty;
import typo.data.Money;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;

/** View: sales.vstorewithdemographics */
public record VstorewithdemographicsViewRow(
  /** Points to {@link adventureworks.sales.store.StoreRow#businessentityid()} */
  BusinessentityId businessentityid,
  /** Points to {@link adventureworks.sales.store.StoreRow#name()} */
  Name name,
  @JsonProperty("AnnualSales") Money annualSales,
  @JsonProperty("AnnualRevenue") Money annualRevenue,
  @JsonProperty("BankName") String bankName,
  @JsonProperty("BusinessType") String businessType,
  @JsonProperty("YearOpened") Integer yearOpened,
  @JsonProperty("Specialty") String specialty,
  @JsonProperty("SquareFeet") Integer squareFeet,
  @JsonProperty("Brands") String brands,
  @JsonProperty("Internet") String internet,
  @JsonProperty("NumberEmployees") Integer numberEmployees
) {
  /** Points to {@link adventureworks.sales.store.StoreRow#businessentityid()} */
  public VstorewithdemographicsViewRow withBusinessentityid(BusinessentityId businessentityid) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  /** Points to {@link adventureworks.sales.store.StoreRow#name()} */
  public VstorewithdemographicsViewRow withName(Name name) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withAnnualSales(Money annualSales) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withAnnualRevenue(Money annualRevenue) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withBankName(String bankName) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withBusinessType(String businessType) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withYearOpened(Integer yearOpened) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withSpecialty(String specialty) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withSquareFeet(Integer squareFeet) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withBrands(String brands) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withInternet(String internet) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  public VstorewithdemographicsViewRow withNumberEmployees(Integer numberEmployees) {
    return new VstorewithdemographicsViewRow(businessentityid, name, annualSales, annualRevenue, bankName, businessType, yearOpened, specialty, squareFeet, brands, internet, numberEmployees);
  };

  static RowParser<VstorewithdemographicsViewRow> _rowParser = RowParsers.of(BusinessentityId.pgType, Name.pgType, PgTypes.money, PgTypes.money, PgTypes.text, PgTypes.text, PgTypes.int4, PgTypes.text, PgTypes.int4, PgTypes.text, PgTypes.text, PgTypes.int4, VstorewithdemographicsViewRow::new, row -> new Object[]{row.businessentityid(), row.name(), row.annualSales(), row.annualRevenue(), row.bankName(), row.businessType(), row.yearOpened(), row.specialty(), row.squareFeet(), row.brands(), row.internet(), row.numberEmployees()});;
}