/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_.table_with_generated_columns;

import com.fasterxml.jackson.annotation.JsonValue;
import typo.dsl.Bijection;
import typo.runtime.PgType;
import typo.runtime.PgTypes;
import typo.runtime.internal.arrayMap;

/** Type for the primary key of table `public.table-with-generated-columns` */
public record TableWithGeneratedColumnsId(@JsonValue String value) {
  public TableWithGeneratedColumnsId withValue(String value) {
    return new TableWithGeneratedColumnsId(value);
  }
  ;

  @Override
  public java.lang.String toString() {
    return value.toString();
  }
  ;

  public static Bijection<TableWithGeneratedColumnsId, String> bijection =
      Bijection.of(TableWithGeneratedColumnsId::value, TableWithGeneratedColumnsId::new);

  public static PgType<TableWithGeneratedColumnsId> pgType =
      PgTypes.text.bimap(TableWithGeneratedColumnsId::new, TableWithGeneratedColumnsId::value);

  public static PgType<TableWithGeneratedColumnsId[]> pgTypeArray =
      PgTypes.textArray.bimap(
          xs ->
              arrayMap.map(xs, TableWithGeneratedColumnsId::new, TableWithGeneratedColumnsId.class),
          xs -> arrayMap.map(xs, TableWithGeneratedColumnsId::value, String.class));
}
