/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.cu;

import java.sql.Connection;
import java.util.List;
import typo.dsl.SelectBuilder;

public interface CuViewRepo {
  SelectBuilder<CuViewFields, CuViewRow> select();

  List<CuViewRow> selectAll(Connection c);
}
