/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.mariatest_spatial_null

import dev.typr.dslkt.DeleteBuilder
import dev.typr.dslkt.SelectBuilder
import dev.typr.dslkt.UpdateBuilder
import dev.typr.foundationskt.Connection
import dev.typr.foundationskt.ConnectionRead
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map

interface MariatestSpatialNullRepo {
  abstract fun delete(): DeleteBuilder<MariatestSpatialNullFields, MariatestSpatialNullRow>

  abstract fun deleteById(
    id: MariatestSpatialNullId,
    c: Connection
  ): kotlin.Boolean

  abstract fun deleteByIds(
    ids: List<MariatestSpatialNullId>,
    c: Connection
  ): Int

  abstract fun insert(
    unsaved: MariatestSpatialNullRow,
    c: Connection
  ): MariatestSpatialNullRow

  abstract fun insert(
    unsaved: MariatestSpatialNullRowUnsaved,
    c: Connection
  ): MariatestSpatialNullRow

  abstract fun select(): SelectBuilder<MariatestSpatialNullFields, MariatestSpatialNullRow>

  abstract fun selectAll(c: ConnectionRead): List<MariatestSpatialNullRow>

  abstract fun selectById(
    id: MariatestSpatialNullId,
    c: ConnectionRead
  ): MariatestSpatialNullRow?

  abstract fun selectByIds(
    ids: List<MariatestSpatialNullId>,
    c: ConnectionRead
  ): List<MariatestSpatialNullRow>

  abstract fun selectByIdsTracked(
    ids: List<MariatestSpatialNullId>,
    c: ConnectionRead
  ): Map<MariatestSpatialNullId, MariatestSpatialNullRow>

  abstract fun update(): UpdateBuilder<MariatestSpatialNullFields, MariatestSpatialNullRow>

  abstract fun update(
    row: MariatestSpatialNullRow,
    c: Connection
  ): kotlin.Boolean

  abstract fun upsert(
    unsaved: MariatestSpatialNullRow,
    c: Connection
  ): MariatestSpatialNullRow

  abstract fun upsertBatch(
    unsaved: Iterator<MariatestSpatialNullRow>,
    c: Connection
  ): List<MariatestSpatialNullRow>
}