/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.productdescription

import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.runtime.internal.arrayMap

/** Type for the primary key of table `production.productdescription` */
data class ProductdescriptionId(val value: Int) {
  companion object {
    val pgType: PgType<ProductdescriptionId> =
      PgTypes.int4.bimap(::ProductdescriptionId, ProductdescriptionId::value)

    val pgTypeArray: PgType<Array<ProductdescriptionId>> =
      PgTypes.int4Array.bimap({ xs -> arrayMap.map(xs, ::ProductdescriptionId, ProductdescriptionId::class.java) }, { xs -> arrayMap.map(xs, ProductdescriptionId::value, Int::class.java) })
  }
}