/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.salestaxrate

import java.lang.RuntimeException
import java.sql.Connection
import java.util.ArrayList
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableMap
import typo.kotlindsl.DeleteBuilder
import typo.kotlindsl.DeleteBuilderMock
import typo.kotlindsl.DeleteParams
import typo.kotlindsl.SelectBuilder
import typo.kotlindsl.SelectBuilderMock
import typo.kotlindsl.SelectParams
import typo.kotlindsl.UpdateBuilder
import typo.kotlindsl.UpdateBuilderMock
import typo.kotlindsl.UpdateParams

data class SalestaxrateRepoMock(
  val toRow: (SalestaxrateRowUnsaved) -> SalestaxrateRow,
  val map: MutableMap<SalestaxrateId, SalestaxrateRow> = mutableMapOf<SalestaxrateId, SalestaxrateRow>()
) : SalestaxrateRepo {
  override fun delete(): DeleteBuilder<SalestaxrateFields, SalestaxrateRow> = DeleteBuilderMock(SalestaxrateFields.structure, { map.values.toList() }, DeleteParams.empty(), { row -> row.salestaxrateid }, { id -> map.remove(id) })

  override fun deleteById(
    salestaxrateid: SalestaxrateId,
    c: Connection
  ): Boolean = map.remove(salestaxrateid) != null

  override fun deleteByIds(
    salestaxrateids: Array<SalestaxrateId>,
    c: Connection
  ): Int {
    var count = 0
    for (id in salestaxrateids) {
      if (map.remove(id) != null) {
      count = count + 1
    }
    }
    return count
  }

  override fun insert(
    unsaved: SalestaxrateRow,
    c: Connection
  ): SalestaxrateRow {
    if (map.containsKey(unsaved.salestaxrateid)) {
      throw RuntimeException("id " + unsaved.salestaxrateid + " already exists")
    }
    map[unsaved.salestaxrateid] = unsaved
    return unsaved
  }

  override fun insert(
    unsaved: SalestaxrateRowUnsaved,
    c: Connection
  ): SalestaxrateRow = insert(toRow(unsaved), c)

  override fun insertStreaming(
    unsaved: Iterator<SalestaxrateRow>,
    batchSize: Int,
    c: Connection
  ): Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.salestaxrateid] = row
      count = count + 1L
    }
    return count
  }

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override fun insertUnsavedStreaming(
    unsaved: Iterator<SalestaxrateRowUnsaved>,
    batchSize: Int,
    c: Connection
  ): Long {
    var count = 0L
    while (unsaved.hasNext()) {
      val unsavedRow = unsaved.next()
      val row = toRow(unsavedRow)
      map[row.salestaxrateid] = row
      count = count + 1L
    }
    return count
  }

  override fun select(): SelectBuilder<SalestaxrateFields, SalestaxrateRow> = SelectBuilderMock(SalestaxrateFields.structure, { map.values.toList() }, SelectParams.empty())

  override fun selectAll(c: Connection): List<SalestaxrateRow> = map.values.toList()

  override fun selectById(
    salestaxrateid: SalestaxrateId,
    c: Connection
  ): SalestaxrateRow? = map[salestaxrateid]

  override fun selectByIds(
    salestaxrateids: Array<SalestaxrateId>,
    c: Connection
  ): List<SalestaxrateRow> {
    val result = ArrayList<SalestaxrateRow>()
    for (id in salestaxrateids) {
      val opt = map[id]
      if (opt != null) {
      result.add(opt!!)
    }
    }
    return result
  }

  override fun selectByIdsTracked(
    salestaxrateids: Array<SalestaxrateId>,
    c: Connection
  ): Map<SalestaxrateId, SalestaxrateRow> = selectByIds(salestaxrateids, c).associateBy({ row: SalestaxrateRow -> row.salestaxrateid })

  override fun update(): UpdateBuilder<SalestaxrateFields, SalestaxrateRow> = UpdateBuilderMock(SalestaxrateFields.structure, { map.values.toList() }, UpdateParams.empty(), { row -> row })

  override fun update(
    row: SalestaxrateRow,
    c: Connection
  ): Boolean {
    val shouldUpdate = map[row.salestaxrateid]?.takeIf({ oldRow -> (oldRow != row) }) != null
    if (shouldUpdate) {
      map[row.salestaxrateid] = row
    }
    return shouldUpdate
  }

  override fun upsert(
    unsaved: SalestaxrateRow,
    c: Connection
  ): SalestaxrateRow {
    map[unsaved.salestaxrateid] = unsaved
    return unsaved
  }

  override fun upsertBatch(
    unsaved: Iterator<SalestaxrateRow>,
    c: Connection
  ): List<SalestaxrateRow> {
    val result = ArrayList<SalestaxrateRow>()
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.salestaxrateid] = row
      result.add(row)
    }
    return result
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override fun upsertStreaming(
    unsaved: Iterator<SalestaxrateRow>,
    batchSize: Int,
    c: Connection
  ): Int {
    var count = 0
    while (unsaved.hasNext()) {
      val row = unsaved.next()
      map[row.salestaxrateid] = row
      count = count + 1
    }
    return count
  }
}