/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks

import adventureworks.public.AccountNumber
import adventureworks.public.Flag
import adventureworks.public.Mydomain
import adventureworks.public.Name
import adventureworks.public.NameStyle
import adventureworks.public.OrderNumber
import adventureworks.public.Phone
import adventureworks.public.ShortText
import java.util.Random

/** Methods to generate random data for domain types */
interface TestDomainInsert {
  /** Domain `public.AccountNumber`
    * No constraint
    */
  fun publicAccountNumber(random: Random): AccountNumber

  /** Domain `public.Flag`
    * No constraint
    */
  fun publicFlag(random: Random): Flag

  /** Domain `public.mydomain`
    * No constraint
    */
  fun publicMydomain(random: Random): Mydomain

  /** Domain `public.Name`
    * No constraint
    */
  fun publicName(random: Random): Name

  /** Domain `public.NameStyle`
    * No constraint
    */
  fun publicNameStyle(random: Random): NameStyle

  /** Domain `public.OrderNumber`
    * No constraint
    */
  fun publicOrderNumber(random: Random): OrderNumber

  /** Domain `public.Phone`
    * No constraint
    */
  fun publicPhone(random: Random): Phone

  /** Domain `public.short_text`
    * Constraint: CHECK ((length(VALUE) <= 55))
    */
  fun publicShortText(random: Random): ShortText
}