/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.product

import adventureworks.customtypes.Defaulted
import adventureworks.customtypes.Defaulted.UseDefault
import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoShort
import adventureworks.customtypes.TypoUUID
import adventureworks.production.productmodel.ProductmodelId
import adventureworks.production.productsubcategory.ProductsubcategoryId
import adventureworks.production.unitmeasure.UnitmeasureId
import adventureworks.public.Flag
import adventureworks.public.Name
import java.math.BigDecimal
import typo.runtime.PgText
import typo.runtime.PgTypes

/** This class corresponds to a row in table `production.product` which has not been persisted yet */
data class ProductRowUnsaved(
  /** Name of the product. */
  val name: Name,
  /** Unique product identification number. */
  val productnumber: /* max 25 chars */ java.lang.String,
  /** Product color. */
  val color: /* max 15 chars */ java.lang.String?,
  /** Minimum inventory quantity.
    * Constraint CK_Product_SafetyStockLevel affecting columns safetystocklevel:  ((safetystocklevel > 0))
    */
  val safetystocklevel: TypoShort,
  /** Inventory level that triggers a purchase order or work order.
    * Constraint CK_Product_ReorderPoint affecting columns reorderpoint:  ((reorderpoint > 0))
    */
  val reorderpoint: TypoShort,
  /** Standard cost of the product.
    * Constraint CK_Product_StandardCost affecting columns standardcost:  ((standardcost >= 0.00))
    */
  val standardcost: BigDecimal,
  /** Selling price.
    * Constraint CK_Product_ListPrice affecting columns listprice:  ((listprice >= 0.00))
    */
  val listprice: BigDecimal,
  /** Product size. */
  val size: /* max 5 chars */ java.lang.String?,
  /** Unit of measure for Size column.
    * Points to [adventureworks.production.unitmeasure.UnitmeasureRow.unitmeasurecode]
    */
  val sizeunitmeasurecode: UnitmeasureId?,
  /** Unit of measure for Weight column.
    * Points to [adventureworks.production.unitmeasure.UnitmeasureRow.unitmeasurecode]
    */
  val weightunitmeasurecode: UnitmeasureId?,
  /** Product weight.
    * Constraint CK_Product_Weight affecting columns weight:  ((weight > 0.00))
    */
  val weight: BigDecimal?,
  /** Number of days required to manufacture the product.
    * Constraint CK_Product_DaysToManufacture affecting columns daystomanufacture:  ((daystomanufacture >= 0))
    */
  val daystomanufacture: Int,
  /** R = Road, M = Mountain, T = Touring, S = Standard
    * Constraint CK_Product_ProductLine affecting columns productline:  (((upper((productline)::text) = ANY (ARRAY['S'::text, 'T'::text, 'M'::text, 'R'::text])) OR (productline IS NULL)))
    */
  val productline: /* bpchar, max 2 chars */ java.lang.String?,
  /** H = High, M = Medium, L = Low
    * Constraint CK_Product_Class affecting columns class:  (((upper((class)::text) = ANY (ARRAY['L'::text, 'M'::text, 'H'::text])) OR (class IS NULL)))
    */
  val `class`: /* bpchar, max 2 chars */ java.lang.String?,
  /** W = Womens, M = Mens, U = Universal
    * Constraint CK_Product_Style affecting columns style:  (((upper((style)::text) = ANY (ARRAY['W'::text, 'M'::text, 'U'::text])) OR (style IS NULL)))
    */
  val style: /* bpchar, max 2 chars */ java.lang.String?,
  /** Product is a member of this product subcategory. Foreign key to ProductSubCategory.ProductSubCategoryID.
    * Points to [adventureworks.production.productsubcategory.ProductsubcategoryRow.productsubcategoryid]
    */
  val productsubcategoryid: ProductsubcategoryId?,
  /** Product is a member of this product model. Foreign key to ProductModel.ProductModelID.
    * Points to [adventureworks.production.productmodel.ProductmodelRow.productmodelid]
    */
  val productmodelid: ProductmodelId?,
  /** Date the product was available for sale.
    * Constraint CK_Product_SellEndDate affecting columns sellenddate, sellstartdate:  (((sellenddate >= sellstartdate) OR (sellenddate IS NULL)))
    */
  val sellstartdate: TypoLocalDateTime,
  /** Date the product was no longer available for sale.
    * Constraint CK_Product_SellEndDate affecting columns sellenddate, sellstartdate:  (((sellenddate >= sellstartdate) OR (sellenddate IS NULL)))
    */
  val sellenddate: TypoLocalDateTime?,
  /** Date the product was discontinued. */
  val discontinueddate: TypoLocalDateTime?,
  /** Default: nextval('production.product_productid_seq'::regclass)
    * Primary key for Product records.
    */
  val productid: Defaulted<ProductId>,
  /** Default: true
    * 0 = Product is purchased, 1 = Product is manufactured in-house.
    */
  val makeflag: Defaulted<Flag>,
  /** Default: true
    * 0 = Product is not a salable item. 1 = Product is salable.
    */
  val finishedgoodsflag: Defaulted<Flag>,
  /** Default: uuid_generate_v1() */
  val rowguid: Defaulted<TypoUUID>,
  /** Default: now() */
  val modifieddate: Defaulted<TypoLocalDateTime>
) {
  constructor(name: Name, productnumber: /* max 25 chars */ java.lang.String, safetystocklevel: TypoShort, reorderpoint: TypoShort, standardcost: BigDecimal, listprice: BigDecimal, daystomanufacture: Int, sellstartdate: TypoLocalDateTime) : this(name, productnumber, null, safetystocklevel, reorderpoint, standardcost, listprice, null, null, null, null, daystomanufacture, null, null, null, null, null, sellstartdate, null, null, UseDefault(), UseDefault(), UseDefault(), UseDefault(), UseDefault())

  fun toRow(
    productidDefault: () -> ProductId,
    makeflagDefault: () -> Flag,
    finishedgoodsflagDefault: () -> Flag,
    rowguidDefault: () -> TypoUUID,
    modifieddateDefault: () -> TypoLocalDateTime
  ): ProductRow = ProductRow(productid = productid.getOrElse(productidDefault), name = name, productnumber = productnumber, makeflag = makeflag.getOrElse(makeflagDefault), finishedgoodsflag = finishedgoodsflag.getOrElse(finishedgoodsflagDefault), color = color, safetystocklevel = safetystocklevel, reorderpoint = reorderpoint, standardcost = standardcost, listprice = listprice, size = size, sizeunitmeasurecode = sizeunitmeasurecode, weightunitmeasurecode = weightunitmeasurecode, weight = weight, daystomanufacture = daystomanufacture, productline = productline, `class` = `class`, style = style, productsubcategoryid = productsubcategoryid, productmodelid = productmodelid, sellstartdate = sellstartdate, sellenddate = sellenddate, discontinueddate = discontinueddate, rowguid = rowguid.getOrElse(rowguidDefault), modifieddate = modifieddate.getOrElse(modifieddateDefault))

  companion object {
    val pgText: PgText<ProductRowUnsaved> =
      PgText.instance({ row, sb -> {
        Name.pgType.pgText.unsafeEncode(row.name, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.pgText.unsafeEncode(row.productnumber, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.opt().pgText.unsafeEncode(row.color, sb);
        sb.append(PgText.DELIMETER);
        TypoShort.pgType.pgText.unsafeEncode(row.safetystocklevel, sb);
        sb.append(PgText.DELIMETER);
        TypoShort.pgType.pgText.unsafeEncode(row.reorderpoint, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.numeric.pgText.unsafeEncode(row.standardcost, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.numeric.pgText.unsafeEncode(row.listprice, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.opt().pgText.unsafeEncode(row.size, sb);
        sb.append(PgText.DELIMETER);
        UnitmeasureId.pgType.opt().pgText.unsafeEncode(row.sizeunitmeasurecode, sb);
        sb.append(PgText.DELIMETER);
        UnitmeasureId.pgType.opt().pgText.unsafeEncode(row.weightunitmeasurecode, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.numeric.opt().pgText.unsafeEncode(row.weight, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.int4.pgText.unsafeEncode(row.daystomanufacture, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.opt().pgText.unsafeEncode(row.productline, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.opt().pgText.unsafeEncode(row.`class`, sb);
        sb.append(PgText.DELIMETER);
        PgTypes.text.opt().pgText.unsafeEncode(row.style, sb);
        sb.append(PgText.DELIMETER);
        ProductsubcategoryId.pgType.opt().pgText.unsafeEncode(row.productsubcategoryid, sb);
        sb.append(PgText.DELIMETER);
        ProductmodelId.pgType.opt().pgText.unsafeEncode(row.productmodelid, sb);
        sb.append(PgText.DELIMETER);
        TypoLocalDateTime.pgType.pgText.unsafeEncode(row.sellstartdate, sb);
        sb.append(PgText.DELIMETER);
        TypoLocalDateTime.pgType.opt().pgText.unsafeEncode(row.sellenddate, sb);
        sb.append(PgText.DELIMETER);
        TypoLocalDateTime.pgType.opt().pgText.unsafeEncode(row.discontinueddate, sb);
        sb.append(PgText.DELIMETER);
        Defaulted.pgText(ProductId.pgType.pgText).unsafeEncode(row.productid, sb);
        sb.append(PgText.DELIMETER);
        Defaulted.pgText(Flag.pgType.pgText).unsafeEncode(row.makeflag, sb);
        sb.append(PgText.DELIMETER);
        Defaulted.pgText(Flag.pgType.pgText).unsafeEncode(row.finishedgoodsflag, sb);
        sb.append(PgText.DELIMETER);
        Defaulted.pgText(TypoUUID.pgType.pgText).unsafeEncode(row.rowguid, sb);
        sb.append(PgText.DELIMETER);
        Defaulted.pgText(TypoLocalDateTime.pgType.pgText).unsafeEncode(row.modifieddate, sb);
      } })
  }
}