/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.purchasing.purchaseorderdetail;

import adventureworks.purchasing.purchaseorderheader.PurchaseorderheaderId;
import typo.runtime.PgTypes;
import typo.runtime.RowParser;
import typo.runtime.RowParsers;

/** Type for the composite primary key of table `purchasing.purchaseorderdetail` */
public record PurchaseorderdetailId(
    PurchaseorderheaderId purchaseorderid, Integer purchaseorderdetailid) {
  public PurchaseorderdetailId withPurchaseorderid(PurchaseorderheaderId purchaseorderid) {
    return new PurchaseorderdetailId(purchaseorderid, purchaseorderdetailid);
  }
  ;

  public PurchaseorderdetailId withPurchaseorderdetailid(Integer purchaseorderdetailid) {
    return new PurchaseorderdetailId(purchaseorderid, purchaseorderdetailid);
  }
  ;

  public static RowParser<PurchaseorderdetailId> _rowParser =
      RowParsers.of(
          PurchaseorderheaderId.pgType,
          PgTypes.int4,
          PurchaseorderdetailId::new,
          row -> new Object[] {row.purchaseorderid(), row.purchaseorderdetailid()});
  ;
}
