/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.unitmeasure

import java.sql.Connection
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map
import typr.kotlindsl.DeleteBuilder
import typr.kotlindsl.SelectBuilder
import typr.kotlindsl.UpdateBuilder

interface UnitmeasureRepo {
  abstract fun delete(): DeleteBuilder<UnitmeasureFields, UnitmeasureRow>

  abstract fun deleteById(
    unitmeasurecode: UnitmeasureId,
    c: Connection
  ): Boolean

  abstract fun deleteByIds(
    unitmeasurecodes: Array<UnitmeasureId>,
    c: Connection
  ): Int

  abstract fun insert(
    unsaved: UnitmeasureRow,
    c: Connection
  ): UnitmeasureRow

  abstract fun insert(
    unsaved: UnitmeasureRowUnsaved,
    c: Connection
  ): UnitmeasureRow

  abstract fun insertStreaming(
    unsaved: Iterator<UnitmeasureRow>,
    batchSize: Int,
    c: Connection
  ): Long

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  abstract fun insertUnsavedStreaming(
    unsaved: Iterator<UnitmeasureRowUnsaved>,
    batchSize: Int,
    c: Connection
  ): Long

  abstract fun select(): SelectBuilder<UnitmeasureFields, UnitmeasureRow>

  abstract fun selectAll(c: Connection): List<UnitmeasureRow>

  abstract fun selectById(
    unitmeasurecode: UnitmeasureId,
    c: Connection
  ): UnitmeasureRow?

  abstract fun selectByIds(
    unitmeasurecodes: Array<UnitmeasureId>,
    c: Connection
  ): List<UnitmeasureRow>

  abstract fun selectByIdsTracked(
    unitmeasurecodes: Array<UnitmeasureId>,
    c: Connection
  ): Map<UnitmeasureId, UnitmeasureRow>

  abstract fun update(): UpdateBuilder<UnitmeasureFields, UnitmeasureRow>

  abstract fun update(
    row: UnitmeasureRow,
    c: Connection
  ): Boolean

  abstract fun upsert(
    unsaved: UnitmeasureRow,
    c: Connection
  ): UnitmeasureRow

  abstract fun upsertBatch(
    unsaved: Iterator<UnitmeasureRow>,
    c: Connection
  ): List<UnitmeasureRow>

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  abstract fun upsertStreaming(
    unsaved: Iterator<UnitmeasureRow>,
    batchSize: Int,
    c: Connection
  ): Int
}