/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.billofmaterials

import adventureworks.production.product.ProductId
import adventureworks.production.unitmeasure.UnitmeasureId
import java.sql.Connection
import java.util.ArrayList
import kotlin.collections.Iterator
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableMap
import typo.kotlindsl.DeleteBuilder
import typo.kotlindsl.Dialect
import typo.kotlindsl.Fragment
import typo.kotlindsl.KotlinDbTypes
import typo.kotlindsl.SelectBuilder
import typo.kotlindsl.UpdateBuilder
import typo.kotlindsl.nullable
import typo.runtime.PgTypes
import typo.runtime.streamingInsert

class BillofmaterialsRepoImpl() : BillofmaterialsRepo {
  override fun delete(): DeleteBuilder<BillofmaterialsFields, BillofmaterialsRow> = DeleteBuilder.of("\"production\".\"billofmaterials\"", BillofmaterialsFields.structure, Dialect.POSTGRESQL)

  override fun deleteById(
    billofmaterialsid: Int,
    c: Connection
  ): Boolean = Fragment.interpolate(Fragment.lit("delete from \"production\".\"billofmaterials\" where \"billofmaterialsid\" = "), Fragment.encode(KotlinDbTypes.PgTypes.int4, billofmaterialsid), Fragment.lit("")).update().runUnchecked(c) > 0

  override fun deleteByIds(
    billofmaterialsids: Array<Int>,
    c: Connection
  ): Int = Fragment.interpolate(Fragment.lit("delete\nfrom \"production\".\"billofmaterials\"\nwhere \"billofmaterialsid\" = ANY("), Fragment.encode(PgTypes.int4Array, billofmaterialsids), Fragment.lit(")"))
    .update()
    .runUnchecked(c)

  override fun insert(
    unsaved: BillofmaterialsRow,
    c: Connection
  ): BillofmaterialsRow = Fragment.interpolate(Fragment.lit("insert into \"production\".\"billofmaterials\"(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\")\nvalues ("), Fragment.encode(KotlinDbTypes.PgTypes.int4, unsaved.billofmaterialsid), Fragment.lit("::int4, "), Fragment.encode(ProductId.pgType.nullable(), unsaved.productassemblyid), Fragment.lit("::int4, "), Fragment.encode(ProductId.pgType, unsaved.componentid), Fragment.lit("::int4, "), Fragment.encode(PgTypes.timestamp, unsaved.startdate), Fragment.lit("::timestamp, "), Fragment.encode(PgTypes.timestamp.nullable(), unsaved.enddate), Fragment.lit("::timestamp, "), Fragment.encode(UnitmeasureId.pgType, unsaved.unitmeasurecode), Fragment.lit("::bpchar, "), Fragment.encode(KotlinDbTypes.PgTypes.int2, unsaved.bomlevel), Fragment.lit("::int2, "), Fragment.encode(PgTypes.numeric, unsaved.perassemblyqty), Fragment.lit("::numeric, "), Fragment.encode(PgTypes.timestamp, unsaved.modifieddate), Fragment.lit("::timestamp)\nRETURNING \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\"\n"))
    .updateReturning(BillofmaterialsRow._rowParser.exactlyOne()).runUnchecked(c)

  override fun insert(
    unsaved: BillofmaterialsRowUnsaved,
    c: Connection
  ): BillofmaterialsRow {
    val columns: ArrayList<Fragment> = ArrayList()
    val values: ArrayList<Fragment> = ArrayList()
    columns.add(Fragment.lit("\"productassemblyid\""))
    values.add(Fragment.interpolate(Fragment.encode(ProductId.pgType.nullable(), unsaved.productassemblyid), Fragment.lit("::int4")))
    columns.add(Fragment.lit("\"componentid\""))
    values.add(Fragment.interpolate(Fragment.encode(ProductId.pgType, unsaved.componentid), Fragment.lit("::int4")))
    columns.add(Fragment.lit("\"enddate\""))
    values.add(Fragment.interpolate(Fragment.encode(PgTypes.timestamp.nullable(), unsaved.enddate), Fragment.lit("::timestamp")))
    columns.add(Fragment.lit("\"unitmeasurecode\""))
    values.add(Fragment.interpolate(Fragment.encode(UnitmeasureId.pgType, unsaved.unitmeasurecode), Fragment.lit("::bpchar")))
    columns.add(Fragment.lit("\"bomlevel\""))
    values.add(Fragment.interpolate(Fragment.encode(KotlinDbTypes.PgTypes.int2, unsaved.bomlevel), Fragment.lit("::int2")))
    unsaved.billofmaterialsid.visit(
      {  },
      { value -> columns.add(Fragment.lit("\"billofmaterialsid\""))
      values.add(Fragment.interpolate(Fragment.encode(KotlinDbTypes.PgTypes.int4, value), Fragment.lit("::int4"))) }
    );
    unsaved.startdate.visit(
      {  },
      { value -> columns.add(Fragment.lit("\"startdate\""))
      values.add(Fragment.interpolate(Fragment.encode(PgTypes.timestamp, value), Fragment.lit("::timestamp"))) }
    );
    unsaved.perassemblyqty.visit(
      {  },
      { value -> columns.add(Fragment.lit("\"perassemblyqty\""))
      values.add(Fragment.interpolate(Fragment.encode(PgTypes.numeric, value), Fragment.lit("::numeric"))) }
    );
    unsaved.modifieddate.visit(
      {  },
      { value -> columns.add(Fragment.lit("\"modifieddate\""))
      values.add(Fragment.interpolate(Fragment.encode(PgTypes.timestamp, value), Fragment.lit("::timestamp"))) }
    );
    val q: Fragment = Fragment.interpolate(Fragment.lit("insert into \"production\".\"billofmaterials\"("), Fragment.comma(columns.toMutableList()), Fragment.lit(")\nvalues ("), Fragment.comma(values.toMutableList()), Fragment.lit(")\nRETURNING \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\"\n"))
    return q.updateReturning(BillofmaterialsRow._rowParser.exactlyOne()).runUnchecked(c)
  }

  override fun insertStreaming(
    unsaved: Iterator<BillofmaterialsRow>,
    batchSize: Int,
    c: Connection
  ): Long = streamingInsert.insertUnchecked("COPY \"production\".\"billofmaterials\"(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\") FROM STDIN", batchSize, unsaved, c, BillofmaterialsRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override fun insertUnsavedStreaming(
    unsaved: Iterator<BillofmaterialsRowUnsaved>,
    batchSize: Int,
    c: Connection
  ): Long = streamingInsert.insertUnchecked("COPY \"production\".\"billofmaterials\"(\"productassemblyid\", \"componentid\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"billofmaterialsid\", \"startdate\", \"perassemblyqty\", \"modifieddate\") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')", batchSize, unsaved, c, BillofmaterialsRowUnsaved.pgText)

  override fun select(): SelectBuilder<BillofmaterialsFields, BillofmaterialsRow> = SelectBuilder.of("\"production\".\"billofmaterials\"", BillofmaterialsFields.structure, BillofmaterialsRow._rowParser, Dialect.POSTGRESQL)

  override fun selectAll(c: Connection): List<BillofmaterialsRow> = Fragment.interpolate(Fragment.lit("select \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\"\nfrom \"production\".\"billofmaterials\"\n")).query(BillofmaterialsRow._rowParser.all()).runUnchecked(c)

  override fun selectById(
    billofmaterialsid: Int,
    c: Connection
  ): BillofmaterialsRow? = Fragment.interpolate(Fragment.lit("select \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\"\nfrom \"production\".\"billofmaterials\"\nwhere \"billofmaterialsid\" = "), Fragment.encode(KotlinDbTypes.PgTypes.int4, billofmaterialsid), Fragment.lit("")).query(BillofmaterialsRow._rowParser.first()).runUnchecked(c)

  override fun selectByIds(
    billofmaterialsids: Array<Int>,
    c: Connection
  ): List<BillofmaterialsRow> = Fragment.interpolate(Fragment.lit("select \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\"\nfrom \"production\".\"billofmaterials\"\nwhere \"billofmaterialsid\" = ANY("), Fragment.encode(PgTypes.int4Array, billofmaterialsids), Fragment.lit(")")).query(BillofmaterialsRow._rowParser.all()).runUnchecked(c)

  override fun selectByIdsTracked(
    billofmaterialsids: Array<Int>,
    c: Connection
  ): Map<Int, BillofmaterialsRow> {
    val ret: MutableMap<Int, BillofmaterialsRow> = mutableMapOf<Int, BillofmaterialsRow>()
    selectByIds(billofmaterialsids, c).forEach({ row -> ret.put(row.billofmaterialsid, row) })
    return ret.toMap()
  }

  override fun update(): UpdateBuilder<BillofmaterialsFields, BillofmaterialsRow> = UpdateBuilder.of("\"production\".\"billofmaterials\"", BillofmaterialsFields.structure, BillofmaterialsRow._rowParser, Dialect.POSTGRESQL)

  override fun update(
    row: BillofmaterialsRow,
    c: Connection
  ): Boolean {
    val billofmaterialsid: Int = row.billofmaterialsid
    return Fragment.interpolate(Fragment.lit("update \"production\".\"billofmaterials\"\nset \"productassemblyid\" = "), Fragment.encode(ProductId.pgType.nullable(), row.productassemblyid), Fragment.lit("::int4,\n\"componentid\" = "), Fragment.encode(ProductId.pgType, row.componentid), Fragment.lit("::int4,\n\"startdate\" = "), Fragment.encode(PgTypes.timestamp, row.startdate), Fragment.lit("::timestamp,\n\"enddate\" = "), Fragment.encode(PgTypes.timestamp.nullable(), row.enddate), Fragment.lit("::timestamp,\n\"unitmeasurecode\" = "), Fragment.encode(UnitmeasureId.pgType, row.unitmeasurecode), Fragment.lit("::bpchar,\n\"bomlevel\" = "), Fragment.encode(KotlinDbTypes.PgTypes.int2, row.bomlevel), Fragment.lit("::int2,\n\"perassemblyqty\" = "), Fragment.encode(PgTypes.numeric, row.perassemblyqty), Fragment.lit("::numeric,\n\"modifieddate\" = "), Fragment.encode(PgTypes.timestamp, row.modifieddate), Fragment.lit("::timestamp\nwhere \"billofmaterialsid\" = "), Fragment.encode(KotlinDbTypes.PgTypes.int4, billofmaterialsid), Fragment.lit("")).update().runUnchecked(c) > 0
  }

  override fun upsert(
    unsaved: BillofmaterialsRow,
    c: Connection
  ): BillofmaterialsRow = Fragment.interpolate(Fragment.lit("insert into \"production\".\"billofmaterials\"(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\")\nvalues ("), Fragment.encode(KotlinDbTypes.PgTypes.int4, unsaved.billofmaterialsid), Fragment.lit("::int4, "), Fragment.encode(ProductId.pgType.nullable(), unsaved.productassemblyid), Fragment.lit("::int4, "), Fragment.encode(ProductId.pgType, unsaved.componentid), Fragment.lit("::int4, "), Fragment.encode(PgTypes.timestamp, unsaved.startdate), Fragment.lit("::timestamp, "), Fragment.encode(PgTypes.timestamp.nullable(), unsaved.enddate), Fragment.lit("::timestamp, "), Fragment.encode(UnitmeasureId.pgType, unsaved.unitmeasurecode), Fragment.lit("::bpchar, "), Fragment.encode(KotlinDbTypes.PgTypes.int2, unsaved.bomlevel), Fragment.lit("::int2, "), Fragment.encode(PgTypes.numeric, unsaved.perassemblyqty), Fragment.lit("::numeric, "), Fragment.encode(PgTypes.timestamp, unsaved.modifieddate), Fragment.lit("::timestamp)\non conflict (\"billofmaterialsid\")\ndo update set\n  \"productassemblyid\" = EXCLUDED.\"productassemblyid\",\n\"componentid\" = EXCLUDED.\"componentid\",\n\"startdate\" = EXCLUDED.\"startdate\",\n\"enddate\" = EXCLUDED.\"enddate\",\n\"unitmeasurecode\" = EXCLUDED.\"unitmeasurecode\",\n\"bomlevel\" = EXCLUDED.\"bomlevel\",\n\"perassemblyqty\" = EXCLUDED.\"perassemblyqty\",\n\"modifieddate\" = EXCLUDED.\"modifieddate\"\nreturning \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\""))
    .updateReturning(BillofmaterialsRow._rowParser.exactlyOne())
    .runUnchecked(c)

  override fun upsertBatch(
    unsaved: Iterator<BillofmaterialsRow>,
    c: Connection
  ): List<BillofmaterialsRow> = Fragment.interpolate(Fragment.lit("insert into \"production\".\"billofmaterials\"(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\")\nvalues (?::int4, ?::int4, ?::int4, ?::timestamp, ?::timestamp, ?::bpchar, ?::int2, ?::numeric, ?::timestamp)\non conflict (\"billofmaterialsid\")\ndo update set\n  \"productassemblyid\" = EXCLUDED.\"productassemblyid\",\n\"componentid\" = EXCLUDED.\"componentid\",\n\"startdate\" = EXCLUDED.\"startdate\",\n\"enddate\" = EXCLUDED.\"enddate\",\n\"unitmeasurecode\" = EXCLUDED.\"unitmeasurecode\",\n\"bomlevel\" = EXCLUDED.\"bomlevel\",\n\"perassemblyqty\" = EXCLUDED.\"perassemblyqty\",\n\"modifieddate\" = EXCLUDED.\"modifieddate\"\nreturning \"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\""))
    .updateManyReturning(BillofmaterialsRow._rowParser, unsaved)
  .runUnchecked(c)

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override fun upsertStreaming(
    unsaved: Iterator<BillofmaterialsRow>,
    batchSize: Int,
    c: Connection
  ): Int {
    Fragment.interpolate(Fragment.lit("create temporary table billofmaterials_TEMP (like \"production\".\"billofmaterials\") on commit drop")).update().runUnchecked(c)
    streamingInsert.insertUnchecked("copy billofmaterials_TEMP(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\") from stdin", batchSize, unsaved, c, BillofmaterialsRow.pgText)
    return Fragment.interpolate(Fragment.lit("insert into \"production\".\"billofmaterials\"(\"billofmaterialsid\", \"productassemblyid\", \"componentid\", \"startdate\", \"enddate\", \"unitmeasurecode\", \"bomlevel\", \"perassemblyqty\", \"modifieddate\")\nselect * from billofmaterials_TEMP\non conflict (\"billofmaterialsid\")\ndo update set\n  \"productassemblyid\" = EXCLUDED.\"productassemblyid\",\n\"componentid\" = EXCLUDED.\"componentid\",\n\"startdate\" = EXCLUDED.\"startdate\",\n\"enddate\" = EXCLUDED.\"enddate\",\n\"unitmeasurecode\" = EXCLUDED.\"unitmeasurecode\",\n\"bomlevel\" = EXCLUDED.\"bomlevel\",\n\"perassemblyqty\" = EXCLUDED.\"perassemblyqty\",\n\"modifieddate\" = EXCLUDED.\"modifieddate\"\n;\ndrop table billofmaterials_TEMP;")).update().runUnchecked(c)
  }
}