/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.salesorderdetail

import adventureworks.customtypes.Defaulted
import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoShort
import adventureworks.customtypes.TypoUUID
import adventureworks.production.product.ProductId
import adventureworks.sales.salesorderheader.SalesorderheaderId
import adventureworks.sales.specialoffer.SpecialofferId
import cats.instances.list.catsStdInstancesForList
import doobie.free.connection.ConnectionIO
import doobie.postgres.syntax.FragmentOps
import doobie.syntax.SqlInterpolator.SingleFragment.fromWrite
import doobie.util.Write
import doobie.util.fragment.Fragment
import doobie.util.meta.Meta
import doobie.util.update.Update
import fs2.Stream
import typr.dsl.DeleteBuilder
import typr.dsl.SelectBuilder
import typr.dsl.UpdateBuilder
import doobie.syntax.string.toSqlInterpolator

class SalesorderdetailRepoImpl extends SalesorderdetailRepo {
  override def delete: DeleteBuilder[SalesorderdetailFields, SalesorderdetailRow] = DeleteBuilder.of(""""sales"."salesorderdetail"""", SalesorderdetailFields.structure, SalesorderdetailRow.read)

  override def deleteById(compositeId: SalesorderdetailId): ConnectionIO[Boolean] = sql"""delete from "sales"."salesorderdetail" where "salesorderid" = ${fromWrite(compositeId.salesorderid)(using new Write.Single(SalesorderheaderId.put))} AND "salesorderdetailid" = ${fromWrite(compositeId.salesorderdetailid)(using new Write.Single(Meta.IntMeta.put))}""".update.run.map(_ > 0)

  override def deleteByIds(compositeIds: Array[SalesorderdetailId]): ConnectionIO[Int] = {
    val salesorderid = compositeIds.map(_.salesorderid)
    val salesorderdetailid = compositeIds.map(_.salesorderdetailid)
    sql"""delete
    from "sales"."salesorderdetail"
    where ("salesorderid", "salesorderdetailid")
    in (select unnest(${fromWrite(salesorderid)(using new Write.Single(SalesorderheaderId.arrayPut))}), unnest(${fromWrite(salesorderdetailid)(using new Write.Single(adventureworks.IntegerArrayMeta.put))}))
    """.update.run
  }

  override def insert(unsaved: SalesorderdetailRow): ConnectionIO[SalesorderdetailRow] = {
    sql"""insert into "sales"."salesorderdetail"("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate")
    values (${fromWrite(unsaved.salesorderid)(using new Write.Single(SalesorderheaderId.put))}::int4, ${fromWrite(unsaved.salesorderdetailid)(using new Write.Single(Meta.IntMeta.put))}::int4, ${fromWrite(unsaved.carriertrackingnumber)(using new Write.SingleOpt(Meta.StringMeta.put))}, ${fromWrite(unsaved.orderqty)(using new Write.Single(TypoShort.put))}::int2, ${fromWrite(unsaved.productid)(using new Write.Single(ProductId.put))}::int4, ${fromWrite(unsaved.specialofferid)(using new Write.Single(SpecialofferId.put))}::int4, ${fromWrite(unsaved.unitprice)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric, ${fromWrite(unsaved.unitpricediscount)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric, ${fromWrite(unsaved.rowguid)(using new Write.Single(TypoUUID.put))}::uuid, ${fromWrite(unsaved.modifieddate)(using new Write.Single(TypoLocalDateTime.put))}::timestamp)
    returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text
    """.query(using SalesorderdetailRow.read).unique
  }

  override def insert(unsaved: SalesorderdetailRowUnsaved): ConnectionIO[SalesorderdetailRow] = {
    val fs = List(
      Some((Fragment.const0(s""""salesorderid""""), fr"${fromWrite(unsaved.salesorderid)(using new Write.Single(SalesorderheaderId.put))}::int4")),
      Some((Fragment.const0(s""""carriertrackingnumber""""), fr"${fromWrite(unsaved.carriertrackingnumber)(using new Write.SingleOpt(Meta.StringMeta.put))}")),
      Some((Fragment.const0(s""""orderqty""""), fr"${fromWrite(unsaved.orderqty)(using new Write.Single(TypoShort.put))}::int2")),
      Some((Fragment.const0(s""""productid""""), fr"${fromWrite(unsaved.productid)(using new Write.Single(ProductId.put))}::int4")),
      Some((Fragment.const0(s""""specialofferid""""), fr"${fromWrite(unsaved.specialofferid)(using new Write.Single(SpecialofferId.put))}::int4")),
      Some((Fragment.const0(s""""unitprice""""), fr"${fromWrite(unsaved.unitprice)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric")),
      unsaved.salesorderdetailid match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((Fragment.const0(s""""salesorderdetailid""""), fr"${fromWrite(value: Int)(using new Write.Single(Meta.IntMeta.put))}::int4"))
      },
      unsaved.unitpricediscount match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((Fragment.const0(s""""unitpricediscount""""), fr"${fromWrite(value: BigDecimal)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric"))
      },
      unsaved.rowguid match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((Fragment.const0(s""""rowguid""""), fr"${fromWrite(value: TypoUUID)(using new Write.Single(TypoUUID.put))}::uuid"))
      },
      unsaved.modifieddate match {
        case Defaulted.UseDefault() => None
        case Defaulted.Provided(value) => Some((Fragment.const0(s""""modifieddate""""), fr"${fromWrite(value: TypoLocalDateTime)(using new Write.Single(TypoLocalDateTime.put))}::timestamp"))
      }
    ).flatten
    val q = if (fs.isEmpty) {
      sql"""insert into "sales"."salesorderdetail" default values
      returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text
      """
    } else {
      val CommaSeparate = Fragment.FragmentMonoid.intercalate(fr", ")
      sql"""insert into "sales"."salesorderdetail"(${CommaSeparate.combineAllOption(fs.map { case (n, _) => n }).get})
      values (${CommaSeparate.combineAllOption(fs.map { case (_, f) => f }).get})
      returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text
      """
    }
    q.query(using SalesorderdetailRow.read).unique
  }

  override def insertStreaming(
    unsaved: Stream[ConnectionIO, SalesorderdetailRow],
    batchSize: Int = 10000
  ): ConnectionIO[Long] = new FragmentOps(sql"""COPY "sales"."salesorderdetail"("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate") FROM STDIN""").copyIn(unsaved, batchSize)(using SalesorderdetailRow.pgText)

  /** NOTE: this functionality requires PostgreSQL 16 or later! */
  override def insertUnsavedStreaming(
    unsaved: Stream[ConnectionIO, SalesorderdetailRowUnsaved],
    batchSize: Int = 10000
  ): ConnectionIO[Long] = new FragmentOps(sql"""COPY "sales"."salesorderdetail"("salesorderid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "salesorderdetailid", "unitpricediscount", "rowguid", "modifieddate") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""").copyIn(unsaved, batchSize)(using SalesorderdetailRowUnsaved.pgText)

  override def select: SelectBuilder[SalesorderdetailFields, SalesorderdetailRow] = SelectBuilder.of(""""sales"."salesorderdetail"""", SalesorderdetailFields.structure, SalesorderdetailRow.read)

  override def selectAll: Stream[ConnectionIO, SalesorderdetailRow] = sql"""select "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text from "sales"."salesorderdetail"""".query(using SalesorderdetailRow.read).stream

  override def selectById(compositeId: SalesorderdetailId): ConnectionIO[Option[SalesorderdetailRow]] = sql"""select "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text from "sales"."salesorderdetail" where "salesorderid" = ${fromWrite(compositeId.salesorderid)(using new Write.Single(SalesorderheaderId.put))} AND "salesorderdetailid" = ${fromWrite(compositeId.salesorderdetailid)(using new Write.Single(Meta.IntMeta.put))}""".query(using SalesorderdetailRow.read).option

  override def selectByIds(compositeIds: Array[SalesorderdetailId]): Stream[ConnectionIO, SalesorderdetailRow] = {
    val salesorderid = compositeIds.map(_.salesorderid)
    val salesorderdetailid = compositeIds.map(_.salesorderdetailid)
    sql"""select "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text
    from "sales"."salesorderdetail"
    where ("salesorderid", "salesorderdetailid")
    in (select unnest(${fromWrite(salesorderid)(using new Write.Single(SalesorderheaderId.arrayPut))}), unnest(${fromWrite(salesorderdetailid)(using new Write.Single(adventureworks.IntegerArrayMeta.put))}))
    """.query(using SalesorderdetailRow.read).stream
  }

  override def selectByIdsTracked(compositeIds: Array[SalesorderdetailId]): ConnectionIO[Map[SalesorderdetailId, SalesorderdetailRow]] = {
    selectByIds(compositeIds).compile.toList.map { rows =>
      val byId = rows.view.map(x => (x.compositeId, x)).toMap
      compositeIds.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
    }
  }

  override def update: UpdateBuilder[SalesorderdetailFields, SalesorderdetailRow] = UpdateBuilder.of(""""sales"."salesorderdetail"""", SalesorderdetailFields.structure, SalesorderdetailRow.read)

  override def update(row: SalesorderdetailRow): ConnectionIO[Option[SalesorderdetailRow]] = {
    val compositeId = row.compositeId
    sql"""update "sales"."salesorderdetail"
    set "carriertrackingnumber" = ${fromWrite(row.carriertrackingnumber)(using new Write.SingleOpt(Meta.StringMeta.put))},
    "orderqty" = ${fromWrite(row.orderqty)(using new Write.Single(TypoShort.put))}::int2,
    "productid" = ${fromWrite(row.productid)(using new Write.Single(ProductId.put))}::int4,
    "specialofferid" = ${fromWrite(row.specialofferid)(using new Write.Single(SpecialofferId.put))}::int4,
    "unitprice" = ${fromWrite(row.unitprice)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
    "unitpricediscount" = ${fromWrite(row.unitpricediscount)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
    "rowguid" = ${fromWrite(row.rowguid)(using new Write.Single(TypoUUID.put))}::uuid,
    "modifieddate" = ${fromWrite(row.modifieddate)(using new Write.Single(TypoLocalDateTime.put))}::timestamp
    where "salesorderid" = ${fromWrite(compositeId.salesorderid)(using new Write.Single(SalesorderheaderId.put))} AND "salesorderdetailid" = ${fromWrite(compositeId.salesorderdetailid)(using new Write.Single(Meta.IntMeta.put))}
    returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text""".query(using SalesorderdetailRow.read).option
  }

  override def upsert(unsaved: SalesorderdetailRow): ConnectionIO[SalesorderdetailRow] = {
    sql"""insert into "sales"."salesorderdetail"("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate")
    values (
      ${fromWrite(unsaved.salesorderid)(using new Write.Single(SalesorderheaderId.put))}::int4,
    ${fromWrite(unsaved.salesorderdetailid)(using new Write.Single(Meta.IntMeta.put))}::int4,
    ${fromWrite(unsaved.carriertrackingnumber)(using new Write.SingleOpt(Meta.StringMeta.put))},
    ${fromWrite(unsaved.orderqty)(using new Write.Single(TypoShort.put))}::int2,
    ${fromWrite(unsaved.productid)(using new Write.Single(ProductId.put))}::int4,
    ${fromWrite(unsaved.specialofferid)(using new Write.Single(SpecialofferId.put))}::int4,
    ${fromWrite(unsaved.unitprice)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
    ${fromWrite(unsaved.unitpricediscount)(using new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
    ${fromWrite(unsaved.rowguid)(using new Write.Single(TypoUUID.put))}::uuid,
    ${fromWrite(unsaved.modifieddate)(using new Write.Single(TypoLocalDateTime.put))}::timestamp
    )
    on conflict ("salesorderid", "salesorderdetailid")
    do update set
      "carriertrackingnumber" = EXCLUDED."carriertrackingnumber",
    "orderqty" = EXCLUDED."orderqty",
    "productid" = EXCLUDED."productid",
    "specialofferid" = EXCLUDED."specialofferid",
    "unitprice" = EXCLUDED."unitprice",
    "unitpricediscount" = EXCLUDED."unitpricediscount",
    "rowguid" = EXCLUDED."rowguid",
    "modifieddate" = EXCLUDED."modifieddate"
    returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text
    """.query(using SalesorderdetailRow.read).unique
  }

  override def upsertBatch(unsaved: List[SalesorderdetailRow]): Stream[ConnectionIO, SalesorderdetailRow] = {
    Update[SalesorderdetailRow](
      s"""insert into "sales"."salesorderdetail"("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate")
      values (?::int4,?::int4,?,?::int2,?::int4,?::int4,?::numeric,?::numeric,?::uuid,?::timestamp)
      on conflict ("salesorderid", "salesorderdetailid")
      do update set
        "carriertrackingnumber" = EXCLUDED."carriertrackingnumber",
      "orderqty" = EXCLUDED."orderqty",
      "productid" = EXCLUDED."productid",
      "specialofferid" = EXCLUDED."specialofferid",
      "unitprice" = EXCLUDED."unitprice",
      "unitpricediscount" = EXCLUDED."unitpricediscount",
      "rowguid" = EXCLUDED."rowguid",
      "modifieddate" = EXCLUDED."modifieddate"
      returning "salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate"::text"""
    )(using SalesorderdetailRow.write)
    .updateManyWithGeneratedKeys[SalesorderdetailRow]("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate")(unsaved)(using catsStdInstancesForList, SalesorderdetailRow.read)
  }

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override def upsertStreaming(
    unsaved: Stream[ConnectionIO, SalesorderdetailRow],
    batchSize: Int = 10000
  ): ConnectionIO[Int] = {
    for {
      _ <- sql"""create temporary table salesorderdetail_TEMP (like "sales"."salesorderdetail") on commit drop""".update.run
      _ <- new FragmentOps(sql"""copy salesorderdetail_TEMP("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate") from stdin""").copyIn(unsaved, batchSize)(using SalesorderdetailRow.pgText)
      res <- sql"""insert into "sales"."salesorderdetail"("salesorderid", "salesorderdetailid", "carriertrackingnumber", "orderqty", "productid", "specialofferid", "unitprice", "unitpricediscount", "rowguid", "modifieddate")
             select * from salesorderdetail_TEMP
             on conflict ("salesorderid", "salesorderdetailid")
             do update set
               "carriertrackingnumber" = EXCLUDED."carriertrackingnumber",
             "orderqty" = EXCLUDED."orderqty",
             "productid" = EXCLUDED."productid",
             "specialofferid" = EXCLUDED."specialofferid",
             "unitprice" = EXCLUDED."unitprice",
             "unitpricediscount" = EXCLUDED."unitpricediscount",
             "rowguid" = EXCLUDED."rowguid",
             "modifieddate" = EXCLUDED."modifieddate"
             ;
             drop table salesorderdetail_TEMP;""".update.run
    } yield res
  }
}