/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.bec;

import java.sql.Connection;
import java.util.List;
import typr.dsl.SelectBuilder;

public interface BecViewRepo {
  SelectBuilder<BecViewFields, BecViewRow> select();

  List<BecViewRow> selectAll(Connection c);
}
