/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.person.businessentitycontact

import adventureworks.person.businessentity.BusinessentityFields
import adventureworks.person.businessentity.BusinessentityId
import adventureworks.person.businessentity.BusinessentityRow
import adventureworks.person.contacttype.ContacttypeFields
import adventureworks.person.contacttype.ContacttypeId
import adventureworks.person.contacttype.ContacttypeRow
import adventureworks.person.person.PersonFields
import adventureworks.person.person.PersonRow
import java.time.LocalDateTime
import java.util.Optional
import java.util.UUID
import typr.dsl.FieldsExpr0
import typr.dsl.ForeignKey
import typr.dsl.Path
import typr.dsl.RelationStructure
import typr.dsl.SqlExpr
import typr.dsl.SqlExpr.CompositeIn
import typr.dsl.SqlExpr.Field
import typr.dsl.SqlExpr.FieldLike
import typr.dsl.SqlExpr.IdField
import typr.runtime.PgTypes
import typr.runtime.RowParser

trait BusinessentitycontactFields extends FieldsExpr0[BusinessentitycontactRow] {
  def businessentityid: IdField[BusinessentityId, BusinessentitycontactRow]

  def personid: IdField[BusinessentityId, BusinessentitycontactRow]

  def contacttypeid: IdField[ContacttypeId, BusinessentitycontactRow]

  def rowguid: Field[UUID, BusinessentitycontactRow]

  def modifieddate: Field[LocalDateTime, BusinessentitycontactRow]

  def fkBusinessentity: ForeignKey[BusinessentityFields, BusinessentityRow] = ForeignKey.of[BusinessentityFields, BusinessentityRow]("person.FK_BusinessEntityContact_BusinessEntity_BusinessEntityID").withColumnPair[BusinessentityId](businessentityid, _.businessentityid)

  def fkContacttype: ForeignKey[ContacttypeFields, ContacttypeRow] = ForeignKey.of[ContacttypeFields, ContacttypeRow]("person.FK_BusinessEntityContact_ContactType_ContactTypeID").withColumnPair[ContacttypeId](contacttypeid, _.contacttypeid)

  def fkPerson: ForeignKey[PersonFields, PersonRow] = ForeignKey.of[PersonFields, PersonRow]("person.FK_BusinessEntityContact_Person_PersonID").withColumnPair[BusinessentityId](personid, _.businessentityid)

  def compositeIdIs(compositeId: BusinessentitycontactId): SqlExpr[java.lang.Boolean] = SqlExpr.all(businessentityid.isEqual(compositeId.businessentityid), personid.isEqual(compositeId.personid), contacttypeid.isEqual(compositeId.contacttypeid))

  def compositeIdIn(compositeIds: java.util.List[BusinessentitycontactId]): SqlExpr[java.lang.Boolean] = CompositeIn(java.util.List.of(CompositeIn.Part[BusinessentityId, BusinessentitycontactId, BusinessentitycontactRow](businessentityid, _.businessentityid, BusinessentityId.pgType), CompositeIn.Part[BusinessentityId, BusinessentitycontactId, BusinessentitycontactRow](personid, _.personid, BusinessentityId.pgType), CompositeIn.Part[ContacttypeId, BusinessentitycontactId, BusinessentitycontactRow](contacttypeid, _.contacttypeid, ContacttypeId.pgType)), compositeIds)

  override def columns: java.util.List[FieldLike[?, BusinessentitycontactRow]]

  override def rowParser: RowParser[BusinessentitycontactRow] = BusinessentitycontactRow._rowParser
}

object BusinessentitycontactFields {
  case class Impl(val `_path`: java.util.List[Path]) extends BusinessentitycontactFields with RelationStructure[BusinessentitycontactFields, BusinessentitycontactRow] {

    override def businessentityid: IdField[BusinessentityId, BusinessentitycontactRow] = {
      new IdField[BusinessentityId, BusinessentitycontactRow](
        _path,
        "businessentityid",
        _.businessentityid,
        Optional.empty(),
        Optional.of("int4"),
        (row, value) => row.copy(businessentityid = value),
        BusinessentityId.pgType
      )
    }

    override def personid: IdField[BusinessentityId, BusinessentitycontactRow] = {
      new IdField[BusinessentityId, BusinessentitycontactRow](
        _path,
        "personid",
        _.personid,
        Optional.empty(),
        Optional.of("int4"),
        (row, value) => row.copy(personid = value),
        BusinessentityId.pgType
      )
    }

    override def contacttypeid: IdField[ContacttypeId, BusinessentitycontactRow] = {
      new IdField[ContacttypeId, BusinessentitycontactRow](
        _path,
        "contacttypeid",
        _.contacttypeid,
        Optional.empty(),
        Optional.of("int4"),
        (row, value) => row.copy(contacttypeid = value),
        ContacttypeId.pgType
      )
    }

    override def rowguid: Field[UUID, BusinessentitycontactRow] = {
      new Field[UUID, BusinessentitycontactRow](
        _path,
        "rowguid",
        _.rowguid,
        Optional.empty(),
        Optional.of("uuid"),
        (row, value) => row.copy(rowguid = value),
        PgTypes.uuid
      )
    }

    override def modifieddate: Field[LocalDateTime, BusinessentitycontactRow] = {
      new Field[LocalDateTime, BusinessentitycontactRow](
        _path,
        "modifieddate",
        _.modifieddate,
        Optional.empty(),
        Optional.of("timestamp"),
        (row, value) => row.copy(modifieddate = value),
        PgTypes.timestamp
      )
    }

    override def columns: java.util.List[FieldLike[?, BusinessentitycontactRow]] = java.util.List.of(this.businessentityid, this.personid, this.contacttypeid, this.rowguid, this.modifieddate)

    override def withPaths(`_path`: java.util.List[Path]): RelationStructure[BusinessentitycontactFields, BusinessentitycontactRow] = new Impl(`_path`)
  }

  def structure: Impl = new Impl(java.util.Collections.emptyList())
}