/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.precision_types

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime
import java.time.LocalTime
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import testdb.precisetypes.Binary16
import testdb.precisetypes.Binary32
import testdb.precisetypes.Binary64
import testdb.precisetypes.Decimal10_2
import testdb.precisetypes.Decimal12_4
import testdb.precisetypes.Decimal18_4
import testdb.precisetypes.Decimal5_2
import testdb.precisetypes.Decimal8_2
import testdb.precisetypes.LocalDateTime3
import testdb.precisetypes.LocalDateTime6
import testdb.precisetypes.LocalTime3
import testdb.precisetypes.LocalTime6
import testdb.precisetypes.PaddedString10
import testdb.precisetypes.String10
import testdb.precisetypes.String100
import testdb.precisetypes.String20
import testdb.precisetypes.String255
import testdb.precisetypes.String50

/** This class corresponds to a row in table `precision_types` which has not been persisted yet */
case class PrecisionTypesRowUnsaved(
  /**  */
  string10: String10,
  /**  */
  string20: String20,
  /**  */
  string50: String50,
  /**  */
  string100: String100,
  /**  */
  string255: String255,
  /**  */
  char10: PaddedString10,
  /**  */
  @JsonProperty("decimal5_2") decimal52: Decimal5_2,
  /**  */
  @JsonProperty("decimal10_2") decimal102: Decimal10_2,
  /**  */
  @JsonProperty("decimal18_4") decimal184: Decimal18_4,
  /**  */
  @JsonProperty("numeric8_2") numeric82: Decimal8_2,
  /**  */
  @JsonProperty("numeric12_4") numeric124: Decimal12_4,
  /**  */
  binary16: Binary16,
  /**  */
  binary32: Binary32,
  /**  */
  binary64: Binary64,
  /**  */
  time0: LocalTime,
  /**  */
  time3: LocalTime3,
  /**  */
  time6: LocalTime6,
  /**  */
  datetime0: LocalDateTime,
  /**  */
  datetime3: LocalDateTime3,
  /**  */
  datetime6: LocalDateTime6,
  /** Default: current_timestamp()

   */
  ts0: Defaulted[LocalDateTime] = new UseDefault(),
  /** Default: current_timestamp(3)

   */
  ts3: Defaulted[LocalDateTime3] = new UseDefault(),
  /** Default: current_timestamp(6)

   */
  ts6: Defaulted[LocalDateTime6] = new UseDefault()
) {
  def toRow(
    ts0Default: => LocalDateTime,
    ts3Default: => LocalDateTime3,
    ts6Default: => LocalDateTime6,
    idDefault: => PrecisionTypesId
  ): PrecisionTypesRow = {
    new PrecisionTypesRow(
      id = idDefault,
      string10 = string10,
      string20 = string20,
      string50 = string50,
      string100 = string100,
      string255 = string255,
      char10 = char10,
      decimal52 = decimal52,
      decimal102 = decimal102,
      decimal184 = decimal184,
      numeric82 = numeric82,
      numeric124 = numeric124,
      binary16 = binary16,
      binary32 = binary32,
      binary64 = binary64,
      time0 = time0,
      time3 = time3,
      time6 = time6,
      datetime0 = datetime0,
      datetime3 = datetime3,
      datetime6 = datetime6,
      ts0 = ts0.getOrElse(ts0Default),
      ts3 = ts3.getOrElse(ts3Default),
      ts6 = ts6.getOrElse(ts6Default)
    )
  }
}