/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.psc

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.customtypes.TypoUUID
import adventureworks.production.productcategory.ProductcategoryId
import adventureworks.production.productsubcategory.ProductsubcategoryId
import adventureworks.public.Name
import typr.dsl.Path
import typr.dsl.RelationStructure
import typr.dsl.SqlExpr.Field
import typr.dsl.SqlExpr.FieldLike

trait PscViewFields {
  def id: Field[ProductsubcategoryId, PscViewRow]
  def productsubcategoryid: Field[ProductsubcategoryId, PscViewRow]
  def productcategoryid: Field[ProductcategoryId, PscViewRow]
  def name: Field[Name, PscViewRow]
  def rowguid: Field[TypoUUID, PscViewRow]
  def modifieddate: Field[TypoLocalDateTime, PscViewRow]
}

object PscViewFields {
  lazy val structure: RelationStructure[PscViewFields, PscViewRow] =
    new Impl(List())

  private final class Impl(val _path: List[Path])
    extends RelationStructure[PscViewFields, PscViewRow] {

    override lazy val fields: PscViewFields = new PscViewFields {
      override def id = Field[ProductsubcategoryId, PscViewRow](_path, "id", None, None, x => x.id, (row, value) => row.copy(id = value))
      override def productsubcategoryid = Field[ProductsubcategoryId, PscViewRow](_path, "productsubcategoryid", None, None, x => x.productsubcategoryid, (row, value) => row.copy(productsubcategoryid = value))
      override def productcategoryid = Field[ProductcategoryId, PscViewRow](_path, "productcategoryid", None, None, x => x.productcategoryid, (row, value) => row.copy(productcategoryid = value))
      override def name = Field[Name, PscViewRow](_path, "name", None, None, x => x.name, (row, value) => row.copy(name = value))
      override def rowguid = Field[TypoUUID, PscViewRow](_path, "rowguid", None, None, x => x.rowguid, (row, value) => row.copy(rowguid = value))
      override def modifieddate = Field[TypoLocalDateTime, PscViewRow](_path, "modifieddate", Some("text"), None, x => x.modifieddate, (row, value) => row.copy(modifieddate = value))
    }

    override lazy val columns: List[FieldLike[?, PscViewRow]] =
      List[FieldLike[?, PscViewRow]](fields.id, fields.productsubcategoryid, fields.productcategoryid, fields.name, fields.rowguid, fields.modifieddate)

    override def copy(path: List[Path]): Impl =
      new Impl(path)
  }
}
