/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.v_daily_sales

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDate
import java.util.Optional
import typo.runtime.MariaTypes
import typo.runtime.RowParser
import typo.runtime.RowParsers

/** View: v_daily_sales
 * VIEW
 */
case class VDailySalesViewRow(
  /** 
   * Default: NULL
   */
  @JsonProperty("order_date") orderDate: Optional[LocalDate],
  /** 
   * Default: 0
   */
  @JsonProperty("order_count") orderCount: java.lang.Long,
  /** 
   * Default: 0
   */
  @JsonProperty("unique_customers") uniqueCustomers: java.lang.Long,
  /** 
   * Default: NULL
   */
  @JsonProperty("items_sold") itemsSold: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("gross_sales") grossSales: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("total_discounts") totalDiscounts: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("total_shipping") totalShipping: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("total_tax") totalTax: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("net_sales") netSales: Optional[java.math.BigDecimal],
  /** 
   * Default: NULL
   */
  @JsonProperty("avg_order_value") avgOrderValue: Optional[java.math.BigDecimal]
)

object VDailySalesViewRow {
  val `_rowParser`: RowParser[VDailySalesViewRow] = RowParsers.of(MariaTypes.date.opt(), MariaTypes.bigint, MariaTypes.bigint, MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), MariaTypes.decimal.opt(), VDailySalesViewRow.apply, row => Array[Object](row.orderDate.asInstanceOf[Object], row.orderCount.asInstanceOf[Object], row.uniqueCustomers.asInstanceOf[Object], row.itemsSold.asInstanceOf[Object], row.grossSales.asInstanceOf[Object], row.totalDiscounts.asInstanceOf[Object], row.totalShipping.asInstanceOf[Object], row.totalTax.asInstanceOf[Object], row.netSales.asInstanceOf[Object], row.avgOrderValue.asInstanceOf[Object]))
}