/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.humanresources.vjobcandidate

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.humanresources.jobcandidate.JobcandidateId
import adventureworks.person.businessentity.BusinessentityId
import anorm.Column
import anorm.RowParser
import anorm.Success
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

/** View: humanresources.vjobcandidate */
case class VjobcandidateViewRow(
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.jobcandidateid]] */
  jobcandidateid: JobcandidateId,
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.businessentityid]] */
  businessentityid: Option[BusinessentityId],
  namePrefix: /* nullability unknown */ Option[/* max 30 chars */ String],
  nameFirst: /* nullability unknown */ Option[/* max 30 chars */ String],
  nameMiddle: /* nullability unknown */ Option[/* max 30 chars */ String],
  nameLast: /* nullability unknown */ Option[/* max 30 chars */ String],
  nameSuffix: /* nullability unknown */ Option[/* max 30 chars */ String],
  skills: /* nullability unknown */ Option[String],
  addrType: /* nullability unknown */ Option[/* max 30 chars */ String],
  addrLocCountryRegion: /* nullability unknown */ Option[/* max 100 chars */ String],
  addrLocState: /* nullability unknown */ Option[/* max 100 chars */ String],
  addrLocCity: /* nullability unknown */ Option[/* max 100 chars */ String],
  addrPostalCode: /* nullability unknown */ Option[/* max 20 chars */ String],
  eMail: /* nullability unknown */ Option[String],
  webSite: /* nullability unknown */ Option[String],
  /** Points to [[adventureworks.humanresources.jobcandidate.JobcandidateRow.modifieddate]] */
  modifieddate: TypoLocalDateTime
)

object VjobcandidateViewRow {
  given reads: Reads[VjobcandidateViewRow] = {
    Reads[VjobcandidateViewRow](json => JsResult.fromTry(
        Try(
          VjobcandidateViewRow(
            jobcandidateid = json.\("jobcandidateid").as(JobcandidateId.reads),
            businessentityid = json.\("businessentityid").toOption.map(_.as(BusinessentityId.reads)),
            namePrefix = json.\("Name.Prefix").toOption.map(_.as(Reads.StringReads)),
            nameFirst = json.\("Name.First").toOption.map(_.as(Reads.StringReads)),
            nameMiddle = json.\("Name.Middle").toOption.map(_.as(Reads.StringReads)),
            nameLast = json.\("Name.Last").toOption.map(_.as(Reads.StringReads)),
            nameSuffix = json.\("Name.Suffix").toOption.map(_.as(Reads.StringReads)),
            skills = json.\("Skills").toOption.map(_.as(Reads.StringReads)),
            addrType = json.\("Addr.Type").toOption.map(_.as(Reads.StringReads)),
            addrLocCountryRegion = json.\("Addr.Loc.CountryRegion").toOption.map(_.as(Reads.StringReads)),
            addrLocState = json.\("Addr.Loc.State").toOption.map(_.as(Reads.StringReads)),
            addrLocCity = json.\("Addr.Loc.City").toOption.map(_.as(Reads.StringReads)),
            addrPostalCode = json.\("Addr.PostalCode").toOption.map(_.as(Reads.StringReads)),
            eMail = json.\("EMail").toOption.map(_.as(Reads.StringReads)),
            webSite = json.\("WebSite").toOption.map(_.as(Reads.StringReads)),
            modifieddate = json.\("modifieddate").as(TypoLocalDateTime.reads)
          )
        )
      ),
    )
  }

  def rowParser(idx: Int): RowParser[VjobcandidateViewRow] = {
    RowParser[VjobcandidateViewRow] { row =>
      Success(
        VjobcandidateViewRow(
          jobcandidateid = row(idx + 0)(using JobcandidateId.column),
          businessentityid = row(idx + 1)(using Column.columnToOption(using BusinessentityId.column)),
          namePrefix = row(idx + 2)(using Column.columnToOption(using Column.columnToString)),
          nameFirst = row(idx + 3)(using Column.columnToOption(using Column.columnToString)),
          nameMiddle = row(idx + 4)(using Column.columnToOption(using Column.columnToString)),
          nameLast = row(idx + 5)(using Column.columnToOption(using Column.columnToString)),
          nameSuffix = row(idx + 6)(using Column.columnToOption(using Column.columnToString)),
          skills = row(idx + 7)(using Column.columnToOption(using Column.columnToString)),
          addrType = row(idx + 8)(using Column.columnToOption(using Column.columnToString)),
          addrLocCountryRegion = row(idx + 9)(using Column.columnToOption(using Column.columnToString)),
          addrLocState = row(idx + 10)(using Column.columnToOption(using Column.columnToString)),
          addrLocCity = row(idx + 11)(using Column.columnToOption(using Column.columnToString)),
          addrPostalCode = row(idx + 12)(using Column.columnToOption(using Column.columnToString)),
          eMail = row(idx + 13)(using Column.columnToOption(using Column.columnToString)),
          webSite = row(idx + 14)(using Column.columnToOption(using Column.columnToString)),
          modifieddate = row(idx + 15)(using TypoLocalDateTime.column)
        )
      )
    }
  }

  given writes: OWrites[VjobcandidateViewRow] = {
    OWrites[VjobcandidateViewRow](o =>
      new JsObject(ListMap[String, JsValue](
        "jobcandidateid" -> JobcandidateId.writes.writes(o.jobcandidateid),
        "businessentityid" -> Writes.OptionWrites(using BusinessentityId.writes).writes(o.businessentityid),
        "Name.Prefix" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.namePrefix),
        "Name.First" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.nameFirst),
        "Name.Middle" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.nameMiddle),
        "Name.Last" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.nameLast),
        "Name.Suffix" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.nameSuffix),
        "Skills" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.skills),
        "Addr.Type" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.addrType),
        "Addr.Loc.CountryRegion" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.addrLocCountryRegion),
        "Addr.Loc.State" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.addrLocState),
        "Addr.Loc.City" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.addrLocCity),
        "Addr.PostalCode" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.addrPostalCode),
        "EMail" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.eMail),
        "WebSite" -> Writes.OptionWrites(using Writes.StringWrites).writes(o.webSite),
        "modifieddate" -> TypoLocalDateTime.writes.writes(o.modifieddate)
      ))
    )
  }
}