/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.customers

import java.sql.Connection
import java.util.ArrayList
import java.util.HashMap
import java.util.Optional
import testdb.customer_status.CustomerStatusId
import typo.dsl.DeleteBuilder
import typo.dsl.Dialect
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import typo.runtime.Fragment
import typo.runtime.Fragment.Literal
import typo.runtime.MariaTypes
import typo.runtime.FragmentInterpolator.interpolate

class CustomersRepoImpl extends CustomersRepo {
  override def delete: DeleteBuilder[CustomersFields, CustomersRow] = DeleteBuilder.of("`customers`", CustomersFields.structure, Dialect.MARIADB)

  override def deleteById(customerId: CustomersId)(using c: Connection): java.lang.Boolean = interpolate"delete from `customers` where `customer_id` = ${CustomersId.pgType.encode(customerId)}".update().runUnchecked(c) > 0

  override def deleteByIds(customerIds: Array[CustomersId])(using c: Connection): Integer = {
    val fragments: ArrayList[Fragment] = new ArrayList[Fragment]()
    customerIds.foreach { id => fragments.add(CustomersId.pgType.encode(id)) }
    return Fragment.interpolate(Fragment.lit("delete from `customers` where `customer_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).update().runUnchecked(c)
  }

  override def insert(unsaved: CustomersRow)(using c: Connection): CustomersRow = {
  interpolate"""insert into `customers`(`email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`)
    values (${MariaTypes.text.encode(unsaved.email)}, ${MariaTypes.blob.encode(unsaved.passwordHash)}, ${MariaTypes.text.encode(unsaved.firstName)}, ${MariaTypes.text.encode(unsaved.lastName)}, ${MariaTypes.text.opt().encode(unsaved.phone)}, ${CustomerStatusId.pgType.encode(unsaved.status)}, ${MariaTypes.text.encode(unsaved.tier)}, ${MariaTypes.text.opt().encode(unsaved.preferences)}, ${MariaTypes.set.opt().encode(unsaved.marketingFlags)}, ${MariaTypes.text.opt().encode(unsaved.notes)}, ${MariaTypes.datetime.encode(unsaved.createdAt)}, ${MariaTypes.datetime.encode(unsaved.updatedAt)}, ${MariaTypes.datetime.opt().encode(unsaved.lastLoginAt)})
    returning `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`
    """
    .updateReturning(CustomersRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  override def insert(unsaved: CustomersRowUnsaved)(using c: Connection): CustomersRow = {
    val columns: ArrayList[Literal] = new ArrayList[Literal]()
    val values: ArrayList[Fragment] = new ArrayList[Fragment]()
    columns.add(Fragment.lit("`email`")): @scala.annotation.nowarn
    values.add(interpolate"${MariaTypes.text.encode(unsaved.email)}"): @scala.annotation.nowarn
    columns.add(Fragment.lit("`password_hash`")): @scala.annotation.nowarn
    values.add(interpolate"${MariaTypes.blob.encode(unsaved.passwordHash)}"): @scala.annotation.nowarn
    columns.add(Fragment.lit("`first_name`")): @scala.annotation.nowarn
    values.add(interpolate"${MariaTypes.text.encode(unsaved.firstName)}"): @scala.annotation.nowarn
    columns.add(Fragment.lit("`last_name`")): @scala.annotation.nowarn
    values.add(interpolate"${MariaTypes.text.encode(unsaved.lastName)}"): @scala.annotation.nowarn
    unsaved.phone.visit(
      {  },
      value => { columns.add(Fragment.lit("`phone`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.text.opt().encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.status.visit(
      {  },
      value => { columns.add(Fragment.lit("`status`")): @scala.annotation.nowarn; values.add(interpolate"${CustomerStatusId.pgType.encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.tier.visit(
      {  },
      value => { columns.add(Fragment.lit("`tier`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.text.encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.preferences.visit(
      {  },
      value => { columns.add(Fragment.lit("`preferences`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.text.opt().encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.marketingFlags.visit(
      {  },
      value => { columns.add(Fragment.lit("`marketing_flags`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.set.opt().encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.notes.visit(
      {  },
      value => { columns.add(Fragment.lit("`notes`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.text.opt().encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.createdAt.visit(
      {  },
      value => { columns.add(Fragment.lit("`created_at`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.datetime.encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.updatedAt.visit(
      {  },
      value => { columns.add(Fragment.lit("`updated_at`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.datetime.encode(value)}"): @scala.annotation.nowarn }
    );
    unsaved.lastLoginAt.visit(
      {  },
      value => { columns.add(Fragment.lit("`last_login_at`")): @scala.annotation.nowarn; values.add(interpolate"${MariaTypes.datetime.opt().encode(value)}"): @scala.annotation.nowarn }
    );
    val q: Fragment = {
      interpolate"""insert into `customers`(${Fragment.comma(columns)})
      values (${Fragment.comma(values)})
      returning `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`
      """
    }
    return q.updateReturning(CustomersRow.`_rowParser`.exactlyOne()).runUnchecked(c)
  }

  override def select: SelectBuilder[CustomersFields, CustomersRow] = SelectBuilder.of("`customers`", CustomersFields.structure, CustomersRow.`_rowParser`, Dialect.MARIADB)

  override def selectAll(using c: Connection): java.util.List[CustomersRow] = {
    interpolate"""select `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`
    from `customers`
    """.query(CustomersRow.`_rowParser`.all()).runUnchecked(c)
  }

  override def selectById(customerId: CustomersId)(using c: Connection): Optional[CustomersRow] = {
    interpolate"""select `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`
    from `customers`
    where `customer_id` = ${CustomersId.pgType.encode(customerId)}""".query(CustomersRow.`_rowParser`.first()).runUnchecked(c)
  }

  override def selectByIds(customerIds: Array[CustomersId])(using c: Connection): java.util.List[CustomersRow] = {
    val fragments: ArrayList[Fragment] = new ArrayList[Fragment]()
    customerIds.foreach { id => fragments.add(CustomersId.pgType.encode(id)) }
    return Fragment.interpolate(Fragment.lit("select `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at` from `customers` where `customer_id` in ("), Fragment.comma(fragments), Fragment.lit(")")).query(CustomersRow.`_rowParser`.all()).runUnchecked(c)
  }

  override def selectByIdsTracked(customerIds: Array[CustomersId])(using c: Connection): java.util.Map[CustomersId, CustomersRow] = {
    val ret: HashMap[CustomersId, CustomersRow] = new HashMap[CustomersId, CustomersRow]()
    selectByIds(customerIds)(using c).forEach(row => ret.put(row.customerId, row): @scala.annotation.nowarn)
    return ret
  }

  override def selectByUniqueEmail(email: String)(using c: Connection): Optional[CustomersRow] = {
    interpolate"""select `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`
    from `customers`
    where `email` = ${MariaTypes.text.encode(email)}
    """.query(CustomersRow.`_rowParser`.first()).runUnchecked(c)
  }

  override def update: UpdateBuilder[CustomersFields, CustomersRow] = UpdateBuilder.of("`customers`", CustomersFields.structure, CustomersRow.`_rowParser`.all(), Dialect.MARIADB)

  override def update(row: CustomersRow)(using c: Connection): java.lang.Boolean = {
    val customerId: CustomersId = row.customerId
    return interpolate"""update `customers`
    set `email` = ${MariaTypes.text.encode(row.email)},
    `password_hash` = ${MariaTypes.blob.encode(row.passwordHash)},
    `first_name` = ${MariaTypes.text.encode(row.firstName)},
    `last_name` = ${MariaTypes.text.encode(row.lastName)},
    `phone` = ${MariaTypes.text.opt().encode(row.phone)},
    `status` = ${CustomerStatusId.pgType.encode(row.status)},
    `tier` = ${MariaTypes.text.encode(row.tier)},
    `preferences` = ${MariaTypes.text.opt().encode(row.preferences)},
    `marketing_flags` = ${MariaTypes.set.opt().encode(row.marketingFlags)},
    `notes` = ${MariaTypes.text.opt().encode(row.notes)},
    `created_at` = ${MariaTypes.datetime.encode(row.createdAt)},
    `updated_at` = ${MariaTypes.datetime.encode(row.updatedAt)},
    `last_login_at` = ${MariaTypes.datetime.opt().encode(row.lastLoginAt)}
    where `customer_id` = ${CustomersId.pgType.encode(customerId)}""".update().runUnchecked(c) > 0
  }

  override def upsert(unsaved: CustomersRow)(using c: Connection): CustomersRow = {
  interpolate"""INSERT INTO `customers`(`email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`)
    VALUES (${MariaTypes.text.encode(unsaved.email)}, ${MariaTypes.blob.encode(unsaved.passwordHash)}, ${MariaTypes.text.encode(unsaved.firstName)}, ${MariaTypes.text.encode(unsaved.lastName)}, ${MariaTypes.text.opt().encode(unsaved.phone)}, ${CustomerStatusId.pgType.encode(unsaved.status)}, ${MariaTypes.text.encode(unsaved.tier)}, ${MariaTypes.text.opt().encode(unsaved.preferences)}, ${MariaTypes.set.opt().encode(unsaved.marketingFlags)}, ${MariaTypes.text.opt().encode(unsaved.notes)}, ${MariaTypes.datetime.encode(unsaved.createdAt)}, ${MariaTypes.datetime.encode(unsaved.updatedAt)}, ${MariaTypes.datetime.opt().encode(unsaved.lastLoginAt)})
    ON DUPLICATE KEY UPDATE `email` = VALUES(`email`),
    `password_hash` = VALUES(`password_hash`),
    `first_name` = VALUES(`first_name`),
    `last_name` = VALUES(`last_name`),
    `phone` = VALUES(`phone`),
    `status` = VALUES(`status`),
    `tier` = VALUES(`tier`),
    `preferences` = VALUES(`preferences`),
    `marketing_flags` = VALUES(`marketing_flags`),
    `notes` = VALUES(`notes`),
    `created_at` = VALUES(`created_at`),
    `updated_at` = VALUES(`updated_at`),
    `last_login_at` = VALUES(`last_login_at`)
    RETURNING `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`"""
    .updateReturning(CustomersRow.`_rowParser`.exactlyOne())
    .runUnchecked(c)
  }

  override def upsertBatch(unsaved: java.util.Iterator[CustomersRow])(using c: Connection): java.util.List[CustomersRow] = {
    interpolate"""INSERT INTO `customers`(`customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE `email` = VALUES(`email`),
    `password_hash` = VALUES(`password_hash`),
    `first_name` = VALUES(`first_name`),
    `last_name` = VALUES(`last_name`),
    `phone` = VALUES(`phone`),
    `status` = VALUES(`status`),
    `tier` = VALUES(`tier`),
    `preferences` = VALUES(`preferences`),
    `marketing_flags` = VALUES(`marketing_flags`),
    `notes` = VALUES(`notes`),
    `created_at` = VALUES(`created_at`),
    `updated_at` = VALUES(`updated_at`),
    `last_login_at` = VALUES(`last_login_at`)
    RETURNING `customer_id`, `email`, `password_hash`, `first_name`, `last_name`, `phone`, `status`, `tier`, `preferences`, `marketing_flags`, `notes`, `created_at`, `updated_at`, `last_login_at`"""
      .updateReturningEach(CustomersRow.`_rowParser`, unsaved)
      .runUnchecked(c)
  }
}