/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb

import dev.typr.foundations.data.Json
import dev.typr.foundations.data.Uint1
import dev.typr.foundations.data.Uint2
import dev.typr.foundations.data.Uint4
import dev.typr.foundations.data.Uint8
import dev.typr.foundations.data.maria.Inet4
import dev.typr.foundations.data.maria.Inet6
import java.lang.Math
import java.sql.Connection
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.Year
import org.mariadb.jdbc.`type`.Geometry
import org.mariadb.jdbc.`type`.GeometryCollection
import org.mariadb.jdbc.`type`.LineString
import org.mariadb.jdbc.`type`.MultiLineString
import org.mariadb.jdbc.`type`.MultiPoint
import org.mariadb.jdbc.`type`.MultiPolygon
import org.mariadb.jdbc.`type`.Point
import org.mariadb.jdbc.`type`.Polygon
import scala.util.Random
import testdb.audit_log.AuditLogRepoImpl
import testdb.audit_log.AuditLogRow
import testdb.audit_log.AuditLogRowUnsaved
import testdb.brands.BrandsId
import testdb.brands.BrandsRepoImpl
import testdb.brands.BrandsRow
import testdb.brands.BrandsRowUnsaved
import testdb.categories.CategoriesId
import testdb.categories.CategoriesRepoImpl
import testdb.categories.CategoriesRow
import testdb.categories.CategoriesRowUnsaved
import testdb.customer_addresses.CustomerAddressesId
import testdb.customer_addresses.CustomerAddressesRepoImpl
import testdb.customer_addresses.CustomerAddressesRow
import testdb.customer_addresses.CustomerAddressesRowUnsaved
import testdb.customer_status.CustomerStatusId
import testdb.customer_status.CustomerStatusRepoImpl
import testdb.customer_status.CustomerStatusRow
import testdb.customer_status.CustomerStatusRowUnsaved
import testdb.customers.CustomersId
import testdb.customers.CustomersRepoImpl
import testdb.customers.CustomersRow
import testdb.customers.CustomersRowUnsaved
import testdb.customtypes.Defaulted
import testdb.customtypes.Defaulted.UseDefault
import testdb.inventory.InventoryRepoImpl
import testdb.inventory.InventoryRow
import testdb.inventory.InventoryRowUnsaved
import testdb.mariatest.MariatestId
import testdb.mariatest.MariatestRepoImpl
import testdb.mariatest.MariatestRow
import testdb.mariatest.MariatestRowUnsaved
import testdb.mariatest_identity.MariatestIdentityRepoImpl
import testdb.mariatest_identity.MariatestIdentityRow
import testdb.mariatest_identity.MariatestIdentityRowUnsaved
import testdb.mariatest_spatial.MariatestSpatialRepoImpl
import testdb.mariatest_spatial.MariatestSpatialRow
import testdb.mariatest_spatial.MariatestSpatialRowUnsaved
import testdb.mariatest_spatial_null.MariatestSpatialNullRepoImpl
import testdb.mariatest_spatial_null.MariatestSpatialNullRow
import testdb.mariatest_spatial_null.MariatestSpatialNullRowUnsaved
import testdb.mariatest_unique.MariatestUniqueRepoImpl
import testdb.mariatest_unique.MariatestUniqueRow
import testdb.mariatest_unique.MariatestUniqueRowUnsaved
import testdb.mariatestnull.MariatestnullRepoImpl
import testdb.mariatestnull.MariatestnullRow
import testdb.mariatestnull.MariatestnullRowUnsaved
import testdb.order_history.OrderHistoryRepoImpl
import testdb.order_history.OrderHistoryRow
import testdb.order_history.OrderHistoryRowUnsaved
import testdb.order_items.OrderItemsId
import testdb.order_items.OrderItemsRepoImpl
import testdb.order_items.OrderItemsRow
import testdb.order_items.OrderItemsRowUnsaved
import testdb.orders.OrdersId
import testdb.orders.OrdersRepoImpl
import testdb.orders.OrdersRow
import testdb.orders.OrdersRowUnsaved
import testdb.payment_methods.PaymentMethodsId
import testdb.payment_methods.PaymentMethodsRepoImpl
import testdb.payment_methods.PaymentMethodsRow
import testdb.payment_methods.PaymentMethodsRowUnsaved
import testdb.payments.PaymentsRepoImpl
import testdb.payments.PaymentsRow
import testdb.payments.PaymentsRowUnsaved
import testdb.precisetypes.Binary16
import testdb.precisetypes.Binary32
import testdb.precisetypes.Binary64
import testdb.precisetypes.Decimal10_2
import testdb.precisetypes.Decimal12_4
import testdb.precisetypes.Decimal18_4
import testdb.precisetypes.Decimal5_2
import testdb.precisetypes.Decimal8_2
import testdb.precisetypes.LocalDateTime3
import testdb.precisetypes.LocalDateTime6
import testdb.precisetypes.LocalTime3
import testdb.precisetypes.LocalTime6
import testdb.precisetypes.PaddedString10
import testdb.precisetypes.String10
import testdb.precisetypes.String100
import testdb.precisetypes.String20
import testdb.precisetypes.String255
import testdb.precisetypes.String50
import testdb.precision_types.PrecisionTypesRepoImpl
import testdb.precision_types.PrecisionTypesRow
import testdb.precision_types.PrecisionTypesRowUnsaved
import testdb.precision_types_null.PrecisionTypesNullRepoImpl
import testdb.precision_types_null.PrecisionTypesNullRow
import testdb.precision_types_null.PrecisionTypesNullRowUnsaved
import testdb.price_tiers.PriceTiersId
import testdb.price_tiers.PriceTiersRepoImpl
import testdb.price_tiers.PriceTiersRow
import testdb.price_tiers.PriceTiersRowUnsaved
import testdb.product_categories.ProductCategoriesRepoImpl
import testdb.product_categories.ProductCategoriesRow
import testdb.product_categories.ProductCategoriesRowUnsaved
import testdb.product_images.ProductImagesRepoImpl
import testdb.product_images.ProductImagesRow
import testdb.product_images.ProductImagesRowUnsaved
import testdb.product_prices.ProductPricesRepoImpl
import testdb.product_prices.ProductPricesRow
import testdb.product_prices.ProductPricesRowUnsaved
import testdb.products.ProductsId
import testdb.products.ProductsRepoImpl
import testdb.products.ProductsRow
import testdb.products.ProductsRowUnsaved
import testdb.promotions.PromotionsId
import testdb.promotions.PromotionsRepoImpl
import testdb.promotions.PromotionsRow
import testdb.promotions.PromotionsRowUnsaved
import testdb.reviews.ReviewsRepoImpl
import testdb.reviews.ReviewsRow
import testdb.reviews.ReviewsRowUnsaved
import testdb.shipments.ShipmentsRepoImpl
import testdb.shipments.ShipmentsRow
import testdb.shipments.ShipmentsRowUnsaved
import testdb.shipping_carriers.ShippingCarriersId
import testdb.shipping_carriers.ShippingCarriersRepoImpl
import testdb.shipping_carriers.ShippingCarriersRow
import testdb.shipping_carriers.ShippingCarriersRowUnsaved
import testdb.warehouses.WarehousesId
import testdb.warehouses.WarehousesRepoImpl
import testdb.warehouses.WarehousesRow
import testdb.warehouses.WarehousesRowUnsaved

/** Methods to generate random data for `Ident(TestInsert)` */
case class TestInsert(random: Random) {
  def AuditLog(
    tableName: String = random.alphanumeric.take(20).mkString,
    recordId: String = random.alphanumeric.take(20).mkString,
    action: String = random.alphanumeric.take(20).mkString,
    oldValues: Defaulted[Option[Json]] = new UseDefault(),
    newValues: Defaulted[Option[Json]] = new UseDefault(),
    changedBy: Defaulted[Option[String]] = new UseDefault(),
    changedAt: Defaulted[LocalDateTime] = new UseDefault(),
    clientIp: Defaulted[Option[Inet6]] = new UseDefault(),
    sessionId: Defaulted[Option[Array[Byte]]] = new UseDefault()
  )(using c: Connection): AuditLogRow = {
    (new AuditLogRepoImpl()).insert(new AuditLogRowUnsaved(
      tableName = tableName,
      recordId = recordId,
      action = action,
      oldValues = oldValues,
      newValues = newValues,
      changedBy = changedBy,
      changedAt = changedAt,
      clientIp = clientIp,
      sessionId = sessionId
    ))(using c)
  }

  def Brands(
    name: String = random.alphanumeric.take(20).mkString,
    slug: String = random.alphanumeric.take(20).mkString,
    logoBlob: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    websiteUrl: Defaulted[Option[String]] = new UseDefault(),
    countryOfOrigin: Defaulted[Option[String]] = new UseDefault(),
    isActive: Defaulted[Boolean] = new UseDefault()
  )(using c: Connection): BrandsRow = {
    (new BrandsRepoImpl()).insert(new BrandsRowUnsaved(
      name = name,
      slug = slug,
      logoBlob = logoBlob,
      websiteUrl = websiteUrl,
      countryOfOrigin = countryOfOrigin,
      isActive = isActive
    ))(using c)
  }

  def Categories(
    name: String = random.alphanumeric.take(20).mkString,
    slug: String = random.alphanumeric.take(20).mkString,
    parentId: Defaulted[Option[CategoriesId]] = new UseDefault(),
    description: Defaulted[Option[String]] = new UseDefault(),
    imageUrl: Defaulted[Option[String]] = new UseDefault(),
    sortOrder: Defaulted[Short] = new UseDefault(),
    isVisible: Defaulted[Boolean] = new UseDefault(),
    metadata: Defaulted[Option[Json]] = new UseDefault()
  )(using c: Connection): CategoriesRow = {
    (new CategoriesRepoImpl()).insert(new CategoriesRowUnsaved(
      name = name,
      slug = slug,
      parentId = parentId,
      description = description,
      imageUrl = imageUrl,
      sortOrder = sortOrder,
      isVisible = isVisible,
      metadata = metadata
    ))(using c)
  }

  def CustomerAddresses(
    customerId: CustomersId,
    addressType: String = random.alphanumeric.take(20).mkString,
    recipientName: String = random.alphanumeric.take(20).mkString,
    streetLine1: String = random.alphanumeric.take(20).mkString,
    city: String = random.alphanumeric.take(20).mkString,
    postalCode: String = random.alphanumeric.take(20).mkString,
    countryCode: String = random.alphanumeric.take(2).mkString,
    isDefault: Defaulted[Boolean] = new UseDefault(),
    streetLine2: Defaulted[Option[String]] = new UseDefault(),
    stateProvince: Defaulted[Option[String]] = new UseDefault(),
    location: Defaulted[Option[Point]] = new UseDefault(),
    deliveryNotes: Defaulted[Option[String]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): CustomerAddressesRow = {
    (new CustomerAddressesRepoImpl()).insert(new CustomerAddressesRowUnsaved(
      customerId = customerId,
      addressType = addressType,
      recipientName = recipientName,
      streetLine1 = streetLine1,
      city = city,
      postalCode = postalCode,
      countryCode = countryCode,
      isDefault = isDefault,
      streetLine2 = streetLine2,
      stateProvince = stateProvince,
      location = location,
      deliveryNotes = deliveryNotes,
      createdAt = createdAt
    ))(using c)
  }

  def CustomerStatus(
    statusCode: CustomerStatusId = new CustomerStatusId(random.alphanumeric.take(20).mkString),
    description: String = random.alphanumeric.take(20).mkString,
    isActive: Defaulted[Boolean] = new UseDefault()
  )(using c: Connection): CustomerStatusRow = (new CustomerStatusRepoImpl()).insert(new CustomerStatusRowUnsaved(statusCode = statusCode, description = description, isActive = isActive))(using c)

  def Customers(
    passwordHash: Array[Byte],
    email: String = random.alphanumeric.take(20).mkString,
    firstName: String = random.alphanumeric.take(20).mkString,
    lastName: String = random.alphanumeric.take(20).mkString,
    phone: Defaulted[Option[String]] = new UseDefault(),
    status: Defaulted[CustomerStatusId] = new UseDefault(),
    tier: Defaulted[String] = new UseDefault(),
    preferences: Defaulted[Option[Json]] = new UseDefault(),
    marketingFlags: Defaulted[Option[EmailMailPushSmsSet]] = new UseDefault(),
    notes: Defaulted[Option[String]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault(),
    updatedAt: Defaulted[LocalDateTime] = new UseDefault(),
    lastLoginAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
  )(using c: Connection): CustomersRow = {
    (new CustomersRepoImpl()).insert(new CustomersRowUnsaved(
      email = email,
      passwordHash = passwordHash,
      firstName = firstName,
      lastName = lastName,
      phone = phone,
      status = status,
      tier = tier,
      preferences = preferences,
      marketingFlags = marketingFlags,
      notes = notes,
      createdAt = createdAt,
      updatedAt = updatedAt,
      lastLoginAt = lastLoginAt
    ))(using c)
  }

  def Inventory(
    productId: ProductsId,
    warehouseId: WarehousesId,
    quantityOnHand: Defaulted[Int] = new UseDefault(),
    quantityReserved: Defaulted[Int] = new UseDefault(),
    quantityOnOrder: Defaulted[Int] = new UseDefault(),
    reorderPoint: Defaulted[Int] = new UseDefault(),
    reorderQuantity: Defaulted[Int] = new UseDefault(),
    binLocation: Defaulted[Option[String]] = new UseDefault(),
    lastCountedAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    updatedAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): InventoryRow = {
    (new InventoryRepoImpl()).insert(new InventoryRowUnsaved(
      productId = productId,
      warehouseId = warehouseId,
      quantityOnHand = quantityOnHand,
      quantityReserved = quantityReserved,
      quantityOnOrder = quantityOnOrder,
      reorderPoint = reorderPoint,
      reorderQuantity = reorderQuantity,
      binLocation = binLocation,
      lastCountedAt = lastCountedAt,
      updatedAt = updatedAt
    ))(using c)
  }

  def Mariatest(
    bitCol: Array[Byte],
    bit1Col: Array[Byte],
    binaryCol: Array[Byte],
    varbinaryCol: Array[Byte],
    tinyblobCol: Array[Byte],
    blobCol: Array[Byte],
    mediumblobCol: Array[Byte],
    longblobCol: Array[Byte],
    yearCol: Year,
    inet4Col: Inet4,
    inet6Col: Inet6,
    tinyintCol: Byte = random.nextInt(Byte.MaxValue).toByte,
    smallintCol: Short = random.nextInt(Short.MaxValue).toShort,
    mediumintCol: Int = random.nextInt(8388607),
    intCol: MariatestId = new MariatestId(random.nextInt()),
    bigintCol: Long = random.nextLong(),
    tinyintUCol: Uint1 = Uint1.of(random.nextInt(256)),
    smallintUCol: Uint2 = Uint2.of(random.nextInt(65536)),
    mediumintUCol: Uint4 = Uint4.of(random.nextInt(16777216).toLong),
    intUCol: Uint4 = Uint4.of(Math.abs(random.nextInt()).toLong),
    bigintUCol: Uint8 = Uint8.of(Math.abs(random.nextLong())),
    decimalCol: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    numericCol: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    floatCol: Float = random.nextFloat(),
    doubleCol: Double = random.nextDouble(),
    boolCol: Boolean = random.nextBoolean(),
    charCol: String = random.alphanumeric.take(10).mkString,
    varcharCol: String = random.alphanumeric.take(20).mkString,
    tinytextCol: String = random.alphanumeric.take(20).mkString,
    textCol: String = random.alphanumeric.take(20).mkString,
    mediumtextCol: String = random.alphanumeric.take(20).mkString,
    longtextCol: String = random.alphanumeric.take(20).mkString,
    dateCol: LocalDate = LocalDate.ofEpochDay(random.nextInt(30000).toLong),
    timeCol: LocalTime = LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong),
    timeFspCol: LocalTime = LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong),
    datetimeCol: LocalDateTime = LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    datetimeFspCol: LocalDateTime = LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    setCol: XYZSet = XYZSet.of(List(XYZSetMember.x)),
    jsonCol: Json = new Json("{}"),
    timestampCol: Defaulted[LocalDateTime] = new UseDefault(),
    timestampFspCol: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): MariatestRow = {
    (new MariatestRepoImpl()).insert(new MariatestRowUnsaved(
      tinyintCol = tinyintCol,
      smallintCol = smallintCol,
      mediumintCol = mediumintCol,
      intCol = intCol,
      bigintCol = bigintCol,
      tinyintUCol = tinyintUCol,
      smallintUCol = smallintUCol,
      mediumintUCol = mediumintUCol,
      intUCol = intUCol,
      bigintUCol = bigintUCol,
      decimalCol = decimalCol,
      numericCol = numericCol,
      floatCol = floatCol,
      doubleCol = doubleCol,
      boolCol = boolCol,
      bitCol = bitCol,
      bit1Col = bit1Col,
      charCol = charCol,
      varcharCol = varcharCol,
      tinytextCol = tinytextCol,
      textCol = textCol,
      mediumtextCol = mediumtextCol,
      longtextCol = longtextCol,
      binaryCol = binaryCol,
      varbinaryCol = varbinaryCol,
      tinyblobCol = tinyblobCol,
      blobCol = blobCol,
      mediumblobCol = mediumblobCol,
      longblobCol = longblobCol,
      dateCol = dateCol,
      timeCol = timeCol,
      timeFspCol = timeFspCol,
      datetimeCol = datetimeCol,
      datetimeFspCol = datetimeFspCol,
      yearCol = yearCol,
      setCol = setCol,
      jsonCol = jsonCol,
      inet4Col = inet4Col,
      inet6Col = inet6Col,
      timestampCol = timestampCol,
      timestampFspCol = timestampFspCol
    ))(using c)
  }

  def MariatestIdentity(name: String = random.alphanumeric.take(20).mkString)(using c: Connection): MariatestIdentityRow = (new MariatestIdentityRepoImpl()).insert(new MariatestIdentityRowUnsaved(name = name))(using c)

  def MariatestSpatial(
    geometryCol: Geometry,
    pointCol: Point,
    linestringCol: LineString,
    polygonCol: Polygon,
    multipointCol: MultiPoint,
    multilinestringCol: MultiLineString,
    multipolygonCol: MultiPolygon,
    geometrycollectionCol: GeometryCollection
  )(using c: Connection): MariatestSpatialRow = {
    (new MariatestSpatialRepoImpl()).insert(new MariatestSpatialRowUnsaved(
      geometryCol = geometryCol,
      pointCol = pointCol,
      linestringCol = linestringCol,
      polygonCol = polygonCol,
      multipointCol = multipointCol,
      multilinestringCol = multilinestringCol,
      multipolygonCol = multipolygonCol,
      geometrycollectionCol = geometrycollectionCol
    ))(using c)
  }

  def MariatestSpatialNull(
    geometryCol: Defaulted[Option[Geometry]] = new UseDefault(),
    pointCol: Defaulted[Option[Point]] = new UseDefault(),
    linestringCol: Defaulted[Option[LineString]] = new UseDefault(),
    polygonCol: Defaulted[Option[Polygon]] = new UseDefault(),
    multipointCol: Defaulted[Option[MultiPoint]] = new UseDefault(),
    multilinestringCol: Defaulted[Option[MultiLineString]] = new UseDefault(),
    multipolygonCol: Defaulted[Option[MultiPolygon]] = new UseDefault(),
    geometrycollectionCol: Defaulted[Option[GeometryCollection]] = new UseDefault()
  )(using c: Connection): MariatestSpatialNullRow = {
    (new MariatestSpatialNullRepoImpl()).insert(new MariatestSpatialNullRowUnsaved(
      geometryCol = geometryCol,
      pointCol = pointCol,
      linestringCol = linestringCol,
      polygonCol = polygonCol,
      multipointCol = multipointCol,
      multilinestringCol = multilinestringCol,
      multipolygonCol = multipolygonCol,
      geometrycollectionCol = geometrycollectionCol
    ))(using c)
  }

  def MariatestUnique(
    email: String = random.alphanumeric.take(20).mkString,
    code: String = random.alphanumeric.take(20).mkString,
    category: String = random.alphanumeric.take(20).mkString
  )(using c: Connection): MariatestUniqueRow = (new MariatestUniqueRepoImpl()).insert(new MariatestUniqueRowUnsaved(email = email, code = code, category = category))(using c)

  def Mariatestnull(
    tinyintCol: Defaulted[Option[Byte]] = new UseDefault(),
    smallintCol: Defaulted[Option[Short]] = new UseDefault(),
    mediumintCol: Defaulted[Option[Int]] = new UseDefault(),
    intCol: Defaulted[Option[Int]] = new UseDefault(),
    bigintCol: Defaulted[Option[Long]] = new UseDefault(),
    tinyintUCol: Defaulted[Option[Uint1]] = new UseDefault(),
    smallintUCol: Defaulted[Option[Uint2]] = new UseDefault(),
    mediumintUCol: Defaulted[Option[Uint4]] = new UseDefault(),
    intUCol: Defaulted[Option[Uint4]] = new UseDefault(),
    bigintUCol: Defaulted[Option[Uint8]] = new UseDefault(),
    decimalCol: Defaulted[Option[BigDecimal]] = new UseDefault(),
    numericCol: Defaulted[Option[BigDecimal]] = new UseDefault(),
    floatCol: Defaulted[Option[Float]] = new UseDefault(),
    doubleCol: Defaulted[Option[Double]] = new UseDefault(),
    boolCol: Defaulted[Option[Boolean]] = new UseDefault(),
    bitCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    bit1Col: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    charCol: Defaulted[Option[String]] = new UseDefault(),
    varcharCol: Defaulted[Option[String]] = new UseDefault(),
    tinytextCol: Defaulted[Option[String]] = new UseDefault(),
    textCol: Defaulted[Option[String]] = new UseDefault(),
    mediumtextCol: Defaulted[Option[String]] = new UseDefault(),
    longtextCol: Defaulted[Option[String]] = new UseDefault(),
    binaryCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    varbinaryCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    tinyblobCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    blobCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    mediumblobCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    longblobCol: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    dateCol: Defaulted[Option[LocalDate]] = new UseDefault(),
    timeCol: Defaulted[Option[LocalTime]] = new UseDefault(),
    timeFspCol: Defaulted[Option[LocalTime]] = new UseDefault(),
    datetimeCol: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    datetimeFspCol: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    timestampCol: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    timestampFspCol: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    yearCol: Defaulted[Option[Year]] = new UseDefault(),
    setCol: Defaulted[Option[XYZSet]] = new UseDefault(),
    jsonCol: Defaulted[Option[Json]] = new UseDefault(),
    inet4Col: Defaulted[Option[Inet4]] = new UseDefault(),
    inet6Col: Defaulted[Option[Inet6]] = new UseDefault()
  )(using c: Connection): MariatestnullRow = {
    (new MariatestnullRepoImpl()).insert(new MariatestnullRowUnsaved(
      tinyintCol = tinyintCol,
      smallintCol = smallintCol,
      mediumintCol = mediumintCol,
      intCol = intCol,
      bigintCol = bigintCol,
      tinyintUCol = tinyintUCol,
      smallintUCol = smallintUCol,
      mediumintUCol = mediumintUCol,
      intUCol = intUCol,
      bigintUCol = bigintUCol,
      decimalCol = decimalCol,
      numericCol = numericCol,
      floatCol = floatCol,
      doubleCol = doubleCol,
      boolCol = boolCol,
      bitCol = bitCol,
      bit1Col = bit1Col,
      charCol = charCol,
      varcharCol = varcharCol,
      tinytextCol = tinytextCol,
      textCol = textCol,
      mediumtextCol = mediumtextCol,
      longtextCol = longtextCol,
      binaryCol = binaryCol,
      varbinaryCol = varbinaryCol,
      tinyblobCol = tinyblobCol,
      blobCol = blobCol,
      mediumblobCol = mediumblobCol,
      longblobCol = longblobCol,
      dateCol = dateCol,
      timeCol = timeCol,
      timeFspCol = timeFspCol,
      datetimeCol = datetimeCol,
      datetimeFspCol = datetimeFspCol,
      timestampCol = timestampCol,
      timestampFspCol = timestampFspCol,
      yearCol = yearCol,
      setCol = setCol,
      jsonCol = jsonCol,
      inet4Col = inet4Col,
      inet6Col = inet6Col
    ))(using c)
  }

  def OrderHistory(
    orderId: OrdersId,
    newStatus: String = random.alphanumeric.take(20).mkString,
    previousStatus: Defaulted[Option[String]] = new UseDefault(),
    changedBy: Defaulted[Option[String]] = new UseDefault(),
    changeReason: Defaulted[Option[String]] = new UseDefault(),
    metadata: Defaulted[Option[Json]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): OrderHistoryRow = {
    (new OrderHistoryRepoImpl()).insert(new OrderHistoryRowUnsaved(
      orderId = orderId,
      newStatus = newStatus,
      previousStatus = previousStatus,
      changedBy = changedBy,
      changeReason = changeReason,
      metadata = metadata,
      createdAt = createdAt
    ))(using c)
  }

  def OrderItems(
    orderId: OrdersId,
    productId: ProductsId,
    sku: String = random.alphanumeric.take(20).mkString,
    productName: String = random.alphanumeric.take(20).mkString,
    quantity: Uint2 = Uint2.of(random.nextInt(65536)),
    unitPrice: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    lineTotal: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    discountAmount: Defaulted[BigDecimal] = new UseDefault(),
    taxAmount: Defaulted[BigDecimal] = new UseDefault(),
    fulfillmentStatus: Defaulted[String] = new UseDefault(),
    warehouseId: Defaulted[Option[WarehousesId]] = new UseDefault(),
    notes: Defaulted[Option[String]] = new UseDefault()
  )(using c: Connection): OrderItemsRow = {
    (new OrderItemsRepoImpl()).insert(new OrderItemsRowUnsaved(
      orderId = orderId,
      productId = productId,
      sku = sku,
      productName = productName,
      quantity = quantity,
      unitPrice = unitPrice,
      lineTotal = lineTotal,
      discountAmount = discountAmount,
      taxAmount = taxAmount,
      fulfillmentStatus = fulfillmentStatus,
      warehouseId = warehouseId,
      notes = notes
    ))(using c)
  }

  def Orders(
    customerId: CustomersId,
    orderNumber: String = random.alphanumeric.take(20).mkString,
    subtotal: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    totalAmount: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    orderStatus: Defaulted[String] = new UseDefault(),
    paymentStatus: Defaulted[String] = new UseDefault(),
    shippingAddressId: Defaulted[Option[CustomerAddressesId]] = new UseDefault(),
    billingAddressId: Defaulted[Option[CustomerAddressesId]] = new UseDefault(),
    shippingCost: Defaulted[BigDecimal] = new UseDefault(),
    taxAmount: Defaulted[BigDecimal] = new UseDefault(),
    discountAmount: Defaulted[BigDecimal] = new UseDefault(),
    currencyCode: Defaulted[String] = new UseDefault(),
    promotionId: Defaulted[Option[PromotionsId]] = new UseDefault(),
    notes: Defaulted[Option[String]] = new UseDefault(),
    internalNotes: Defaulted[Option[String]] = new UseDefault(),
    ipAddress: Defaulted[Option[Inet6]] = new UseDefault(),
    userAgent: Defaulted[Option[String]] = new UseDefault(),
    orderedAt: Defaulted[LocalDateTime] = new UseDefault(),
    confirmedAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    shippedAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    deliveredAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
  )(using c: Connection): OrdersRow = {
    (new OrdersRepoImpl()).insert(new OrdersRowUnsaved(
      orderNumber = orderNumber,
      customerId = customerId,
      subtotal = subtotal,
      totalAmount = totalAmount,
      orderStatus = orderStatus,
      paymentStatus = paymentStatus,
      shippingAddressId = shippingAddressId,
      billingAddressId = billingAddressId,
      shippingCost = shippingCost,
      taxAmount = taxAmount,
      discountAmount = discountAmount,
      currencyCode = currencyCode,
      promotionId = promotionId,
      notes = notes,
      internalNotes = internalNotes,
      ipAddress = ipAddress,
      userAgent = userAgent,
      orderedAt = orderedAt,
      confirmedAt = confirmedAt,
      shippedAt = shippedAt,
      deliveredAt = deliveredAt
    ))(using c)
  }

  def PaymentMethods(
    code: String = random.alphanumeric.take(20).mkString,
    name: String = random.alphanumeric.take(20).mkString,
    methodType: String = random.alphanumeric.take(20).mkString,
    processorConfig: Defaulted[Option[Json]] = new UseDefault(),
    isActive: Defaulted[Boolean] = new UseDefault(),
    sortOrder: Defaulted[Byte] = new UseDefault()
  )(using c: Connection): PaymentMethodsRow = {
    (new PaymentMethodsRepoImpl()).insert(new PaymentMethodsRowUnsaved(
      code = code,
      name = name,
      methodType = methodType,
      processorConfig = processorConfig,
      isActive = isActive,
      sortOrder = sortOrder
    ))(using c)
  }

  def Payments(
    orderId: OrdersId,
    methodId: PaymentMethodsId,
    amount: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    transactionId: Defaulted[Option[String]] = new UseDefault(),
    currencyCode: Defaulted[String] = new UseDefault(),
    status: Defaulted[String] = new UseDefault(),
    processorResponse: Defaulted[Option[Json]] = new UseDefault(),
    errorMessage: Defaulted[Option[String]] = new UseDefault(),
    ipAddress: Defaulted[Option[Inet6]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault(),
    processedAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
  )(using c: Connection): PaymentsRow = {
    (new PaymentsRepoImpl()).insert(new PaymentsRowUnsaved(
      orderId = orderId,
      methodId = methodId,
      amount = amount,
      transactionId = transactionId,
      currencyCode = currencyCode,
      status = status,
      processorResponse = processorResponse,
      errorMessage = errorMessage,
      ipAddress = ipAddress,
      createdAt = createdAt,
      processedAt = processedAt
    ))(using c)
  }

  def PrecisionTypes(
    char10: PaddedString10,
    string10: String10 = String10.truncate(random.alphanumeric.take(10).mkString),
    string20: String20 = String20.truncate(random.alphanumeric.take(20).mkString),
    string50: String50 = String50.truncate(random.alphanumeric.take(20).mkString),
    string100: String100 = String100.truncate(random.alphanumeric.take(20).mkString),
    string255: String255 = String255.truncate(random.alphanumeric.take(20).mkString),
    decimal52: Decimal5_2 = Decimal5_2.unsafeForce(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 1000.toLong).add(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 100.toLong).movePointLeft(2))),
    decimal102: Decimal10_2 = Decimal10_2.unsafeForce(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 1000000.toLong).add(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 100.toLong).movePointLeft(2))),
    decimal184: Decimal18_4 = Decimal18_4.unsafeForce(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 1000000.toLong).add(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 10000.toLong).movePointLeft(4))),
    numeric82: Decimal8_2 = Decimal8_2.unsafeForce(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 1000000.toLong).add(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 100.toLong).movePointLeft(2))),
    numeric124: Decimal12_4 = Decimal12_4.unsafeForce(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 1000000.toLong).add(java.math.BigDecimal.valueOf(Math.abs(random.nextInt()) % 10000.toLong).movePointLeft(4))),
    binary16: Binary16 = Binary16.unsafeForce({val bs = Array.ofDim[Byte](16); random.nextBytes(bs); bs}),
    binary32: Binary32 = Binary32.unsafeForce({val bs = Array.ofDim[Byte](32); random.nextBytes(bs); bs}),
    binary64: Binary64 = Binary64.unsafeForce({val bs = Array.ofDim[Byte](64); random.nextBytes(bs); bs}),
    time0: LocalTime = LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong),
    time3: LocalTime3 = LocalTime3.of(LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    time6: LocalTime6 = LocalTime6.of(LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    datetime0: LocalDateTime = LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    datetime3: LocalDateTime3 = LocalDateTime3.of(LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong))),
    datetime6: LocalDateTime6 = LocalDateTime6.of(LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong))),
    ts0: Defaulted[LocalDateTime] = new UseDefault(),
    ts3: Defaulted[LocalDateTime3] = new UseDefault(),
    ts6: Defaulted[LocalDateTime6] = new UseDefault()
  )(using c: Connection): PrecisionTypesRow = {
    (new PrecisionTypesRepoImpl()).insert(new PrecisionTypesRowUnsaved(
      string10 = string10,
      string20 = string20,
      string50 = string50,
      string100 = string100,
      string255 = string255,
      char10 = char10,
      decimal52 = decimal52,
      decimal102 = decimal102,
      decimal184 = decimal184,
      numeric82 = numeric82,
      numeric124 = numeric124,
      binary16 = binary16,
      binary32 = binary32,
      binary64 = binary64,
      time0 = time0,
      time3 = time3,
      time6 = time6,
      datetime0 = datetime0,
      datetime3 = datetime3,
      datetime6 = datetime6,
      ts0 = ts0,
      ts3 = ts3,
      ts6 = ts6
    ))(using c)
  }

  def PrecisionTypesNull(
    string10: Defaulted[Option[String10]] = new UseDefault(),
    string20: Defaulted[Option[String20]] = new UseDefault(),
    string50: Defaulted[Option[String50]] = new UseDefault(),
    string100: Defaulted[Option[String100]] = new UseDefault(),
    string255: Defaulted[Option[String255]] = new UseDefault(),
    char10: Defaulted[Option[PaddedString10]] = new UseDefault(),
    decimal52: Defaulted[Option[Decimal5_2]] = new UseDefault(),
    decimal102: Defaulted[Option[Decimal10_2]] = new UseDefault(),
    decimal184: Defaulted[Option[Decimal18_4]] = new UseDefault(),
    numeric82: Defaulted[Option[Decimal8_2]] = new UseDefault(),
    numeric124: Defaulted[Option[Decimal12_4]] = new UseDefault(),
    binary16: Defaulted[Option[Binary16]] = new UseDefault(),
    binary32: Defaulted[Option[Binary32]] = new UseDefault(),
    binary64: Defaulted[Option[Binary64]] = new UseDefault(),
    time0: Defaulted[Option[LocalTime]] = new UseDefault(),
    time3: Defaulted[Option[LocalTime3]] = new UseDefault(),
    time6: Defaulted[Option[LocalTime6]] = new UseDefault(),
    datetime0: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    datetime3: Defaulted[Option[LocalDateTime3]] = new UseDefault(),
    datetime6: Defaulted[Option[LocalDateTime6]] = new UseDefault(),
    ts0: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    ts3: Defaulted[Option[LocalDateTime3]] = new UseDefault(),
    ts6: Defaulted[Option[LocalDateTime6]] = new UseDefault()
  )(using c: Connection): PrecisionTypesNullRow = {
    (new PrecisionTypesNullRepoImpl()).insert(new PrecisionTypesNullRowUnsaved(
      string10 = string10,
      string20 = string20,
      string50 = string50,
      string100 = string100,
      string255 = string255,
      char10 = char10,
      decimal52 = decimal52,
      decimal102 = decimal102,
      decimal184 = decimal184,
      numeric82 = numeric82,
      numeric124 = numeric124,
      binary16 = binary16,
      binary32 = binary32,
      binary64 = binary64,
      time0 = time0,
      time3 = time3,
      time6 = time6,
      datetime0 = datetime0,
      datetime3 = datetime3,
      datetime6 = datetime6,
      ts0 = ts0,
      ts3 = ts3,
      ts6 = ts6
    ))(using c)
  }

  def PriceTiers(
    name: String = random.alphanumeric.take(20).mkString,
    discountType: String = random.alphanumeric.take(20).mkString,
    discountValue: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    minQuantity: Defaulted[Uint4] = new UseDefault()
  )(using c: Connection): PriceTiersRow = {
    (new PriceTiersRepoImpl()).insert(new PriceTiersRowUnsaved(
      name = name,
      discountType = discountType,
      discountValue = discountValue,
      minQuantity = minQuantity
    ))(using c)
  }

  def ProductCategories(
    productId: ProductsId,
    categoryId: CategoriesId,
    isPrimary: Defaulted[Boolean] = new UseDefault(),
    sortOrder: Defaulted[Short] = new UseDefault()
  )(using c: Connection): ProductCategoriesRow = {
    (new ProductCategoriesRepoImpl()).insert(new ProductCategoriesRowUnsaved(
      productId = productId,
      categoryId = categoryId,
      isPrimary = isPrimary,
      sortOrder = sortOrder
    ))(using c)
  }

  def ProductImages(
    productId: ProductsId,
    imageUrl: String = random.alphanumeric.take(20).mkString,
    thumbnailUrl: Defaulted[Option[String]] = new UseDefault(),
    altText: Defaulted[Option[String]] = new UseDefault(),
    sortOrder: Defaulted[Uint1] = new UseDefault(),
    isPrimary: Defaulted[Boolean] = new UseDefault(),
    imageData: Defaulted[Option[Array[Byte]]] = new UseDefault()
  )(using c: Connection): ProductImagesRow = {
    (new ProductImagesRepoImpl()).insert(new ProductImagesRowUnsaved(
      productId = productId,
      imageUrl = imageUrl,
      thumbnailUrl = thumbnailUrl,
      altText = altText,
      sortOrder = sortOrder,
      isPrimary = isPrimary,
      imageData = imageData
    ))(using c)
  }

  def ProductPrices(
    productId: ProductsId,
    price: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    validFrom: LocalDate = LocalDate.ofEpochDay(random.nextInt(30000).toLong),
    tierId: Defaulted[Option[PriceTiersId]] = new UseDefault(),
    currencyCode: Defaulted[String] = new UseDefault(),
    validTo: Defaulted[Option[LocalDate]] = new UseDefault()
  )(using c: Connection): ProductPricesRow = {
    (new ProductPricesRepoImpl()).insert(new ProductPricesRowUnsaved(
      productId = productId,
      price = price,
      validFrom = validFrom,
      tierId = tierId,
      currencyCode = currencyCode,
      validTo = validTo
    ))(using c)
  }

  def Products(
    sku: String = random.alphanumeric.take(20).mkString,
    name: String = random.alphanumeric.take(20).mkString,
    basePrice: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    brandId: Defaulted[Option[BrandsId]] = new UseDefault(),
    shortDescription: Defaulted[Option[String]] = new UseDefault(),
    fullDescription: Defaulted[Option[String]] = new UseDefault(),
    costPrice: Defaulted[Option[BigDecimal]] = new UseDefault(),
    weightKg: Defaulted[Option[BigDecimal]] = new UseDefault(),
    dimensionsJson: Defaulted[Option[Json]] = new UseDefault(),
    status: Defaulted[String] = new UseDefault(),
    taxClass: Defaulted[String] = new UseDefault(),
    tags: Defaulted[Option[BestsellerClearanceFSet]] = new UseDefault(),
    attributes: Defaulted[Option[Json]] = new UseDefault(),
    seoMetadata: Defaulted[Option[Json]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault(),
    updatedAt: Defaulted[LocalDateTime] = new UseDefault(),
    publishedAt: Defaulted[Option[LocalDateTime]] = new UseDefault()
  )(using c: Connection): ProductsRow = {
    (new ProductsRepoImpl()).insert(new ProductsRowUnsaved(
      sku = sku,
      name = name,
      basePrice = basePrice,
      brandId = brandId,
      shortDescription = shortDescription,
      fullDescription = fullDescription,
      costPrice = costPrice,
      weightKg = weightKg,
      dimensionsJson = dimensionsJson,
      status = status,
      taxClass = taxClass,
      tags = tags,
      attributes = attributes,
      seoMetadata = seoMetadata,
      createdAt = createdAt,
      updatedAt = updatedAt,
      publishedAt = publishedAt
    ))(using c)
  }

  def Promotions(
    code: String = random.alphanumeric.take(20).mkString,
    name: String = random.alphanumeric.take(20).mkString,
    discountType: String = random.alphanumeric.take(20).mkString,
    discountValue: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    validFrom: LocalDateTime = LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    validTo: LocalDateTime = LocalDateTime.of(LocalDate.ofEpochDay(random.nextInt(30000).toLong), LocalTime.ofSecondOfDay(random.nextInt(24 * 60 * 60).toLong)),
    description: Defaulted[Option[String]] = new UseDefault(),
    minOrderAmount: Defaulted[Option[BigDecimal]] = new UseDefault(),
    maxUses: Defaulted[Option[Uint4]] = new UseDefault(),
    usesCount: Defaulted[Uint4] = new UseDefault(),
    maxUsesPerCustomer: Defaulted[Option[Uint1]] = new UseDefault(),
    applicableTo: Defaulted[Option[AllBrandsCategoriesCSet]] = new UseDefault(),
    rulesJson: Defaulted[Option[Json]] = new UseDefault(),
    isActive: Defaulted[Boolean] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): PromotionsRow = {
    (new PromotionsRepoImpl()).insert(new PromotionsRowUnsaved(
      code = code,
      name = name,
      discountType = discountType,
      discountValue = discountValue,
      validFrom = validFrom,
      validTo = validTo,
      description = description,
      minOrderAmount = minOrderAmount,
      maxUses = maxUses,
      usesCount = usesCount,
      maxUsesPerCustomer = maxUsesPerCustomer,
      applicableTo = applicableTo,
      rulesJson = rulesJson,
      isActive = isActive,
      createdAt = createdAt
    ))(using c)
  }

  def Reviews(
    productId: ProductsId,
    customerId: CustomersId,
    rating: Uint1 = Uint1.of(random.nextInt(256)),
    orderItemId: Defaulted[Option[OrderItemsId]] = new UseDefault(),
    title: Defaulted[Option[String]] = new UseDefault(),
    content: Defaulted[Option[String]] = new UseDefault(),
    pros: Defaulted[Option[Json]] = new UseDefault(),
    cons: Defaulted[Option[Json]] = new UseDefault(),
    images: Defaulted[Option[Json]] = new UseDefault(),
    isVerifiedPurchase: Defaulted[Boolean] = new UseDefault(),
    isApproved: Defaulted[Boolean] = new UseDefault(),
    helpfulVotes: Defaulted[Uint4] = new UseDefault(),
    unhelpfulVotes: Defaulted[Uint4] = new UseDefault(),
    adminResponse: Defaulted[Option[String]] = new UseDefault(),
    respondedAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault(),
    updatedAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): ReviewsRow = {
    (new ReviewsRepoImpl()).insert(new ReviewsRowUnsaved(
      productId = productId,
      customerId = customerId,
      rating = rating,
      orderItemId = orderItemId,
      title = title,
      content = content,
      pros = pros,
      cons = cons,
      images = images,
      isVerifiedPurchase = isVerifiedPurchase,
      isApproved = isApproved,
      helpfulVotes = helpfulVotes,
      unhelpfulVotes = unhelpfulVotes,
      adminResponse = adminResponse,
      respondedAt = respondedAt,
      createdAt = createdAt,
      updatedAt = updatedAt
    ))(using c)
  }

  def Shipments(
    orderId: OrdersId,
    carrierId: ShippingCarriersId,
    shippingMethod: String = random.alphanumeric.take(20).mkString,
    shippingCost: BigDecimal = BigDecimal.decimal(random.nextDouble()),
    trackingNumber: Defaulted[Option[String]] = new UseDefault(),
    weightKg: Defaulted[Option[BigDecimal]] = new UseDefault(),
    dimensionsJson: Defaulted[Option[Json]] = new UseDefault(),
    labelData: Defaulted[Option[Array[Byte]]] = new UseDefault(),
    status: Defaulted[String] = new UseDefault(),
    estimatedDeliveryDate: Defaulted[Option[LocalDate]] = new UseDefault(),
    actualDeliveryAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    insuranceAmount: Defaulted[Option[BigDecimal]] = new UseDefault(),
    originWarehouseId: Defaulted[Option[WarehousesId]] = new UseDefault(),
    shippedAt: Defaulted[Option[LocalDateTime]] = new UseDefault(),
    createdAt: Defaulted[LocalDateTime] = new UseDefault(),
    updatedAt: Defaulted[LocalDateTime] = new UseDefault()
  )(using c: Connection): ShipmentsRow = {
    (new ShipmentsRepoImpl()).insert(new ShipmentsRowUnsaved(
      orderId = orderId,
      carrierId = carrierId,
      shippingMethod = shippingMethod,
      shippingCost = shippingCost,
      trackingNumber = trackingNumber,
      weightKg = weightKg,
      dimensionsJson = dimensionsJson,
      labelData = labelData,
      status = status,
      estimatedDeliveryDate = estimatedDeliveryDate,
      actualDeliveryAt = actualDeliveryAt,
      insuranceAmount = insuranceAmount,
      originWarehouseId = originWarehouseId,
      shippedAt = shippedAt,
      createdAt = createdAt,
      updatedAt = updatedAt
    ))(using c)
  }

  def ShippingCarriers(
    code: String = random.alphanumeric.take(20).mkString,
    name: String = random.alphanumeric.take(20).mkString,
    trackingUrlTemplate: Defaulted[Option[String]] = new UseDefault(),
    apiConfig: Defaulted[Option[Json]] = new UseDefault(),
    isActive: Defaulted[Boolean] = new UseDefault()
  )(using c: Connection): ShippingCarriersRow = {
    (new ShippingCarriersRepoImpl()).insert(new ShippingCarriersRowUnsaved(
      code = code,
      name = name,
      trackingUrlTemplate = trackingUrlTemplate,
      apiConfig = apiConfig,
      isActive = isActive
    ))(using c)
  }

  def Warehouses(
    location: Point,
    code: String = random.alphanumeric.take(5).mkString,
    name: String = random.alphanumeric.take(20).mkString,
    address: String = random.alphanumeric.take(20).mkString,
    serviceArea: Defaulted[Option[Polygon]] = new UseDefault(),
    timezone: Defaulted[String] = new UseDefault(),
    isActive: Defaulted[Boolean] = new UseDefault(),
    contactEmail: Defaulted[Option[String]] = new UseDefault(),
    contactPhone: Defaulted[Option[String]] = new UseDefault()
  )(using c: Connection): WarehousesRow = {
    (new WarehousesRepoImpl()).insert(new WarehousesRowUnsaved(
      code = code,
      name = name,
      address = address,
      location = location,
      serviceArea = serviceArea,
      timezone = timezone,
      isActive = isActive,
      contactEmail = contactEmail,
      contactPhone = contactPhone
    ))(using c)
  }
}