/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package testdb.find_customers_by_email

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime
import testdb.customers.CustomersId
import typo.kotlindsl.RowParser
import typo.kotlindsl.RowParsers
import typo.kotlindsl.nullable
import typo.runtime.SqlServerTypes

/** SQL file: find-customers-by-email.sql */
data class FindCustomersByEmailSqlRow(
  /** Points to [testdb.customers.CustomersRow.customerId] */
  @JsonProperty("customer_id") val customerId: CustomersId,
  /** Points to [testdb.customers.CustomersRow.name] */
  @JsonProperty("customer_name") val customerName: String,
  /** Points to [testdb.customers.CustomersRow.email] */
  @JsonProperty("customer_email") val customerEmail: String,
  /** Points to [testdb.customers.CustomersRow.createdAt] */
  @JsonProperty("created_at") val createdAt: LocalDateTime?
) {
  companion object {
    val _rowParser: RowParser<FindCustomersByEmailSqlRow> = RowParsers.of(CustomersId.sqlServerType, SqlServerTypes.nvarchar, SqlServerTypes.nvarchar, SqlServerTypes.datetime2.nullable(), { t0, t1, t2, t3 -> FindCustomersByEmailSqlRow(t0, t1, t2, t3) }, { row -> arrayOf<Any?>(row.customerId, row.customerName, row.customerEmail, row.createdAt) })
  }
}