/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public.issue142

import java.sql.Connection
import typr.scaladsl.DeleteBuilder
import typr.scaladsl.SelectBuilder
import typr.scaladsl.UpdateBuilder

trait Issue142Repo {
  def delete: DeleteBuilder[Issue142Fields, Issue142Row]

  def deleteById(tabellkode: Issue142Id)(using c: Connection): Boolean

  def deleteByIds(tabellkodes: Array[Issue142Id])(using c: Connection): Int

  def insert(unsaved: Issue142Row)(using c: Connection): Issue142Row

  def insertStreaming(
    unsaved: Iterator[Issue142Row],
    batchSize: Int = 10000
  )(using c: Connection): Long

  def select: SelectBuilder[Issue142Fields, Issue142Row]

  def selectAll(using c: Connection): List[Issue142Row]

  def selectById(tabellkode: Issue142Id)(using c: Connection): Option[Issue142Row]

  def selectByIds(tabellkodes: Array[Issue142Id])(using c: Connection): List[Issue142Row]

  def selectByIdsTracked(tabellkodes: Array[Issue142Id])(using c: Connection): Map[Issue142Id, Issue142Row]

  def update: UpdateBuilder[Issue142Fields, Issue142Row]

  def upsert(unsaved: Issue142Row)(using c: Connection): Issue142Row

  def upsertBatch(unsaved: Iterator[Issue142Row])(using c: Connection): List[Issue142Row]

  /** NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(
    unsaved: Iterator[Issue142Row],
    batchSize: Int = 10000
  )(using c: Connection): Int
}