package typo

object TypesScala {
  val Any = jvm.Type.Qualified("scala.Any")
  val AnyRef = jvm.Type.Qualified("scala.AnyRef")
  val AnyVal = jvm.Type.Qualified("scala.AnyVal")
  val Array = jvm.Type.Qualified("scala.Array")
  val BigDecimal = jvm.Type.Qualified("scala.math.BigDecimal")
  val Boolean = jvm.Type.Qualified("scala.Boolean")
  val Byte = jvm.Type.Qualified("scala.Byte")
  val Char = jvm.Type.Qualified("scala.Char")
  val Double = jvm.Type.Qualified("scala.Double")
  val Either = jvm.Type.Qualified("scala.Either")
  val Float = jvm.Type.Qualified("scala.Float")
  val Function1 = jvm.Type.Qualified("scala.Function1")
  val Int = jvm.Type.Qualified("scala.Int")
  val Iterable = jvm.Type.Qualified("scala.collection.Iterable")
  val Iterator = jvm.Type.Qualified("scala.collection.Iterator")
  val Left = jvm.Type.Qualified("scala.Left")
  val List = jvm.Type.Qualified("scala.List")
  val ListMap = jvm.Type.Qualified("scala.collection.immutable.ListMap")
  val Long = jvm.Type.Qualified("scala.Long")
  val Map = jvm.Type.Qualified("scala.collection.immutable.Map")
  val Nil = jvm.Type.Qualified("scala.collection.immutable.Nil")
  val None = jvm.Type.Qualified("scala.None")
  val Numeric = jvm.Type.Qualified("scala.math.Numeric")
  val Option = jvm.Type.Qualified("scala.Option")
  val Random = jvm.Type.Qualified("scala.util.Random")
  val Right = jvm.Type.Qualified("scala.Right")
  val Short = jvm.Type.Qualified("scala.Short")
  val Some = jvm.Type.Qualified("scala.Some")
  val StringContext = jvm.Type.Qualified("scala.StringContext")
  val Try = jvm.Type.Qualified("scala.util.Try")
  val Unit = jvm.Type.Qualified("scala.Unit")
  val mutableMap = jvm.Type.Qualified("scala.collection.mutable.Map")
  val nowarn = jvm.Type.Qualified("scala.annotation.nowarn")
  val CollectionConverters = jvm.Type.Qualified("scala.jdk.CollectionConverters")

  def boxedType(tpe: jvm.Type): Option[jvm.Type.Qualified] =
    tpe match {
      case Int                               => scala.Some(TypesJava.Integer)
      case Long                              => scala.Some(TypesJava.Long)
      case Float                             => scala.Some(TypesJava.Float)
      case Double                            => scala.Some(TypesJava.Double)
      case Boolean                           => scala.Some(TypesJava.Boolean)
      case Short                             => scala.Some(TypesJava.Short)
      case Byte                              => scala.Some(TypesJava.Byte)
      case Char                              => scala.Some(TypesJava.Character)
      case jvm.Type.Commented(underlying, _) => boxedType(underlying)
      case jvm.Type.Annotated(underlying, _) => boxedType(underlying)
      case jvm.Type.UserDefined(underlying)  => boxedType(underlying)
      case _                                 => scala.None
    }
}
