/**
 * File has been automatically generated by `typo`.
 *
 * <p>IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.pcc;

import java.sql.Connection;
import java.util.List;
import typo.dsl.SelectBuilder;

public interface PccViewRepo {
  SelectBuilder<PccViewFields, PccViewRow> select();

  List<PccViewRow> selectAll(Connection c);
}
