/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.shoppingcartitem

import com.fasterxml.jackson.annotation.JsonValue
import typo.dsl.Bijection
import typo.runtime.PgType
import typo.runtime.PgTypes
import typo.runtime.internal.arrayMap

/** Type for the primary key of table `sales.shoppingcartitem` */
data class ShoppingcartitemId(@JsonValue val value: Int) {
  override fun toString(): kotlin.String {
    return value.toString()
  }

  companion object {
    val bijection: Bijection<ShoppingcartitemId, Int> =
      Bijection.of(ShoppingcartitemId::value, ::ShoppingcartitemId)

    val pgType: PgType<ShoppingcartitemId> =
      PgTypes.int4.bimap(::ShoppingcartitemId, ShoppingcartitemId::value)

    val pgTypeArray: PgType<Array<ShoppingcartitemId>> =
      PgTypes.int4Array.bimap({ xs -> arrayMap.map(xs, ::ShoppingcartitemId, ShoppingcartitemId::class.java) }, { xs -> arrayMap.map(xs, ShoppingcartitemId::value, Int::class.javaObjectType) })
  }
}