/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_;

import dev.typr.foundations.PgRead;
import dev.typr.foundations.PgStruct;
import dev.typr.foundations.PgType;
import dev.typr.foundations.PgTypes;
import java.util.Optional;

/** PostgreSQL composite type: public.tablefunc_crosstab_4 */
public record TablefuncCrosstab4(
  Optional<String> rowName,
  Optional<String> category1,
  Optional<String> category2,
  Optional<String> category3,
  Optional<String> category4
) {
  public TablefuncCrosstab4 withRowName(Optional<String> rowName) {
    return new TablefuncCrosstab4(rowName, category1, category2, category3, category4);
  };

  public TablefuncCrosstab4 withCategory1(Optional<String> category1) {
    return new TablefuncCrosstab4(rowName, category1, category2, category3, category4);
  };

  public TablefuncCrosstab4 withCategory2(Optional<String> category2) {
    return new TablefuncCrosstab4(rowName, category1, category2, category3, category4);
  };

  public TablefuncCrosstab4 withCategory3(Optional<String> category3) {
    return new TablefuncCrosstab4(rowName, category1, category2, category3, category4);
  };

  public TablefuncCrosstab4 withCategory4(Optional<String> category4) {
    return new TablefuncCrosstab4(rowName, category1, category2, category3, category4);
  };

  static public PgStruct<TablefuncCrosstab4> pgStruct =
    PgStruct.<TablefuncCrosstab4>builder("public.tablefunc_crosstab_4").optField("rowName", PgTypes.text, v -> v.rowName()).optField("category1", PgTypes.text, v -> v.category1()).optField("category2", PgTypes.text, v -> v.category2()).optField("category3", PgTypes.text, v -> v.category3()).optField("category4", PgTypes.text, v -> v.category4()).build(arr -> new TablefuncCrosstab4(Optional.ofNullable((String) arr[0]), Optional.ofNullable((String) arr[1]), Optional.ofNullable((String) arr[2]), Optional.ofNullable((String) arr[3]), Optional.ofNullable((String) arr[4])));

  static public PgType<TablefuncCrosstab4> pgType =
    pgStruct.asType();

  static public PgType<TablefuncCrosstab4[]> pgTypeArray =
    pgType.array(PgRead.readCompositeArray(pgType.pgCompositeText(), TablefuncCrosstab4[]::new), TablefuncCrosstab4[]::new);
}