/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pr.sr

import adventureworks.production.scrapreason.ScrapreasonId
import adventureworks.public.Name
import java.time.LocalDateTime
import kotlin.collections.List
import typr.dsl.FieldsExpr
import typr.dsl.Path
import typr.dsl.SqlExpr.FieldLike
import typr.kotlindsl.RelationStructure
import typr.kotlindsl.SqlExpr.Field
import typr.runtime.PgTypes
import typr.runtime.RowParser

interface SrViewFields : FieldsExpr<SrViewRow> {
  abstract override fun columns(): List<FieldLike<*, SrViewRow>>

  abstract fun id(): Field<ScrapreasonId, SrViewRow>

  abstract fun modifieddate(): Field<LocalDateTime, SrViewRow>

  abstract fun name(): Field<Name, SrViewRow>

  override fun rowParser(): RowParser<SrViewRow> = SrViewRow._rowParser.underlying

  abstract fun scrapreasonid(): Field<ScrapreasonId, SrViewRow>

  companion object {
    data class Impl(val _path: List<Path>) : SrViewFields, RelationStructure<SrViewFields, SrViewRow> {
      override fun id(): Field<ScrapreasonId, SrViewRow> = Field<ScrapreasonId, SrViewRow>(_path, "id", SrViewRow::id, null, null, { row, value -> row.copy(id = value) }, ScrapreasonId.pgType)

      override fun scrapreasonid(): Field<ScrapreasonId, SrViewRow> = Field<ScrapreasonId, SrViewRow>(_path, "scrapreasonid", SrViewRow::scrapreasonid, null, null, { row, value -> row.copy(scrapreasonid = value) }, ScrapreasonId.pgType)

      override fun name(): Field<Name, SrViewRow> = Field<Name, SrViewRow>(_path, "name", SrViewRow::name, null, null, { row, value -> row.copy(name = value) }, Name.pgType)

      override fun modifieddate(): Field<LocalDateTime, SrViewRow> = Field<LocalDateTime, SrViewRow>(_path, "modifieddate", SrViewRow::modifieddate, null, null, { row, value -> row.copy(modifieddate = value) }, PgTypes.timestamp)

      override fun _path(): List<Path> = _path

      override fun columns(): List<FieldLike<*, SrViewRow>> = listOf(this.id().underlying, this.scrapreasonid().underlying, this.name().underlying, this.modifieddate().underlying)

      override fun withPaths(_path: List<Path>): RelationStructure<SrViewFields, SrViewRow> = Impl(_path)
    }

    val structure: Impl = Impl(emptyList<typr.dsl.Path>())
  }
}